// Generated by scripts/n1-listening/gen.py. Do not edit directly.
/** N1 听解目录（只含章节标题），供首屏目录使用；完整页码/音轨见 listening-n1-book.ts。 */
export const listeningN1CatalogWeeks = [
	{
		"n": 1,
		"title": "準備しよう",
		"title_cn": "做好基础准备",
		"title_en": "Mastering the Basics",
		"days": [
			{
				"day": 1,
				"title": "発音に関する聞き取り",
				"title_cn": "听清楚发音",
				"title_en": "Pronunciation"
			},
			{
				"day": 2,
				"title": "文法に関する聞き取り①",
				"title_cn": "听清楚语法①",
				"title_en": "Grammar ①"
			},
			{
				"day": 3,
				"title": "文法に関する聞き取り②",
				"title_cn": "听清楚语法②",
				"title_en": "Grammar ②"
			},
			{
				"day": 4,
				"title": "会話表現",
				"title_cn": "会话表达方式",
				"title_en": "Conversational expressions"
			},
			{
				"day": 5,
				"title": "まとめ問題",
				"title_cn": "小结练习",
				"title_en": "Review"
			}
		]
	},
	{
		"n": 2,
		"title": "問題のパターンに慣れよう",
		"title_cn": "熟悉题型",
		"title_en": "Recognizing the Question Patterns",
		"days": [
			{
				"day": 1,
				"title": "どんな返事をしますか ―即時応答―",
				"title_cn": "该怎么回答——即时应答",
				"title_en": "Quick response"
			},
			{
				"day": 2,
				"title": "このあと何をしますか ―課題理解―",
				"title_cn": "接下来要干什么——课题理解",
				"title_en": "Task-based comprehension"
			},
			{
				"day": 3,
				"title": "どうしてですか ―ポイント理解―",
				"title_cn": "为什么——要点理解",
				"title_en": "Comprehension of key points"
			},
			{
				"day": 4,
				"title": "どんな内容ですか ―概要理解―",
				"title_cn": "是什么内容——概要理解",
				"title_en": "Comprehension of general outline"
			},
			{
				"day": 5,
				"title": "どうすることにしますか ―統合理解①―",
				"title_cn": "决定怎么做——综合理解①",
				"title_en": "Integrated comprehension ①"
			},
			{
				"day": 6,
				"title": "どれにしますか ―統合理解②―",
				"title_cn": "选哪一个——综合理解②",
				"title_en": "Integrated comprehension ②"
			},
			{
				"day": 7,
				"title": "まとめ問題",
				"title_cn": "小结练习",
				"title_en": "Review"
			}
		]
	},
	{
		"n": 3,
		"title": "いろいろなタイプの話を聞こう",
		"title_cn": "听懂各种类型的会话",
		"title_en": "Understanding Different Types of Talk",
		"days": [
			{
				"day": 1,
				"title": "情報を聞こう",
				"title_cn": "听清信息",
				"title_en": "Listening for information"
			},
			{
				"day": 2,
				"title": "指示を聞こう",
				"title_cn": "听清指示",
				"title_en": "Listening to instructions"
			},
			{
				"day": 3,
				"title": "説明を聞こう",
				"title_cn": "听清说明",
				"title_en": "Listening to explanations"
			},
			{
				"day": 4,
				"title": "テーマや言いたいことを聞こう",
				"title_cn": "听清主题和想要表达的内容",
				"title_en": "Themes and main points"
			},
			{
				"day": 5,
				"title": "まとめ問題",
				"title_cn": "小结练习",
				"title_en": "Review"
			}
		]
	},
	{
		"n": 4,
		"title": "いろいろな語彙や表現を覚えよう",
		"title_cn": "记住各种各样的单词和表达方式",
		"title_en": "Learning Vocabulary and Expressions",
		"days": [
			{
				"day": 1,
				"title": "よく聞くカタカナを覚えよう①",
				"title_cn": "记住常听到的片假名词①",
				"title_en": "Common katakana words ①"
			},
			{
				"day": 2,
				"title": "よく聞くカタカナを覚えよう②",
				"title_cn": "记住常听到的片假名词②",
				"title_en": "Common katakana words ②"
			},
			{
				"day": 3,
				"title": "言い換えの言葉を覚えよう",
				"title_cn": "记住换一种说法",
				"title_en": "Paraphrases"
			},
			{
				"day": 4,
				"title": "よく聞く表現を覚えよう",
				"title_cn": "记住常用的表达方式",
				"title_en": "Common expressions"
			},
			{
				"day": 5,
				"title": "まとめ問題",
				"title_cn": "小结练习",
				"title_en": "Review"
			}
		]
	},
	{
		"n": 5,
		"title": "総まとめ問題",
		"title_cn": "综合练习",
		"title_en": "Comprehensive Review",
		"days": [
			{
				"day": 1,
				"title": "問題 I",
				"title_cn": "问题Ⅰ 课题理解",
				"title_en": "Question I"
			},
			{
				"day": 2,
				"title": "問題 II",
				"title_cn": "问题Ⅱ 要点理解",
				"title_en": "Question II"
			},
			{
				"day": 3,
				"title": "問題 III",
				"title_cn": "问题Ⅲ 概要理解",
				"title_en": "Question III"
			},
			{
				"day": 4,
				"title": "問題 IV",
				"title_cn": "问题Ⅳ 即时应答",
				"title_en": "Question IV"
			},
			{
				"day": 5,
				"title": "問題 V",
				"title_cn": "问题Ⅴ 综合理解",
				"title_en": "Question V"
			}
		]
	}
] as const;
