// Generated by scripts/n1-listening/gen.py from the book scans (scripts/n1-listening/). Do not edit directly.
export type ListeningN1Disc = "cd1" | "cd2";
export type ListeningDisc = ListeningN1Disc;

export type ListeningN1Section = {
	readonly number: number;
	readonly title: string;
	readonly subtitle: string;
	readonly title_cn: string;
	readonly title_en: string;
	readonly disc: ListeningN1Disc;
	readonly firstTrack: number;
	readonly pages: readonly { readonly page: number; readonly tracks: readonly number[] }[];
	readonly questions: readonly { readonly label: string; readonly tracks: readonly number[] }[];
	readonly answerPages: readonly number[];
	readonly translationPages: readonly number[];
};

export type ListeningN1Chapter = {
	readonly number: number;
	readonly title: string;
	readonly title_cn: string;
	readonly title_en: string;
	readonly description: string;
	readonly sections: readonly ListeningN1Section[];
};

/**
 * 『新日语能力考试考前对策 N1 聴解』（日本語総まとめ N1 聴解 中文版）+ 原书 MP3（2 张 CD）。
 * 页码 = 书上印刷的页码；CD1 01/19/54、CD2 09 是章节标题音轨，不挂在题目上。
 * 用户提供的音频里缺 CD2 的 19、22、23、27、48 五条（对应题目保留原文和译文，标注音频缺失）。
 */
export const LISTENING_N1_MISSING_TRACKS: Readonly<Record<ListeningN1Disc, readonly number[]>> = { cd1: [], cd2: [19, 22, 23, 27, 48] };

export function listeningN1PageSrc(page: number) {
	return `/listening/n1/pages/${String(page).padStart(3, "0")}.jpg`;
}

export function listeningN1TrackSrc(disc: ListeningN1Disc, track: number) {
	const prefix = disc === "cd1" ? "CD01" : "CD02";
	return `/audio/n1/${disc}/${prefix}_${String(track).padStart(2, "0")}.mp3`;
}

export const listeningN1Chapters: readonly ListeningN1Chapter[] = [
	{
		"number": 1,
		"title": "準備しよう",
		"title_cn": "做好基础准备",
		"title_en": "Mastering the Basics",
		"description": "从发音、语法到口语表达，打好 N1 听力的基础。",
		"sections": [
			{
				"number": 1,
				"title": "発音に関する聞き取り",
				"subtitle": "発音と表記",
				"title_cn": "听清楚发音",
				"title_en": "Pronunciation",
				"disc": "cd1",
				"pages": [
					{
						"page": 12,
						"tracks": []
					},
					{
						"page": 13,
						"tracks": [
							2,
							3,
							4
						]
					}
				],
				"questions": [
					{
						"label": "1番",
						"tracks": [
							2
						]
					},
					{
						"label": "2番",
						"tracks": [
							3
						]
					},
					{
						"label": "3番",
						"tracks": [
							4
						]
					}
				],
				"answerPages": [
					72
				],
				"translationPages": [
					73
				],
				"firstTrack": 2
			},
			{
				"number": 2,
				"title": "文法に関する聞き取り①",
				"subtitle": "縮約形・助詞",
				"title_cn": "听清楚语法①",
				"title_en": "Grammar ①",
				"disc": "cd1",
				"pages": [
					{
						"page": 14,
						"tracks": []
					},
					{
						"page": 15,
						"tracks": [
							5,
							6
						]
					}
				],
				"questions": [
					{
						"label": "1番",
						"tracks": [
							5
						]
					},
					{
						"label": "2番",
						"tracks": [
							6
						]
					}
				],
				"answerPages": [
					74
				],
				"translationPages": [
					75
				],
				"firstTrack": 5
			},
			{
				"number": 3,
				"title": "文法に関する聞き取り②",
				"subtitle": "敬語",
				"title_cn": "听清楚语法②",
				"title_en": "Grammar ②",
				"disc": "cd1",
				"pages": [
					{
						"page": 16,
						"tracks": []
					},
					{
						"page": 17,
						"tracks": [
							7,
							8
						]
					}
				],
				"questions": [
					{
						"label": "1番",
						"tracks": [
							7
						]
					},
					{
						"label": "2番",
						"tracks": [
							8
						]
					}
				],
				"answerPages": [
					76
				],
				"translationPages": [
					77
				],
				"firstTrack": 7
			},
			{
				"number": 4,
				"title": "会話表現",
				"subtitle": "会話らしい表現",
				"title_cn": "会话表达方式",
				"title_en": "Conversational expressions",
				"disc": "cd1",
				"pages": [
					{
						"page": 18,
						"tracks": []
					},
					{
						"page": 19,
						"tracks": [
							9,
							10
						]
					}
				],
				"questions": [
					{
						"label": "1番",
						"tracks": [
							9
						]
					},
					{
						"label": "2番",
						"tracks": [
							10
						]
					}
				],
				"answerPages": [
					78
				],
				"translationPages": [
					79
				],
				"firstTrack": 9
			},
			{
				"number": 5,
				"title": "まとめ問題",
				"subtitle": "総合練習",
				"title_cn": "小结练习",
				"title_en": "Review",
				"disc": "cd1",
				"pages": [
					{
						"page": 20,
						"tracks": [
							11,
							12
						]
					},
					{
						"page": 21,
						"tracks": [
							13,
							14
						]
					},
					{
						"page": 22,
						"tracks": [
							15,
							16,
							17,
							18
						]
					}
				],
				"questions": [
					{
						"label": "問題Ⅰ",
						"tracks": [
							11
						]
					},
					{
						"label": "問題Ⅱ 1番",
						"tracks": [
							12
						]
					},
					{
						"label": "問題Ⅱ 2番",
						"tracks": [
							13
						]
					},
					{
						"label": "問題Ⅱ 3番",
						"tracks": [
							14
						]
					},
					{
						"label": "問題Ⅱ 4番",
						"tracks": [
							15
						]
					},
					{
						"label": "問題Ⅲ 1番",
						"tracks": [
							16
						]
					},
					{
						"label": "問題Ⅲ 2番",
						"tracks": [
							17
						]
					},
					{
						"label": "問題Ⅲ 3番",
						"tracks": [
							18
						]
					}
				],
				"answerPages": [
					80,
					82,
					84
				],
				"translationPages": [
					81,
					83,
					85
				],
				"firstTrack": 11
			}
		]
	},
	{
		"number": 2,
		"title": "問題のパターンに慣れよう",
		"title_cn": "熟悉题型",
		"title_en": "Recognizing the Question Patterns",
		"description": "针对 N1 全部听力题型，边练边熟悉作答流程。",
		"sections": [
			{
				"number": 1,
				"title": "どんな返事をしますか ―即時応答―",
				"subtitle": "即時応答",
				"title_cn": "该怎么回答——即时应答",
				"title_en": "Quick response",
				"disc": "cd1",
				"pages": [
					{
						"page": 24,
						"tracks": [
							20
						]
					},
					{
						"page": 25,
						"tracks": [
							21,
							22,
							23,
							24
						]
					}
				],
				"questions": [
					{
						"label": "例",
						"tracks": [
							20
						]
					},
					{
						"label": "1番",
						"tracks": [
							21
						]
					},
					{
						"label": "2番",
						"tracks": [
							22
						]
					},
					{
						"label": "3番",
						"tracks": [
							23
						]
					},
					{
						"label": "4番",
						"tracks": [
							24
						]
					}
				],
				"answerPages": [
					86
				],
				"translationPages": [
					87
				],
				"firstTrack": 20
			},
			{
				"number": 2,
				"title": "このあと何をしますか ―課題理解―",
				"subtitle": "課題理解",
				"title_cn": "接下来要干什么——课题理解",
				"title_en": "Task-based comprehension",
				"disc": "cd1",
				"pages": [
					{
						"page": 26,
						"tracks": [
							25
						]
					},
					{
						"page": 27,
						"tracks": [
							26,
							27
						]
					}
				],
				"questions": [
					{
						"label": "例",
						"tracks": [
							25
						]
					},
					{
						"label": "1番",
						"tracks": [
							26
						]
					},
					{
						"label": "2番",
						"tracks": [
							27
						]
					}
				],
				"answerPages": [
					88
				],
				"translationPages": [
					89
				],
				"firstTrack": 25
			},
			{
				"number": 3,
				"title": "どうしてですか ―ポイント理解―",
				"subtitle": "ポイント理解",
				"title_cn": "为什么——要点理解",
				"title_en": "Comprehension of key points",
				"disc": "cd1",
				"pages": [
					{
						"page": 28,
						"tracks": [
							28,
							29
						]
					},
					{
						"page": 29,
						"tracks": [
							30,
							31
						]
					}
				],
				"questions": [
					{
						"label": "例",
						"tracks": [
							29
						]
					},
					{
						"label": "1番",
						"tracks": [
							30
						]
					},
					{
						"label": "2番",
						"tracks": [
							31
						]
					}
				],
				"answerPages": [
					90
				],
				"translationPages": [
					91
				],
				"firstTrack": 29
			},
			{
				"number": 4,
				"title": "どんな内容ですか ―概要理解―",
				"subtitle": "概要理解",
				"title_cn": "是什么内容——概要理解",
				"title_en": "Comprehension of general outline",
				"disc": "cd1",
				"pages": [
					{
						"page": 30,
						"tracks": [
							32
						]
					},
					{
						"page": 31,
						"tracks": [
							33,
							34
						]
					}
				],
				"questions": [
					{
						"label": "例",
						"tracks": [
							32
						]
					},
					{
						"label": "1番",
						"tracks": [
							33
						]
					},
					{
						"label": "2番",
						"tracks": [
							34
						]
					}
				],
				"answerPages": [
					92
				],
				"translationPages": [
					93
				],
				"firstTrack": 32
			},
			{
				"number": 5,
				"title": "どうすることにしますか ―統合理解①―",
				"subtitle": "統合理解①",
				"title_cn": "决定怎么做——综合理解①",
				"title_en": "Integrated comprehension ①",
				"disc": "cd1",
				"pages": [
					{
						"page": 32,
						"tracks": [
							35
						]
					},
					{
						"page": 33,
						"tracks": [
							36,
							37
						]
					}
				],
				"questions": [
					{
						"label": "例",
						"tracks": [
							35
						]
					},
					{
						"label": "1番",
						"tracks": [
							36
						]
					},
					{
						"label": "2番",
						"tracks": [
							37
						]
					}
				],
				"answerPages": [
					94
				],
				"translationPages": [
					95
				],
				"firstTrack": 35
			},
			{
				"number": 6,
				"title": "どれにしますか ―統合理解②―",
				"subtitle": "統合理解②",
				"title_cn": "选哪一个——综合理解②",
				"title_en": "Integrated comprehension ②",
				"disc": "cd1",
				"pages": [
					{
						"page": 34,
						"tracks": [
							38
						]
					},
					{
						"page": 35,
						"tracks": [
							39,
							40
						]
					}
				],
				"questions": [
					{
						"label": "例1",
						"tracks": [
							38
						]
					},
					{
						"label": "例 質問1",
						"tracks": [
							39
						]
					},
					{
						"label": "例 質問2",
						"tracks": [
							39
						]
					},
					{
						"label": "1番",
						"tracks": [
							40
						]
					},
					{
						"label": "2番",
						"tracks": [
							40
						]
					}
				],
				"answerPages": [
					96
				],
				"translationPages": [
					97
				],
				"firstTrack": 38
			},
			{
				"number": 7,
				"title": "まとめ問題",
				"subtitle": "総合練習",
				"title_cn": "小结练习",
				"title_en": "Review",
				"disc": "cd1",
				"pages": [
					{
						"page": 36,
						"tracks": [
							41,
							42,
							43,
							44,
							45,
							46,
							47
						]
					},
					{
						"page": 37,
						"tracks": [
							48,
							49,
							50,
							51
						]
					},
					{
						"page": 38,
						"tracks": [
							52,
							53
						]
					}
				],
				"questions": [
					{
						"label": "問題Ⅰ 1番",
						"tracks": [
							41
						]
					},
					{
						"label": "問題Ⅰ 2番",
						"tracks": [
							42
						]
					},
					{
						"label": "問題Ⅰ 3番",
						"tracks": [
							43
						]
					},
					{
						"label": "問題Ⅰ 4番",
						"tracks": [
							44
						]
					},
					{
						"label": "問題Ⅰ 5番",
						"tracks": [
							45
						]
					},
					{
						"label": "問題Ⅱ 1番",
						"tracks": [
							46
						]
					},
					{
						"label": "問題Ⅱ 2番",
						"tracks": [
							47
						]
					},
					{
						"label": "問題Ⅲ 1番",
						"tracks": [
							48
						]
					},
					{
						"label": "問題Ⅲ 2番",
						"tracks": [
							49
						]
					},
					{
						"label": "問題Ⅳ 1番",
						"tracks": [
							50
						]
					},
					{
						"label": "問題Ⅳ 2番",
						"tracks": [
							51
						]
					},
					{
						"label": "問題Ⅴ 1番",
						"tracks": [
							52
						]
					},
					{
						"label": "問題Ⅴ 2番",
						"tracks": [
							53
						]
					}
				],
				"answerPages": [
					98,
					100,
					102,
					104,
					106
				],
				"translationPages": [
					99,
					101,
					103,
					105,
					107
				],
				"firstTrack": 41
			}
		]
	},
	{
		"number": 3,
		"title": "いろいろなタイプの話を聞こう",
		"title_cn": "听懂各种类型的会话",
		"title_en": "Understanding Different Types of Talk",
		"description": "练习听清信息、指示、说明，以及话题和说话人的主张。",
		"sections": [
			{
				"number": 1,
				"title": "情報を聞こう",
				"subtitle": "情報",
				"title_cn": "听清信息",
				"title_en": "Listening for information",
				"disc": "cd1",
				"pages": [
					{
						"page": 40,
						"tracks": []
					},
					{
						"page": 41,
						"tracks": [
							55,
							56,
							57
						]
					}
				],
				"questions": [
					{
						"label": "1番",
						"tracks": [
							55
						]
					},
					{
						"label": "2番",
						"tracks": [
							56
						]
					},
					{
						"label": "3番",
						"tracks": [
							57
						]
					}
				],
				"answerPages": [
					108
				],
				"translationPages": [
					109
				],
				"firstTrack": 55
			},
			{
				"number": 2,
				"title": "指示を聞こう",
				"subtitle": "指示",
				"title_cn": "听清指示",
				"title_en": "Listening to instructions",
				"disc": "cd1",
				"pages": [
					{
						"page": 42,
						"tracks": []
					},
					{
						"page": 43,
						"tracks": [
							58,
							59,
							60
						]
					}
				],
				"questions": [
					{
						"label": "1番",
						"tracks": [
							58
						]
					},
					{
						"label": "2番",
						"tracks": [
							59
						]
					},
					{
						"label": "3番",
						"tracks": [
							60
						]
					}
				],
				"answerPages": [
					110
				],
				"translationPages": [
					111
				],
				"firstTrack": 58
			},
			{
				"number": 3,
				"title": "説明を聞こう",
				"subtitle": "説明",
				"title_cn": "听清说明",
				"title_en": "Listening to explanations",
				"disc": "cd1",
				"pages": [
					{
						"page": 44,
						"tracks": []
					},
					{
						"page": 45,
						"tracks": [
							61,
							62,
							63
						]
					}
				],
				"questions": [
					{
						"label": "1番",
						"tracks": [
							61
						]
					},
					{
						"label": "2番",
						"tracks": [
							62
						]
					},
					{
						"label": "3番",
						"tracks": [
							63
						]
					}
				],
				"answerPages": [
					112
				],
				"translationPages": [
					113
				],
				"firstTrack": 61
			},
			{
				"number": 4,
				"title": "テーマや言いたいことを聞こう",
				"subtitle": "テーマ・主張",
				"title_cn": "听清主题和想要表达的内容",
				"title_en": "Themes and main points",
				"disc": "cd1",
				"pages": [
					{
						"page": 46,
						"tracks": []
					},
					{
						"page": 47,
						"tracks": [
							64,
							65,
							66
						]
					}
				],
				"questions": [
					{
						"label": "1番",
						"tracks": [
							64
						]
					},
					{
						"label": "2番",
						"tracks": [
							65
						]
					},
					{
						"label": "3番",
						"tracks": [
							66
						]
					}
				],
				"answerPages": [
					114
				],
				"translationPages": [
					115
				],
				"firstTrack": 64
			},
			{
				"number": 5,
				"title": "まとめ問題",
				"subtitle": "総合練習",
				"title_cn": "小结练习",
				"title_en": "Review",
				"disc": "cd2",
				"pages": [
					{
						"page": 48,
						"tracks": [
							1,
							2,
							3
						]
					},
					{
						"page": 49,
						"tracks": [
							4,
							5,
							6
						]
					},
					{
						"page": 50,
						"tracks": [
							7,
							8
						]
					}
				],
				"questions": [
					{
						"label": "問題Ⅰ 1番",
						"tracks": [
							1
						]
					},
					{
						"label": "問題Ⅰ 2番",
						"tracks": [
							2
						]
					},
					{
						"label": "問題Ⅰ 3番",
						"tracks": [
							3
						]
					},
					{
						"label": "問題Ⅱ 1番",
						"tracks": [
							4
						]
					},
					{
						"label": "問題Ⅱ 2番",
						"tracks": [
							5
						]
					},
					{
						"label": "問題Ⅱ 3番",
						"tracks": [
							6
						]
					},
					{
						"label": "問題Ⅲ 1番",
						"tracks": [
							7
						]
					},
					{
						"label": "問題Ⅲ 2番",
						"tracks": [
							8
						]
					}
				],
				"answerPages": [
					116,
					118,
					120
				],
				"translationPages": [
					117,
					119,
					121
				],
				"firstTrack": 1
			}
		]
	},
	{
		"number": 4,
		"title": "いろいろな語彙や表現を覚えよう",
		"title_cn": "记住各种各样的单词和表达方式",
		"title_en": "Learning Vocabulary and Expressions",
		"description": "常听到的片假名词、换一种说法的词语和口语惯用表达。",
		"sections": [
			{
				"number": 1,
				"title": "よく聞くカタカナを覚えよう①",
				"subtitle": "カタカナ語",
				"title_cn": "记住常听到的片假名词①",
				"title_en": "Common katakana words ①",
				"disc": "cd2",
				"pages": [
					{
						"page": 52,
						"tracks": []
					},
					{
						"page": 53,
						"tracks": [
							10,
							11,
							12,
							13
						]
					}
				],
				"questions": [
					{
						"label": "1番",
						"tracks": [
							10
						]
					},
					{
						"label": "2番",
						"tracks": [
							11
						]
					},
					{
						"label": "3番",
						"tracks": [
							12
						]
					},
					{
						"label": "4番",
						"tracks": [
							13
						]
					}
				],
				"answerPages": [
					122
				],
				"translationPages": [
					123
				],
				"firstTrack": 10
			},
			{
				"number": 2,
				"title": "よく聞くカタカナを覚えよう②",
				"subtitle": "カタカナ語",
				"title_cn": "记住常听到的片假名词②",
				"title_en": "Common katakana words ②",
				"disc": "cd2",
				"pages": [
					{
						"page": 54,
						"tracks": []
					},
					{
						"page": 55,
						"tracks": [
							14,
							15,
							16,
							17
						]
					}
				],
				"questions": [
					{
						"label": "1番",
						"tracks": [
							14
						]
					},
					{
						"label": "2番",
						"tracks": [
							15
						]
					},
					{
						"label": "3番",
						"tracks": [
							16
						]
					},
					{
						"label": "4番",
						"tracks": [
							17
						]
					}
				],
				"answerPages": [
					124
				],
				"translationPages": [
					125
				],
				"firstTrack": 14
			},
			{
				"number": 3,
				"title": "言い換えの言葉を覚えよう",
				"subtitle": "言い換え",
				"title_cn": "记住换一种说法",
				"title_en": "Paraphrases",
				"disc": "cd2",
				"pages": [
					{
						"page": 56,
						"tracks": []
					},
					{
						"page": 57,
						"tracks": [
							18,
							20,
							21
						]
					}
				],
				"questions": [
					{
						"label": "1番",
						"tracks": [
							18
						]
					},
					{
						"label": "2番",
						"tracks": []
					},
					{
						"label": "3番",
						"tracks": [
							20
						]
					},
					{
						"label": "4番",
						"tracks": [
							21
						]
					}
				],
				"answerPages": [
					126
				],
				"translationPages": [
					127
				],
				"firstTrack": 18
			},
			{
				"number": 4,
				"title": "よく聞く表現を覚えよう",
				"subtitle": "よく聞く表現",
				"title_cn": "记住常用的表达方式",
				"title_en": "Common expressions",
				"disc": "cd2",
				"pages": [
					{
						"page": 58,
						"tracks": []
					},
					{
						"page": 59,
						"tracks": [
							24,
							25
						]
					}
				],
				"questions": [
					{
						"label": "1番",
						"tracks": []
					},
					{
						"label": "2番",
						"tracks": []
					},
					{
						"label": "3番",
						"tracks": [
							24
						]
					},
					{
						"label": "4番",
						"tracks": [
							25
						]
					}
				],
				"answerPages": [
					128
				],
				"translationPages": [
					129
				],
				"firstTrack": 24
			},
			{
				"number": 5,
				"title": "まとめ問題",
				"subtitle": "総合練習",
				"title_cn": "小结练习",
				"title_en": "Review",
				"disc": "cd2",
				"pages": [
					{
						"page": 60,
						"tracks": [
							26,
							28
						]
					},
					{
						"page": 61,
						"tracks": [
							29,
							30,
							31
						]
					},
					{
						"page": 62,
						"tracks": [
							32,
							33
						]
					}
				],
				"questions": [
					{
						"label": "問題Ⅰ 1番",
						"tracks": [
							26
						]
					},
					{
						"label": "問題Ⅰ 2番",
						"tracks": []
					},
					{
						"label": "問題Ⅰ 3番",
						"tracks": [
							28
						]
					},
					{
						"label": "問題Ⅱ 1番",
						"tracks": [
							29
						]
					},
					{
						"label": "問題Ⅱ 2番",
						"tracks": [
							30
						]
					},
					{
						"label": "問題Ⅱ 3番",
						"tracks": [
							31
						]
					},
					{
						"label": "問題Ⅲ 1番",
						"tracks": [
							32
						]
					},
					{
						"label": "問題Ⅲ 2番",
						"tracks": [
							33
						]
					}
				],
				"answerPages": [
					130,
					132,
					134,
					136,
					138
				],
				"translationPages": [
					131,
					133,
					135,
					137,
					139
				],
				"firstTrack": 26
			}
		]
	},
	{
		"number": 5,
		"title": "総まとめ問題",
		"title_cn": "综合练习",
		"title_en": "Comprehensive Review",
		"description": "按正式考试的五种题型做一套模拟题（30 分钟）。",
		"sections": [
			{
				"number": 1,
				"title": "問題 I",
				"subtitle": "課題理解",
				"title_cn": "问题Ⅰ 课题理解",
				"title_en": "Question I",
				"disc": "cd2",
				"pages": [
					{
						"page": 64,
						"tracks": [
							34,
							35
						]
					},
					{
						"page": 65,
						"tracks": [
							36,
							37
						]
					}
				],
				"questions": [
					{
						"label": "1番",
						"tracks": [
							34
						]
					},
					{
						"label": "2番",
						"tracks": [
							35
						]
					},
					{
						"label": "3番",
						"tracks": [
							36
						]
					},
					{
						"label": "4番",
						"tracks": [
							37
						]
					}
				],
				"answerPages": [
					140,
					142
				],
				"translationPages": [
					141,
					143
				],
				"firstTrack": 34
			},
			{
				"number": 2,
				"title": "問題 II",
				"subtitle": "ポイント理解",
				"title_cn": "问题Ⅱ 要点理解",
				"title_en": "Question II",
				"disc": "cd2",
				"pages": [
					{
						"page": 66,
						"tracks": [
							38,
							39,
							40
						]
					},
					{
						"page": 67,
						"tracks": [
							41,
							42
						]
					}
				],
				"questions": [
					{
						"label": "1番",
						"tracks": [
							38
						]
					},
					{
						"label": "2番",
						"tracks": [
							39
						]
					},
					{
						"label": "3番",
						"tracks": [
							40
						]
					},
					{
						"label": "4番",
						"tracks": [
							41
						]
					},
					{
						"label": "5番",
						"tracks": [
							42
						]
					}
				],
				"answerPages": [
					144,
					146
				],
				"translationPages": [
					145,
					147
				],
				"firstTrack": 38
			},
			{
				"number": 3,
				"title": "問題 III",
				"subtitle": "概要理解",
				"title_cn": "问题Ⅲ 概要理解",
				"title_en": "Question III",
				"disc": "cd2",
				"pages": [
					{
						"page": 68,
						"tracks": [
							43,
							44,
							45,
							46
						]
					}
				],
				"questions": [
					{
						"label": "1番",
						"tracks": [
							43
						]
					},
					{
						"label": "2番",
						"tracks": [
							44
						]
					},
					{
						"label": "3番",
						"tracks": [
							45
						]
					},
					{
						"label": "4番",
						"tracks": [
							46
						]
					}
				],
				"answerPages": [
					148,
					150
				],
				"translationPages": [
					149,
					151
				],
				"firstTrack": 43
			},
			{
				"number": 4,
				"title": "問題 IV",
				"subtitle": "即時応答",
				"title_cn": "问题Ⅳ 即时应答",
				"title_en": "Question IV",
				"disc": "cd2",
				"pages": [
					{
						"page": 69,
						"tracks": [
							47,
							49,
							50,
							51,
							52,
							53
						]
					}
				],
				"questions": [
					{
						"label": "1番",
						"tracks": [
							47
						]
					},
					{
						"label": "2番",
						"tracks": []
					},
					{
						"label": "3番",
						"tracks": [
							49
						]
					},
					{
						"label": "4番",
						"tracks": [
							50
						]
					},
					{
						"label": "5番",
						"tracks": [
							51
						]
					},
					{
						"label": "6番",
						"tracks": [
							52
						]
					},
					{
						"label": "7番",
						"tracks": [
							53
						]
					}
				],
				"answerPages": [
					152
				],
				"translationPages": [
					153
				],
				"firstTrack": 47
			},
			{
				"number": 5,
				"title": "問題 V",
				"subtitle": "統合理解",
				"title_cn": "问题Ⅴ 综合理解",
				"title_en": "Question V",
				"disc": "cd2",
				"pages": [
					{
						"page": 70,
						"tracks": [
							54,
							55,
							56
						]
					}
				],
				"questions": [
					{
						"label": "1番",
						"tracks": [
							54
						]
					},
					{
						"label": "2番",
						"tracks": [
							55
						]
					},
					{
						"label": "3番",
						"tracks": [
							56
						]
					}
				],
				"answerPages": [
					154,
					156
				],
				"translationPages": [
					155,
					157
				],
				"firstTrack": 54
			}
		]
	}
];

export function listeningN1BookChapters(): readonly ListeningN1Chapter[] {
	return listeningN1Chapters;
}

export function findListeningN1Chapter(chapter: number) {
	return listeningN1Chapters.find((item) => item.number === chapter);
}

export function findListeningN1Section(chapter: number, section: number) {
	return findListeningN1Chapter(chapter)?.sections.find((item) => item.number === section);
}

export function listeningN1SectionDisc(chapter: number, section: number): ListeningN1Disc {
	return findListeningN1Section(chapter, section)?.disc ?? "cd1";
}
