import json, re
W="/workspace/wt-n1-listening"
SECS={s["key"]:s for s in json.load(open("sections.json"))}
CH={1:("準備しよう","做好基础准备","Mastering the Basics","从发音、语法到口语表达，打好 N1 听力的基础。"),
 2:("問題のパターンに慣れよう","熟悉题型","Recognizing the Question Patterns","针对 N1 全部听力题型，边练边熟悉作答流程。"),
 3:("いろいろなタイプの話を聞こう","听懂各种类型的会话","Understanding Different Types of Talk","练习听清信息、指示、说明，以及话题和说话人的主张。"),
 4:("いろいろな語彙や表現を覚えよう","记住各种各样的单词和表达方式","Learning Vocabulary and Expressions","常听到的片假名词、换一种说法的词语和口语惯用表达。"),
 5:("総まとめ問題","综合练习","Comprehensive Review","按正式考试的五种题型做一套模拟题（30 分钟）。")}
T={"1-1":("発音に関する聞き取り","発音と表記","听清楚发音","Pronunciation"),
"1-2":("文法に関する聞き取り①","縮約形・助詞","听清楚语法①","Grammar ①"),
"1-3":("文法に関する聞き取り②","敬語","听清楚语法②","Grammar ②"),
"1-4":("会話表現","会話らしい表現","会话表达方式","Conversational expressions"),
"1-5":("まとめ問題","総合練習","小结练习","Review"),
"2-1":("どんな返事をしますか ―即時応答―","即時応答","该怎么回答——即时应答","Quick response"),
"2-2":("このあと何をしますか ―課題理解―","課題理解","接下来要干什么——课题理解","Task-based comprehension"),
"2-3":("どうしてですか ―ポイント理解―","ポイント理解","为什么——要点理解","Comprehension of key points"),
"2-4":("どんな内容ですか ―概要理解―","概要理解","是什么内容——概要理解","Comprehension of general outline"),
"2-5":("どうすることにしますか ―統合理解①―","統合理解①","决定怎么做——综合理解①","Integrated comprehension ①"),
"2-6":("どれにしますか ―統合理解②―","統合理解②","选哪一个——综合理解②","Integrated comprehension ②"),
"2-7":("まとめ問題","総合練習","小结练习","Review"),
"3-1":("情報を聞こう","情報","听清信息","Listening for information"),
"3-2":("指示を聞こう","指示","听清指示","Listening to instructions"),
"3-3":("説明を聞こう","説明","听清说明","Listening to explanations"),
"3-4":("テーマや言いたいことを聞こう","テーマ・主張","听清主题和想要表达的内容","Themes and main points"),
"3-5":("まとめ問題","総合練習","小结练习","Review"),
"4-1":("よく聞くカタカナを覚えよう①","カタカナ語","记住常听到的片假名词①","Common katakana words ①"),
"4-2":("よく聞くカタカナを覚えよう②","カタカナ語","记住常听到的片假名词②","Common katakana words ②"),
"4-3":("言い換えの言葉を覚えよう","言い換え","记住换一种说法","Paraphrases"),
"4-4":("よく聞く表現を覚えよう","よく聞く表現","记住常用的表达方式","Common expressions"),
"4-5":("まとめ問題","総合練習","小结练习","Review"),
"5-1":("問題 I","課題理解","问题Ⅰ 课题理解","Question I"),
"5-2":("問題 II","ポイント理解","问题Ⅱ 要点理解","Question II"),
"5-3":("問題 III","概要理解","问题Ⅲ 概要理解","Question III"),
"5-4":("問題 IV","即時応答","问题Ⅳ 即时应答","Question IV"),
"5-5":("問題 V","統合理解","问题Ⅴ 综合理解","Question V")}
MISSING={2:{19,22,23,27,48}}
def ocr(n): return open(f"ocr/{n:03d}.txt").read()
def ts(o): return json.dumps(o,ensure_ascii=False,indent="\t")
lessons={}
for key,s in SECS.items():
    d=json.load(open(f"lessons/{key}.json"))
    ch,sec=map(int,key.split("-")); disc=s["disc"]
    h=d["blocks"][0]; h["no"]=sec; h["title"]=T[key][0] if ch<5 else h["title"]; h["cn"]=T[key][2]; h.setdefault("en",T[key][3]); h["en"]=T[key][3]
    if not h.get("kana"): h.pop("kana",None)
    for b in d["blocks"]:
        if b["type"]=="q" and b.get("tracks"):
            gone=[t for t in b["tracks"] if t in MISSING.get(disc,set())]
            if gone:
                b["tracks"]=[t for t in b["tracks"] if t not in gone]
                msg="⚠ 本题音频缺失（CD%d · %s），可先看听力原文和译文练习。"%(disc," / ".join("%02d"%t for t in gone))
                b["note"]=(b.get("note","")+"\n"+msg).strip()
                if not b["tracks"]: del b["tracks"]
    lessons[key]=d
# book
secs_ts={c:[] for c in CH}
for key,s in SECS.items():
    ch,sec=map(int,key.split("-")); d=lessons[key]; disc=s["disc"]
    pages=[]
    for n in s["pages"]:
        tr=[int(m) for m in re.findall(r"TRACK %d-(\d+)"%disc,ocr(n))]
        tr=[t for t in dict.fromkeys(tr) if t not in MISSING.get(disc,set())]
        pages.append({"page":n,"tracks":tr})
    qs=[{"label":b["label"],"tracks":b.get("tracks",[])} for b in d["blocks"] if b["type"]=="q"]
    jp,sub,cn,en=T[key]
    secs_ts[ch].append(dict(number=sec,title=jp,subtitle=sub,title_cn=cn,title_en=en,disc="cd%d"%disc,pages=pages,questions=qs,answerPages=s["ans"],translationPages=s["tr"]))
chapters=[]
for c,(t,cn,en,desc) in CH.items():
    chapters.append(dict(number=c,title=t,title_cn=cn,title_en=en,description=desc,sections=[{**x,"firstTrack":next((t for q in x["questions"] for t in q["tracks"]),1)} for x in secs_ts[c]]))
book=f'''// Generated by scripts/n1-listening/gen.py from the book scans (scripts/n1-listening/). Do not edit directly.
export type ListeningN1Disc = "cd1" | "cd2";
export type ListeningDisc = ListeningN1Disc;

export type ListeningN1Section = {{
	readonly number: number;
	readonly title: string;
	readonly subtitle: string;
	readonly title_cn: string;
	readonly title_en: string;
	readonly disc: ListeningN1Disc;
	readonly firstTrack: number;
	readonly pages: readonly {{ readonly page: number; readonly tracks: readonly number[] }}[];
	readonly questions: readonly {{ readonly label: string; readonly tracks: readonly number[] }}[];
	readonly answerPages: readonly number[];
	readonly translationPages: readonly number[];
}};

export type ListeningN1Chapter = {{
	readonly number: number;
	readonly title: string;
	readonly title_cn: string;
	readonly title_en: string;
	readonly description: string;
	readonly sections: readonly ListeningN1Section[];
}};

/**
 * 『新日语能力考试考前对策 N1 聴解』（日本語総まとめ N1 聴解 中文版）+ 原书 MP3（2 张 CD）。
 * 页码 = 书上印刷的页码；CD1 01/19/54、CD2 09 是章节标题音轨，不挂在题目上。
 * 用户提供的音频里缺 CD2 的 19、22、23、27、48 五条（对应题目保留原文和译文，标注音频缺失）。
 */
export const LISTENING_N1_MISSING_TRACKS: Readonly<Record<ListeningN1Disc, readonly number[]>> = {{ cd1: [], cd2: [19, 22, 23, 27, 48] }};

export function listeningN1PageSrc(page: number) {{
	return `/listening/n1/pages/${{String(page).padStart(3, "0")}}.jpg`;
}}

export function listeningN1TrackSrc(disc: ListeningN1Disc, track: number) {{
	const prefix = disc === "cd1" ? "CD01" : "CD02";
	return `/audio/n1/${{disc}}/${{prefix}}_${{String(track).padStart(2, "0")}}.mp3`;
}}

export const listeningN1Chapters: readonly ListeningN1Chapter[] = {ts(chapters)};

export function listeningN1BookChapters(): readonly ListeningN1Chapter[] {{
	return listeningN1Chapters;
}}

export function findListeningN1Chapter(chapter: number) {{
	return listeningN1Chapters.find((item) => item.number === chapter);
}}

export function findListeningN1Section(chapter: number, section: number) {{
	return findListeningN1Chapter(chapter)?.sections.find((item) => item.number === section);
}}

export function listeningN1SectionDisc(chapter: number, section: number): ListeningN1Disc {{
	return findListeningN1Section(chapter, section)?.disc ?? "cd1";
}}
'''
open(f"{W}/app/data/listening-n1-book.ts","w").write(book)
for c in CH:
    arr=[{k:lessons[f"{c}-{s}"][k] for k in ("blocks","answer","transcript","transcript_cn")} for s in range(1,len(secs_ts[c])+1)]
    open(f"{W}/app/data/listening-n1-lessons-ch{c}.ts","w").write(f'// Generated by scripts/n1-listening/gen.py from scripts/n1-listening/lessons/*.json. Do not edit directly.\nimport type {{ ListeningLesson }} from "./listening-n3-lesson-types";\n\nexport const chapter{c}Lessons: readonly ListeningLesson[] = {ts(arr)};\n')
print("ok")
cat=[dict(n=c["number"],title=c["title"],title_cn=c["title_cn"],title_en=c["title_en"],days=[dict(day=s["number"],title=s["title"],title_cn=s["title_cn"],title_en=s["title_en"]) for s in c["sections"]]) for c in chapters]
open(f"{W}/app/data/listening-n1-catalog.ts","w").write(f'''// Generated by scripts/n1-listening/gen.py. Do not edit directly.
/** N1 听解目录（只含章节标题），供首屏目录使用；完整页码/音轨见 listening-n1-book.ts。 */
export const listeningN1CatalogWeeks = {json.dumps(cat,ensure_ascii=False,indent="\t")} as const;
''')
