import json
exec(open('body_cn.py').read())
B=json.load(open('bodystr.json'))
m={B[i][0]:v for i,v in sorted(T.items())}
print(len(m))
body=json.dumps(m,ensure_ascii=False,indent="\t")
ts=f'''// Generated by scripts/n1-listening/mkbody.py from scripts/n1-listening/body_cn.py. Do not edit directly.
/** N1 听解正文（说明、例句、选项等书上没有附中文的部分）：日语原文 → 中文翻译。 */
export const listeningN1BodyCn: Readonly<Record<string, string>> = {body};

export function listeningN1BodyTranslation(text: string): string | undefined {{
	return listeningN1BodyCn[text] || undefined;
}}
'''
open('/workspace/wt-n1-listening/app/data/listening-n1-body-support.ts','w').write(ts)
