#!/usr/bin/env python3
"""Build app/data/lesson-review-glosses.json from curated cn/en pairs."""
from __future__ import annotations

import json
from pathlib import Path

# jp -> (cn, en)
PAIRS: list[tuple[str, str, str]] = [
    ("エドマルがいっぱい🐶", "Edmaru 的狗好多", "There are so many dogs at Edmaru"),
    ("めまい", "头晕", "dizziness"),
    ("テストは成績に影響する", "考试会影响成绩", "The test affects your grade"),
    ("AかBか", "是 A 还是 B", "A or B"),
    ("あまり大切じゃない", "不太重要", "not that important"),
    ("やっと終わったね", "终于结束了呢", "It's finally over"),
    ("なんでだろう", "为什么呢", "I wonder why"),
    ("他の生徒", "其他学生", "other students"),
    ("おばさん（middle age woman）🙅‍♀️→おねえさん（polite）", "叫中年女性不要用「おばさん」，礼貌说法是「おねえさん」", "Don't call a middle-aged woman obasan; oneesan is politer"),
    ("名前を呼ぶのが一番良いです！👍", "直接叫名字最好！", "Calling someone by name is best"),
    ("呼び方", "称呼方式", "how to address someone"),
    ("どんな呼び方が良いですか？", "怎样称呼比较好？", "What should I call you?"),
    ("お金を送ってもらうように言った", "让对方把钱寄过来", "I told them to send me the money"),
    ("スピーカーにした", "开了免提 / 开了扬声器", "I put it on speaker"),
    ("交番に連れて行きたかった", "想带去派出所", "I wanted to take them to the police box"),
    ("こわい", "可怕、害怕", "scary / I'm scared"),
    ("返す", "归还", "to return (something)"),
    ("tax 税金", "税", "tax"),
    ("発展途上国（はってんとじょうこく）", "发展中国家", "developing country"),
    ("国民", "国民", "citizen / the people"),
    ("兄弟", "兄弟", "siblings / brothers"),
    ("ドラえもんの暗記パンがほしい🍞🥐🥪😅", "好想要哆啦A梦的记忆面包", "I want Doraemon's memory bread"),
    ("練習すれば練習するほど、日本語が上手になる", "越练习，日语就越好", "The more you practice, the better your Japanese gets"),
    ("あまりにも", "过于、太", "too much / excessively"),
    ("あまり、、、ない", "不太……", "not very..."),
    ("なんて など", "「なんて」≈「など」（举例、之类）", "nante is like nado (and so on)"),
    ("アメリカは規制されていること以外は出来るんでね", "在美国，除了被限制的事情以外都能做", "In America you can do anything except what's restricted"),
    ("あとは州次第", "剩下的就看各州了", "The rest depends on the state"),
    ("日本は法律に書いてあることしか出来ない", "在日本，法律没写的就不能做", "In Japan you can only do what's written in the law"),
    ("この違いでしょうね", "大概就是这个差别吧", "That's probably the difference"),
    ("LINEのグループの人と言いった", "跟 LINE 群里的人说了", "I told someone in the LINE group"),
    ("本当に？", "真的吗？", "Really?"),
    ("素晴らしい，ストーリー、マジでドロドロでやばい", "太精彩了，剧情真的又狗血又刺激", "Amazing story — it's messy and wild"),
    ("主人公は生まれ育った家庭の影響で、よく現実から逃げてしまう。例えば一人で今の環境を離れ、誰にも連絡がつかないようにする。結婚して 10 年経った今、1 年間姿を消した。", "主角受原生家庭影响，常常逃避现实。比如一个人离开现在的环境，让谁都联系不上。结婚十年了，却消失了一整年。", "The protagonist often runs from reality because of their family. They disappear for a whole year after ten years of marriage."),
    ("このドラマのヒロインは 31 歳の時に 4 回結婚した。そして 5 人目の夫は彼女が過去に結婚していたことを知らない。", "这部剧的女主 31 岁结过 4 次婚。第五任丈夫不知道她结过婚。", "The heroine married four times by 31. Her fifth husband doesn't know."),
    ("4 人目は起業家で、バーでナンパされて結婚した。結婚翌日に会社が潰れちゃった。", "第四任是创业者，在酒吧被搭讪后结婚。结婚第二天公司就倒了。", "The fourth husband was an entrepreneur she met at a bar. His company collapsed the next day."),
    ("マジでウケる（really funny", "真的好好笑", "really funny"),
    ("Bのうちで掃除した時", "在 B 家里打扫的时候", "when cleaning at B's house"),
    ("A 帰ります", "A 要回去了", "A is going home"),
    ("DさんはAさんを殴るほぼ", "D 差点打了 A", "D almost hit A"),
    ("サイコパス", "精神病态 / 反社会人格", "psychopath"),
    ("病院に行くように言われた", "被要求去医院", "I was told to go to the hospital"),
    ("生きてるか死んでるか分からない", "不知道是活着还是死了", "I don't know if they're alive or dead"),
    ("仲直り", "和好", "to make up / reconcile"),
    ("最初の", "最初的", "the first / initial"),
    ("奥さん", "太太、妻子（敬称）", "wife (polite)"),
    ("旦那", "丈夫", "husband"),
    ("免許証", "驾照 / 执照", "license"),
    ("相反する（あいはん", "相反、相互矛盾", "to conflict / be contrary"),
    ("大野さんがたくさん荷物を送るって言ってたから、それを一緒にやってもらっていい？", "大野说要寄很多行李，那个能一起帮忙弄吗？", "Ono said they'd send lots of luggage — can we do that together?"),
    ("ふわふわだった", "软软的、毛茸茸的", "it was fluffy"),
    ("もふもふ", "毛茸茸", "fluffy / soft to the touch"),
    ("よく世話されている", "被照顾得很好", "well taken care of"),
    ("字幕", "字幕", "subtitles"),
    ("突然", "突然", "suddenly"),
    ("旅の途中で", "在旅行途中", "during the trip"),
    ("ほぼ", "几乎、差不多", "almost / nearly"),
    ("召し上がる", "吃、喝（尊敬语）", "to eat / drink (honorific)"),
    ("その後なら", "如果是那之后的话", "if it's after that"),
    ("話しかけてきた", "过来搭话了", "came up and talked to me"),
    ("話すのが好き", "喜欢说话", "I like talking"),
    ("分からなかった", "当时没明白", "I didn't understand"),
    ("それでわかった", "这样才明白了", "that's how I understood"),
    ("うちかえるって言った", "说了「再来一趟」", "said I'd come back / drop by again"),
    ("ジム帰り", "从健身房回来", "on the way home from the gym"),
    ("立ち話（たちばなし）(站着闲谈", "站着聊天", "standing and chatting"),
    ("おじさんに会って立ち話をした", "碰到一位大叔，站着聊了一会儿", "I ran into an older man and chatted standing"),
    ("天才！てんさい", "天才！", "genius!"),
    ("完璧（かんぺき）じゃない", "并不完美", "it's not perfect"),
    ("どっちを使うかいつも考える", "总是在想该用哪一个", "I always think about which one to use"),
    ("やっといてよかった（ 还好事先做了、幸亏做了", "还好事先做了", "I'm glad I did it in advance"),
    ("やく（訳", "译、意思", "translation / meaning"),
    ("聞いてもいい", "可以问吗 / 问问也没关系", "Is it OK to ask?"),
    ("画面", "屏幕、画面", "screen"),
    ("同じ時間でいろんなことする", "同一时间做很多事", "do many things at the same time"),
    ("工場の人のお話を聞きます", "听工厂的人讲话", "listen to the factory worker"),
    ("てくださる：てくれる", "「てくださる」是「てくれる」的尊敬说法", "tekudasaru is the honorific of tekureru"),
    ("用意（ようい）して下さい", "请准备好", "please get it ready"),
    ("持ってこなくてもいい", "不用带过来也行", "you don't have to bring it"),
    ("他の荷物でいっぱいで", "被别的行李占满了", "it's full of other bags"),
    ("どこにも置く場所がないですね", "到处都没地方放呢", "there's nowhere to put it"),
    ("置いといて", "先放着吧", "just leave it there"),
    ("復活", "复活、恢复", "revival / come back"),
    ("起こる（おこる", "发生", "to happen"),
    ("シルバーウィーク", "黄金周之外的银色周（连休）", "Silver Week (a string of holidays)"),
    ("めっちゃ休み！(好长的假期", "假放得好长！", "such a long break!"),
    ("めっちゃ楽しみ！（期待", "超期待！", "I can't wait!"),
    ("くまのほんぐうたいしゃ", "熊野本宫大社", "Kumano Hongu Taisha shrine"),
    ("熊野古道（くまのこどう）", "熊野古道", "Kumano Kodo pilgrimage routes"),
    ("仕事して、お金貯めて、日本に来たのかな？", "是工作存钱才来日本的吧？", "Did they work, save money, and come to Japan?"),
    ("みんなができることじゃない", "不是谁都能做到的", "not everyone can do that"),
    ("間に合う", "来得及", "to make it in time"),
    ("間に合わないかもしれない", "可能来不及", "might not make it in time"),
    ("メキシコ人の友達がいて、彼女のおじいさんは日本人です。そのおかげで彼女は、35歳まで日本にいれるのですが、35歳を過ぎたらビザが切れてしまいます。なので、他のビザを取るために急がないといけません。ビザを取るのが難しくなる。", "我有个墨西哥朋友，她爷爷是日本人。所以她能待到 35 岁，一过 35 岁签证就到期。必须赶紧换别的签证，否则会更难拿。", "A Mexican friend can stay until 35 thanks to her Japanese grandfather. After that the visa expires, so she has to rush another one."),
    ("遊ぶのが楽しい", "玩很开心", "playing is fun"),
    ("働くのが大変", "工作很辛苦", "working is hard"),
    ("お得（おとく", "划算、便宜", "a good deal"),
    ("なんでだよ", "为什么啊", "come on, why?"),
    ("だろう？🙆", "「だろう？」可以用", "darou? is OK"),
    ("だろ？🙅", "「だろ？」不太好", "daro? is not great"),
    ("でしょ？🙆‍♀️", "「でしょ？」可以用", "desho? is OK"),
    ("行けば", "如果去的话", "if you go"),
    ("パン工場 （こうじょう", "面包工厂", "bread factory"),
    ("電車代 （ でんしゃだい", "电车费", "train fare"),
    ("マンガの面白いところを知りたい", "想知道漫画有趣的地方", "I want to know what makes the manga interesting"),
    ("マンガの面白さを知りたい", "想知道漫画的有趣之处", "I want to know the manga's appeal"),
    ("ナルトのアニメは感情が揺(yu)さぶられる。", "《火影忍者》会把人的感情搅动起来。", "Naruto really stirs your emotions."),
    ("見てる途中でキャラクターの感情を感じます。", "看着看着就能感受到角色的感情。", "While watching I feel the characters' emotions."),
    ("鬼滅の刃", "鬼灭之刃", "Demon Slayer"),
    ("妖精的尾巴", "妖精的尾巴", "Fairy Tail"),
    ("日语：FAIRY TAIL／フェアリーテイル", "日文名：FAIRY TAIL／フェアリーテイル", "Japanese title: Fairy Tail"),
    ("真岛浩", "真岛浩（漫画家）", "Hiro Mashima"),
    ("中国のこと、聞いてもいい？", "可以问你中国的事情吗？", "Can I ask you about China?"),
    ("日本はもっと前から速い新幹線がありました", "日本更早以前就有很快的新干线了", "Japan had fast shinkansen much earlier"),
    ("点数", "分数", "score / points"),
    ("早くうまくなりたい", "想快点变熟练", "I want to get good at it soon"),
    ("早くこの時期を乗り越えたい", "想快点度过这段时期", "I want to get through this period soon"),
    ("初心者", "初学者", "beginner"),
    ("もっと楽(らく)になった", "变得更轻松了", "it got easier"),
    ("後楽園連", "后乐园一带", "around Korakuen"),
    ("良い経験！", "很棒的经历！", "a great experience!"),
    ("雨が降ってもみんなおどってた", "即使下雨大家还在跳舞", "everyone kept dancing even in the rain"),
    ("もっと雨が降っても、さらに激しく踊ってた（おどってた）", "雨下得更大，大家跳得更疯", "even when it rained harder they danced more wildly"),
    ("思いっきり", "尽情地、全力地", "with all one's might"),
    ("良い思い出", "美好的回忆", "a good memory"),
    ("本物（ほんもの）みたいだった", "看起来像真的一样", "it looked like the real thing"),
    ("見るものが多すぎたので、全部見れませんでした。", "要看的东西太多，没能全看完。", "There was too much to see, so I couldn't see it all."),
    ("なので、また行きたいです。", "所以还想再去。", "So I want to go again."),
    ("第二次世界大戦（だいにじ せかいたいせん）", "第二次世界大战", "World War II"),
    ("兵士", "士兵", "soldier"),
    ("壁にあった", "在墙上", "it was on the wall"),
    ("終戦", "战争结束", "end of the war"),
    ("忘れないために", "为了不忘记", "so we don't forget"),
    ("このネックレスをみて、欲しいって言ってたんだ", "看到这条项链，说想要", "Saw this necklace and said they wanted it"),
    ("少し高いけど、お母さんが欲しがっているものをあげようよ", "有点贵，但把妈妈想要的东西给她吧", "It's a bit expensive, but let's give mom what she wants"),
    ("あげようよ", "给她吧 / 送给她吧", "let's give it to her"),
    ("喜ぶ（よろこぶ）", "高兴", "to be glad"),
    ("したい＋がる", "「たい」加上「がる」表示看起来想做", "tai + garu: looks like they want to"),
    ("食べたがっている", "看起来想吃", "looks like they want to eat"),
    ("食べたい", "想吃", "want to eat"),
    ("食べたがる", "显得想吃", "to show that one wants to eat"),
    ("荷物をお持ちします", "我来帮您拿行李（谦让）", "I'll carry your bags (humble)"),
    ("荷物をお持ちになります", "您拿行李（尊敬）", "you carry the bags (honorific)"),
    ("荷物をお持ちになりませんか？", "您要拿行李吗？（尊敬）", "Would you like to take the bags? (honorific)"),
    ("荷物をお持ちしましょうか。", "我来帮您拿行李吧？", "Shall I carry your bags?"),
    ("いつか静かになるでしょう", "总有一天会安静下来吧", "It'll be quiet someday"),
    ("少し寝られるようになりました", "终于能稍微睡着了", "I became able to sleep a little"),
    ("親", "父母", "parent(s)"),
    ("子供の時、親に何をさせられましたか？", "小时候被父母逼着做过什么？", "What did your parents make you do as a child?"),
    ("野菜を食べさせられました", "被逼着吃蔬菜", "I was made to eat vegetables"),
    ("私の傘、どこに行っちゃったんだろう？", "我的伞跑哪儿去了？", "Where did my umbrella go?"),
    ("ストレス解放（かいほう）できる", "能释放压力", "can release stress"),
    ("⭐️ストレス発散（はっさん）できる", "更能发泄压力（更自然）", "can let off steam (more natural)"),
    ("強い力を使うとき", "使很大力气的时候", "when you use a lot of force"),
    ("利点", "优点", "advantage"),
    ("ジムに行くのは、健康維持（けんこういじ）のためです。", "去健身房是为了保持健康。", "I go to the gym to stay healthy."),
    ("＝健康と体型（たいけい）を維持（いじ）するためです。", "也就是为了保持健康和体型。", "that is, to maintain health and body shape"),
    ("型", "型、形状（身体轮廓时常用フォルム）", "form / shape"),
    ("敬語（けいご", "敬语", "honorific language"),
    ("始めたんだって？", "听说你开始了？", "You started, I hear?"),
    ("始めたの？", "开始了吗？", "Did you start?"),
    ("始めたんでしょ？", "你开始了吧？", "You started, right?"),
    ("始めたらしいじゃん", "好像开始了嘛", "Sounds like you started"),
    ("やめちゃったんだ", "结果放弃了", "I ended up quitting"),
    ("やめちゃった", "放弃了（= やめた）", "quit (casual)"),
    ("やりすぎているから、ゲームはやるなって", "因为玩过头了，所以被说别玩游戏", "Because I overdid it, I was told not to game"),
    ("やるなって（言われた）", "被说「别做」", "was told not to do it"),
    ("やる", "做（= する）", "to do"),
    ("いっぱいできる", "能做很多", "can do a lot"),
    ("塾（じゅく）", "补习班", "cram school"),
    ("海外（かいがい）", "海外", "overseas"),
    ("言ってた", "说过", "was saying"),
    ("ハンカチ", "手帕", "handkerchief"),
    ("今一人", "现在一个人", "I'm alone now"),
    ("こんな美しい（うつくしい）女性を放って（ほう）おくなんて", "把这么漂亮的女性丢在一边", "leaving such a beautiful woman alone"),
    ("もったいないなあ", "太可惜了啊", "what a waste"),
    ("寝ようと思ったらえらい揺れた🫨", "正想睡觉就晃得很厉害", "I was about to sleep when it shook hard"),
    ("とても揺れた", "晃得很厉害", "it shook a lot"),
    ("すごく揺れた", "晃得非常厉害", "it shook hugely"),
    ("限定げんてい", "限定", "limited"),
    ("ダイレクトな表現（ひょうげん）", "直接的表达", "a direct expression"),
    ("ナンパ師", "搭讪高手", "pickup artist"),
    ("電気ポットが冷蔵庫の上から落ちそうになって、危ないので床においた。", "电热水壶快从冰箱上掉下来，太危险了所以放到地上。", "The kettle was about to fall off the fridge, so I put it on the floor."),
    ("たしか", "我记得 / 大概", "if I remember / probably"),
    ("良い休日を（お過ごし下さい）", "祝你假期愉快", "Have a nice holiday"),
    ("かわいいよ", "很可爱哦（告知新信息）", "it's cute (I'm telling you)"),
    ("BBQ場で買おうよ", "在烧烤场买吧", "let's buy it at the BBQ spot"),
    ("そっちのほうがいいよね", "那边更好吧", "that way is better, right"),
    ("君くん", "君 / くん（对男性的称呼）", "kun (address for a guy)"),
    ("冷たい", "凉的、冷淡的", "cold"),
    ("そんな感じ", "那种感觉 / 差不多那样", "something like that"),
    ("短すぎない？", "会不会太短了？", "isn't it too short?"),
    ("すぎる", "过于……", "too..."),
    ("接続", "接续", "connection / conjugation"),
    ("若すぎない？", "会不会太年轻了？", "isn't that too young?"),
    ("可愛すぎない？", "会不会太可爱了？", "isn't that too cute?"),
    ("年上（としうえ）すぎない？", "会不会年纪太大了？", "isn't that too old (for me)?"),
    ("持ってきてくれるんだよね？", "你会带来的吧？", "You'll bring it, right?"),
    ("田中くん→若い男の人、男の子「くん」", "田中くん：对年轻男性、男孩子用「くん」", "Tanaka-kun: kun is for young men / boys"),
    ("もっと漢字", "再多一些汉字", "more kanji"),
    ("半分", "一半", "half"),
    ("逃げられない（にげる）", "逃不掉", "can't run away"),
    ("町中", "城里、镇上", "in town"),
    ("遠い", "远", "far"),
    ("いっこだて", "独栋住宅", "detached house"),
    ("気になる", "在意、好奇", "to be curious / bothered"),
    ("地元", "老家、当地", "hometown / local"),
    ("どくしんの時", "单身的时候", "when I was single"),
    ("彼女いなかった時に、", "没有女朋友的时候", "when I didn't have a girlfriend"),
    ("草むら（くさむら）", "草丛", "clump of grass"),
    ("合わない", "合不来 / 不适合", "doesn't suit / doesn't get along"),
    ("着物", "和服", "kimono"),
    ("動きにくい", "不好活动", "hard to move in"),
    ("これだけだと、寒いと思ういよ", "只穿这个会冷的哦", "just this will be cold"),
    ("ドレス", "连衣裙", "dress"),
    ("ね", "呢 / 对吧", "right? / you know"),
    ("決めた", "决定了", "I've decided"),
    ("これにする", "就选这个", "I'll go with this"),
    ("テスト、⭕️すぎる", "考试，好得过头了", "the test was too perfect"),
    ("食べかけ", "吃到一半的（东西）", "half-eaten"),
    ("クラスの後、のこりを食べます", "下课后再把剩下的吃掉", "I'll eat the rest after class"),
    ("まだたくさん学ぶことがあります", "还有很多要学", "there's still a lot to learn"),
    ("決めたの？", "决定了吗？", "Have you decided?"),
    ("時間がたつ", "时间流逝", "time passes"),
    ("なんとなく", "总觉得、莫名地", "somehow / vaguely"),
    ("1 あげないことはない", "不是不给（有可能给）", "it's not that I wouldn't give it"),
    ("2 あげることはない", "没必要给", "no need to give it"),
    ("3 あげないことじゃない", "并不是不给", "it's not that I won't give it"),
    ("4 あげないことにする", "决定不给", "I've decided not to give it"),
    ("庭には二羽ニワトリがいる", "院子里有两只鸡（二羽是鸡的量词）", "There are two chickens in the yard"),
    ("パン作ったことありますか", "做过面包吗？", "Have you ever made bread?"),
    ("パンツ食ったことありますか", "吃过内裤吗？（谐音玩笑）", "Have you ever eaten pants? (pun)"),
    ("あのー、先生。先生が「この本は面白いから読んだ方がいい」と仰っていた本を貸していただけないでしょうか。", "那个，老师。您说过「这本书很有趣，最好读一读」的那本，能借我吗？", "Um, teacher, could I borrow the book you said was worth reading?"),
    ("＝先生が「この本は面白いから読んだ方がいい」と言った本を貸して下さい。", "请把老师说「这本书有趣，最好读」的那本借给我。（普通说法）", "Please lend me the book the teacher said was interesting."),
    ("渡すように", "转交给……", "so that it gets handed over"),
    ("おっしゃっていた", "您说过（尊敬语）", "you said (honorific)"),
    ("白人", "白人", "white person"),
    ("おばあさんにとって難しい。", "对奶奶来说很难。", "It's hard for grandma."),
    ("並ぶ", "排队", "to line up"),
    ("その様に", "像那样", "like that"),
    ("千葉やばいよね", "千叶好夸张啊", "Chiba is crazy, huh"),
    ("めちゃくちゃ降っとる", "雨下得离谱", "it's pouring"),
    ("お気をつけください", "请小心", "please take care"),
    ("マジでやべぇな", "真的太糟了", "this is seriously bad"),
    ("蘇我駅ヤバすぎ", "苏我站也太离谱了", "Soga station is too much"),
    ("日本に住んでるだけで楽しい", "光是住在日本就很开心", "just living in Japan is fun"),
    ("いろんな文", "各种各样的句子", "all kinds of sentences"),
    ("5ヶ月目", "第五个月", "the fifth month"),
    ("へ→に", "「へ」改成「に」", "change へ to に"),
    ("帰ってきた", "回来了", "came back"),
    ("いつも面白い話があるね", "总是有有趣的故事呢", "you always have interesting stories"),
    ("彼女はすぐに私がどこ出身か分かりました", "她马上就知道我是哪里人", "She immediately knew where I was from"),
    ("旅行に行こうとしている", "正打算去旅行", "about to go on a trip"),
    ("今週末に旅行に行くと言っていました", "说了这周末要去旅行", "they said they're traveling this weekend"),
    ("彼に会いに行く", "去见他", "go to see him"),
    ("いつか彼女とか将来の奥さんと一緒に行きたい！", "以后想和女朋友或未来的妻子一起去！", "Someday I want to go with a girlfriend or future wife"),
    ("元カノとヨーロッパに行こうと思っていたけど、治安がよくないのでやめました", "本来想和前女友去欧洲，因为治安不好就放弃了", "I was going to Europe with my ex, but dropped it because it wasn't safe"),
    ("高校の修学旅行", "高中的修学旅行", "high-school trip"),
    ("おっしゃっていた本を貸していただけないでしょうか？", "您说过的那本书能借给我吗？", "Could I borrow the book you mentioned?"),
    ("前よりも成長（せいちょう）しました", "比以前成长了", "I've grown more than before"),
    ("前よりわかるようになりました", "比以前更能听懂了", "I understand more than before"),
    ("まじで頭がいい！", "真的好聪明！", "you're seriously smart!"),
    ("冷蔵庫（れいぞうこ）", "冰箱", "refrigerator"),
    ("いい一日", "美好的一天", "a good day"),
    ("雨が降った", "下雨了", "it rained"),
    ("雨が降ってきた", "雨下起来了", "it started raining"),
    ("先生に習いはじめて", "开始跟老师学之后", "since I started learning from the teacher"),
    ("→優勝のあと言います", "比赛赢了之后会说", "said after winning"),
    ("暑くてどこも行きたくないから", "因为太热哪里都不想去", "it's so hot I don't want to go anywhere"),
    ("30分から1時間ぐらい", "大概三十分钟到一小时", "about 30 minutes to an hour"),
    ("ちゃんと覚えた", "好好记住了", "I memorized it properly"),
    ("ハンカチをプレゼントしようと思っているんですけど", "我在想送手帕当礼物", "I'm thinking of giving a handkerchief"),
    ("ジムに行こうと思う", "打算去健身房", "I'm thinking of going to the gym"),
    ("おすしを食べようと思う", "打算吃寿司", "I'm thinking of eating sushi"),
    ("日動火災・熊本県共同ビル", "日动火灾・熊本县共同大楼", "Nichido Fire / Kumamoto Prefecture building"),
    ("前にくまもとにオンラインできふをしました。", "之前在网上给熊本捐过款。", "I donated to Kumamoto online before."),
    ("そして、銀座のくまもとのお店にも行って、きふをしたかったけど、たくさん人が並んでたので、他のところに行きました。", "后来也去了银座的熊本店想捐款，人太多就去别的地方了。", "I went to the Kumamoto shop in Ginza to donate, but the line was long so I left."),
    ("（ならぶ）", "排队", "to line up"),
    ("健康（けんこう）", "健康", "health"),
    ("通知（つうち）", "通知", "notification"),
    ("アプリやルールはいつもかしこい（賢い）ひとがつくるので、かしこくないひとはそのシステムに使われてしまいます。", "App 和规则总是聪明人做的，不聪明的人就会被系统牵着走。", "Apps and rules are made by smart people, so less smart people get used by the system."),
    ("日本の男の人は髪（かみ）とか外見（がいけん）に気を遣うけど", "日本男生会在意头发和外表，但是", "Japanese men care about hair and looks, but"),
    ("[にほんのおとこのひとは かみとか がいけん に きをつかうけど]", "日本男生会在意头发和外表，但是（读音）", "reading of the previous sentence"),
    ("中国人の男の人は気にしない。 [ちゅうごくじんのおとこのひとはきにしない]", "中国男生不太在意。", "Chinese men don't really care."),
    ("伝統的（でんとうてき）な漢字", "传统的汉字", "traditional kanji"),
    ("教科書（きょうかしょ）", "教科书", "textbook"),
    ("同じ気持ち [おなじきもち]", "同样的心情", "the same feeling"),
    ("同じ思い [おなじおもい]", "同样的想法", "the same thought"),
    ("さんずい（三点水）", "三点水旁", "the water radical"),
    ("苗字（みょうじ）", "姓", "family name"),
    ("親切 [しんせつ]", "亲切、热心", "kind"),
    ("決められる", "能决定 / 被决定", "can decide / be decided"),
    ("ケイ", "ケイ（音读）", "Kei (on-yomi)"),
    ("私のクラスメイトは、若いので私と話が合いません。私は、テクノロジーとか政治的な話をしたいのですが、私のクラスメイトとはそういう話ができません。", "我的同学比较年轻，聊不到一起。我想聊科技或政治，但跟同学聊不了这些。", "My classmates are young so we don't click. I want to talk tech or politics, but I can't with them."),
    ("[わたしのくらすめいとは、わかいのでわたしとはなしがあいません。わたしは、テクノロジーとかせいじてきなはなしをしたいのですが、わたしのクラスメイトとはそういうはなしができません。", "上一句的读音", "reading of the previous sentence"),
    ("まだ食べてない", "还没吃", "haven't eaten yet"),
    ("見てない", "没看", "haven't watched / seen"),
    ("美容師（びようし）", "美容师、发型师", "hairdresser"),
    ("やっと休める", "终于能休息了", "I can finally rest"),
    ("１、うどんよりおそばがいいわ", "比起乌冬我更喜欢荞麦面（女性语气的「わ」）", "I prefer soba to udon (feminine wa)"),
    ("２、ねえ、知ってる？ 田中さん、彼と別れたんだって。", "喂，你知道吗？听说田中和他分手了。", "Hey, did you know? Tanaka broke up with him."),
    ("話題", "话题", "topic"),
    ("喋れる", "能聊、能说", "can talk / chat"),
    ("どんな時に使いますか？", "什么时候用？", "When do you use it?"),
    ("いつ言う？", "什么时候说？", "When do you say it?"),
    ("いつ使う？", "什么时候用？", "When do you use it?"),
    ("例文(れいぶん）", "例句", "example sentence"),
    ("よく保存している", "保存得很好", "well preserved"),
    ("マリアさんを病院へ連れていってあげました", "我带玛丽亚去了医院", "I took Maria to the hospital"),
    ("サンスクリーン", "防晒霜（= 日烧け止め）", "sunscreen"),
    ("ありがとう！❤️⬆️", "谢谢！", "thank you!"),
    ("室内", "室内", "indoors"),
    ("黒龍江", "黑龙江", "Heilongjiang"),
    ("いつまで", "到什么时候", "until when"),
    ("ちゃんと相手の名前が書いてあるか、確認して", "确认一下对方的名字有没有写对", "check that the other person's name is written correctly"),
    ("がっこうのあと、スーパーにいって、おべんとうをかいました。", "放学后去超市买了便当。", "After school I went to the supermarket and bought a bento."),
    ("やさいのおそうざい", "蔬菜小菜", "vegetable side dish"),
    ("文を作りましょう！", "来造句吧！", "Let's make sentences!"),
    ("つうがく（通学）", "上学往返", "commuting to school"),
    ("つうきん（通勤）", "上班往返", "commuting to work"),
    ("おくれて来るんだから！", "你可是会迟到的啊！", "you're going to be late!"),
    ("雨が降ってきて、もっとはげしく踊りました。", "雨下起来了，我们跳得更起劲。", "It started raining and we danced even harder."),
    ("他（ほか）の人が、傘をさしてくれました。やさしかったです。", "别人给我打了伞。好温柔。", "Someone held an umbrella for me. It was kind."),
    ("北京よりも東京の方がもっと暑い。", "东京比北京更热。", "Tokyo is hotter than Beijing."),
    ("そう思う。", "我也这么想。", "I think so."),
    ("地理", "地理", "geography"),
    ("かんそうしてる", "很干燥", "it's dry"),
    ("北京の方が乾燥してる", "北京更干燥", "Beijing is drier"),
    ("東京の方が好き", "更喜欢东京", "I like Tokyo more"),
    ("３ヶ月だけ暑い", "只热三个月", "it's only hot for three months"),
    ("湿気（しっけ）がある / じめじめしてる", "有湿气 / 潮乎乎的", "it's humid / clammy"),
    ("たしかに！", "确实！", "that's true!"),
    ("きゅうしょうがつ", "旧正月", "Lunar New Year"),
    ("先生が私の文を直してくれた", "老师帮我改了句子", "the teacher corrected my sentence"),
    ("今日は、このような単語や文を勉強できて、嬉しいです。", "今天能学到这些单词和句子，好开心。", "I'm glad I could study these words and sentences today."),
    ("またのちほど", "稍后再联系", "I'll get back to you later"),
    ("お世話になっております", "一直承蒙您关照", "thank you for your continued support"),
    ("終わり次第（しだい", "一结束就……", "as soon as it finishes"),
    ("トウコウと申しうます", "我叫登浩（自我介绍）", "My name is Toukou"),
    ("ゆみさんは", "由美在吗 / 请问由美", "Is Yumi there?"),
    ("依頼の", "拜托、请求时用的说法", "used when making a request"),
    ("お電話がかかるのを待つ", "等电话打进来", "wait for the phone to ring"),
    ("原形：する", "原形：する", "dictionary form: suru"),
    ("普通礼貌形：しました", "普通礼貌形：しました", "polite form: shimashita"),
    ("谦让语：いたしました", "谦让语：いたしました", "humble form: itashimashita"),
    ("会社には戻らず（もどらず", "不回公司", "without going back to the office"),
    ("とのことです", "（转达）说是……", "I was told that..."),
    ("そうです", "是这样 / 听说是这样", "that's right / I hear that's so"),
    ("お入れしますか", "要帮您倒上吗？", "Shall I pour it for you?"),
    # en-only → add Chinese
    ("朝型", "早起型、早睡早起的人", "morning person"),
    ("夜型", "夜猫子", "night person"),
    ("ベトナム", "越南", "Vietnam"),
    ("くそ！", "靠！", "shit"),
    ("先進国（せんしんこく）", "发达国家", "developed country"),
    ("収入（しゅうにゅう）", "收入", "income"),
    ("公积金", "公积金（住房，约 12%）", "housing fund, about 12%"),
    ("助け合った", "互相帮助了", "helped each other"),
    ("旦那だんな", "丈夫", "husband"),
    ("犬にチューされた", "被狗亲了一口", "the dog kissed me"),
    ("衝撃的 しょうげきてき", "令人震惊", "shocking"),
    ("かしこい", "聪明", "smart"),
    ("忘れずに（", "别忘了", "don't forget"),
    ("びっくり！", "吓到了！吃惊！", "I'm shocked / surprised"),
    ("仲悪い", "关系不好", "don't get along"),
    ("尊敬する！", "好尊敬！", "I respect that"),
    ("ツイてないな〜", "好倒霉啊", "unlucky"),
    ("ツイてる", "走运", "lucky"),
    ("ダラダラする", "懒散地耗着", "being lazy / loafing"),
    ("面白いと思えない", "觉得没那么有趣（语气较软）", "I can't really find it interesting"),
    ("面白いと思わない", "不觉得有趣", "I don't think it's interesting"),
    ("話(はなし)", "集、一话", "episode"),
    ("遅い", "慢、晚", "slow / late"),
    ("ペラペラ", "说得很流利", "fluent"),
    ("インプット", "输入", "input"),
    ("アウトプット", "输出", "output"),
    ("めっちゃ使える！", "超好用！", "super useful"),
    ("それでも", "即便如此", "even so / still"),
    ("おたがい", "彼此、互相", "each other"),
    ("ほとんど", "几乎、大部分", "almost / most"),
    ("何回も行っている", "去过很多次", "I've been there many times"),
    ("怪我が治っていない", "伤还没好", "the injury hasn't healed"),
    ("直す", "修理、改正", "to fix / correct"),
    ("治す", "治好（病、伤）", "to heal / cure"),
    ("いつも通り（どおり）", "和平时一样", "as usual"),
    ("知れる", "能了解到", "to be able to know"),
    ("国の歴史を知れる", "能了解这个国家的历史", "can learn the country's history"),
    ("多すぎた", "太多了", "there were too many"),
    ("戦争", "战争", "war"),
    ("受けたことがある", "曾经考过 / 接受过", "I have taken (a test, etc.)"),
    ("じゃないか", "不是吗 / 我们做到了", "didn't we? / we did it"),
    ("欲しがっているもの", "对方想要的东西", "the thing they want"),
    ("きっと", "一定、肯定", "surely / probably"),
    ("ご遠慮下さい", "请不要这样做", "please refrain"),
    ("彼女は結婚したがっています", "她看起来很想结婚", "she wants to get married"),
    ("したがっている", "显得想……", "looks like they want to"),
    ("したがる", "显得想做", "to appear to want to"),
    ("落ちる、落ちた", "掉下去、掉了", "to fall / fell"),
    ("もし良かったら、もう少し話を聞かせていただけませんか？", "方便的话，能再听您讲一点吗？", "If it's OK, could you tell me a bit more?"),
    ("いっぱい", "很多", "a lot"),
    ("ビビった", "吓到了（很随便）", "I was startled (casual)"),
    ("無事で良かった", "没事就好", "I'm glad you're OK"),
    ("良い（よい）休日（きゅうじつ)を", "祝你假期愉快", "Have a nice holiday"),
    ("かわいいね", "好可爱呢", "it's cute, isn't it"),
    ("だよね", "对吧", "right?"),
    ("そっち", "那边（随便说法，正式是そちら）", "there (casual)"),
    ("汗(あせ)をかく", "出汗", "to sweat"),
    ("マッチングアプリ", "交友软件", "dating app"),
    ("でしょ？", "对吧？（语气较强）", "right? (stronger)"),
    ("ない系", "否定形式", "negative form"),
    ("スマホをいじった", "玩手机了", "used my phone"),
    ("二度寝（にどね）した", "睡回笼觉了", "went back to sleep"),
    ("たからくじ", "彩票", "lottery"),
    ("あたらない", "中不了（奖）", "can't win"),
    ("買ったことがない", "从没买过", "I've never bought one"),
    ("旅行したことがない", "从没旅行过", "I've never traveled"),
    ("V \\+ ことがない", "从没做过……", "have never done..."),
    ("停（と）める", "停（车）", "to park"),
    ("ございます", "有（礼貌）", "there is (polite)"),
    ("ご近所", "附近、街坊", "the neighborhood"),
    ("ご近所の方", "邻居", "neighbors"),
    ("迷惑（めいわく）", "添麻烦", "trouble / nuisance"),
    ("うごきにくい", "不好活动", "hard to move"),
    ("伝えておきますね　つたえておく", "我会先转告的", "I'll let them know"),
    ("知識(ちしき)", "知识", "knowledge"),
    ("雨がやんだ　やむ", "雨停了", "the rain stopped"),
    ("やったー！🙌", "太好了！", "yeah!"),
    ("場合(ばあい)による", "看情况", "it depends"),
    ("どのぐらい運動しますか？", "你运动多久？", "How long do you exercise?"),
    ("ちゃんと", "好好地（正式可说きちんと）", "properly"),
    ("し　ようと思う", "打算做……", "I'm thinking of doing..."),
    ("おしゃれ", "时髦、讲究穿搭", "stylish"),
    ("ほそい", "瘦、细", "thin / skinny"),
    ("リボン", "蝴蝶结、缎带", "ribbon"),
    ("こうゆうの", "像这样的", "something like this"),
    ("人気（にんき）", "受欢迎", "popular"),
    ("かわいすぎる", "可爱过头了", "too cute"),
    ("ならんでた", "当时在排队", "was lining up"),
    ("なんにちか前", "几天前", "several days ago"),
    ("おわたかな", "结束了吧（我在想）", "I wonder if it's over"),
    ("いいんじゃない", "挺好的吧", "that's fine, I think"),
    ("何を言いたかったんだっけ？", "我刚才想说什么来着？", "what was I going to say?"),
    ("そんな感じ(かんじ)", "那种感觉", "like that"),
    ("いい感じ", "感觉不错", "a good vibe"),
    ("いやな感じ", "讨厌的感觉", "bad vibes"),
    ("状況 [じょうきょう]", "状况", "situation"),
    ("決められる [きめられる]", "能决定", "can decide"),
    ("ヘえー、そうなのー", "哎，是这样啊", "oh, I see"),
    ("ヘえー、そうなるのー", "哎，会变成那样啊", "oh, it turns out that way"),
    ("ヘえー、そうしたのー", "哎，你那么做了啊", "oh, you did that"),
    ("むずかしい", "很难说、很难", "hard to say / difficult"),
    ("言いたかったです", "我刚才想说的是", "I wanted to say"),
    ("知識（ちしき）", "知识", "knowledge"),
    ("伝統（でんとう）", "传统", "tradition"),
    ("わすれる", "忘记", "to forget"),
    ("かしこまりました", "好的，明白了（非常礼貌）", "certainly"),
    ("あたまいい！", "好聪明！", "smart!"),
    ("できれば", "如果可以的话", "if possible"),
    ("早く届けたいんですが", "想早点送到", "I'd like to deliver it soon"),
    ("ちるする", "放松一下（chill）", "to chill"),
    ("仲良い(なかいい)", "关系好", "get along well"),
    ("仲良くない（なかよくない）", "关系不好", "don't get along"),
    ("たぶん", "大概", "maybe"),
    ("やめた", "不做了、戒了", "quit / stopped"),
    ("えらい！", "真了不起！辛苦了", "good job / you worked hard"),
    ("すわない", "不抽烟", "don't smoke"),
    ("しらべました", "查过了", "I looked it up"),
    ("情報（じょうほう）", "信息", "information"),
    ("おてつだい", "帮忙", "help"),
    ("しょるい", "文件", "document"),
    ("一枚(いちまい)ずつ", "一张一张地", "one by one (flat objects)"),
    ("ふうとう", "信封", "envelope"),
    ("やりにくい", "不好做、难下手", "hard to do"),
    ("マジで", "真的吗 / 认真的", "seriously / really"),
    ("この場所はめっちゃばえる", "这里超上镜", "this spot is perfect for photos"),
    ("おみせ（お店）", "店", "shop"),
    ("へや（部屋）", "房间", "room"),
    ("おしゃれ な", "时髦的", "stylish"),
    ("めっちゃ", "非常（年轻人说法，≈ ちょう）", "very (casual)"),
    ("かわいー", "好可爱", "cute"),
    ("わんちゃん", "小狗狗", "doggie"),
    ("おしょうがつ", "正月、新年", "New Year"),
    ("なおす", "改正、修理", "to correct / fix"),
    ("れんしゅう 練習", "练习", "practice"),
    ("嬉しい！", "好开心！", "I'm happy"),
    ("助け合う", "互相帮助", "help each other"),
]

root = Path(__file__).resolve().parents[1]
out = root / "app/data/lesson-review-glosses.json"
data = {}
for jp, cn, en in PAIRS:
    data[jp] = {"cn": cn, "en": en}
out.parent.mkdir(parents=True, exist_ok=True)
out.write_text(json.dumps(data, ensure_ascii=False, indent="\t") + "\n", encoding="utf-8")
print(f"wrote {out} ({len(data)} entries)")
