def q(n, ans, trans, trans_en, opts, opts_en, point, point_en, link, extra=None):
    item = {
        "n": n,
        "ans": ans,
        "trans": trans,
        "trans_en": trans_en,
        "option_translations": opts,
        "option_translations_en": opts_en,
        "why": ["", "", "", ""],
        "why_en": ["", "", "", ""],
        "point": point,
        "point_en": point_en,
        "link": link,
    }
    if extra:
        item.update(extra)
    return item


WEEK_DATA = {
    "w2": {
        "mondai1": [
            q(1, 2, "围巾织到一半就停下了。", "I started knitting a muffler but gave up halfway.", ["完全织完", "做到一半", "彻底织完", "坚持织完"], ["finish knitting", "do halfway", "knit through", "knit to the end"], "「Vかけ」表示做到中途。", "Vかけ = start but not finish.", "#/day/2-2/p0"),
            q(2, 4, "那项运动原本是作为护身而想出来的。", "The sport was originally devised for self-defense.", ["和…一起", "随着", "对…来说", "作为"], ["together with", "as … changes", "for / to", "as / in the capacity of"], "「Nとして」表示资格、立场。", "として = as / in the role of.", "#/day/2-5/p3"),
            q(3, 4, "请趁汤还没凉赶紧用。", "Please eat the soup while it is still hot.", ["凉（词干）", "凉（词典形）", "凉了之后", "还没凉"], ["cool (stem)", "cool (dict.)", "after it has cooled", "before it cools"], "「Vないうちに」表示趁还没发生。", "Vないうちに = while it still hasn't happened.", "#/day/2-3/p0"),
            q(4, 3, "他烦恼到极点，最终还是说出了真相。", "After worrying himself sick, he finally told the truth.", ["做到一半", "坚持到底", "…到极点／非常", "偏偏"], ["halfway", "to the end", "to the utmost", "of all times"], "「悩みぬく」＝烦恼到极点。", "Vぬく = do it all the way / thoroughly.", "#/day/2-2/p3"),
            q(5, 1, "只要学生没有干劲，老师再努力也进步不了。", "As long as the students aren't motivated, no amount of teaching will help.", ["只要…就", "越…越", "大约", "和…一起"], ["as long as", "the more", "about", "together with"], "「Vないかぎり」＝只要不…。", "Vないかぎり = so long as … not.", "#/day/2-3/p2"),
            q(6, 3, "偏偏没复习的地方会考到。", "Of all things, the parts I didn't study come up on the test.", ["对…来说", "从…立场看", "偏偏／只有这时", "伴随着"], ["for", "from the viewpoint of", "of all times / only then", "along with"], "「にかぎって」表示偏偏是这种情况。", "にかぎって = of all times / only then.", "#/day/2-3/p3"),
            q(7, 3, "旧的还没用完，先用完再开新的吧。", "There's still some of the old one left, so let's finish it before opening a new one.", ["用到一半", "用到极点", "用完", "坚持用"], ["use halfway", "use thoroughly", "use up", "use to the end"], "「使いきる」＝用光。", "Vきる = do completely / use up.", "#/day/2-2/p1"),
            q(8, 4, "天刚亮他们就开始干活。", "They start work at the very moment day breaks.", ["只要", "和…同时", "随着", "在…前后"], ["as long as", "together with", "as … changes", "just as / around the time"], "「VるかVないかのうちに」表示几乎同时。", "VるかVないかのうちに = hardly has A happened when B.", "#/day/2-3/p1"),
            q(9, 2, "仅限小学生及以下儿童赠送礼物。", "A present is given only to children in elementary school or younger.", ["只要", "仅限于", "作为", "对…来说"], ["as long as", "limited to", "as", "for"], "「Nにかぎり」＝仅限于。", "にかぎり = limited to.", "#/day/2-3/p3"),
            q(10, 3, "正是因为考虑你的健康，才不让你喝酒。", "It's precisely because I care about your health that I won't let you drink.", ["越…越", "大约", "正是因为", "偏偏"], ["the more", "about", "precisely because", "of all times"], "「からこそ」强调原因。", "からこそ stresses the reason.", "#/day/2-4/p1"),
            q(11, 3, "只要身体好，生活总能过下去。", "As long as I'm healthy I can get by somehow.", ["越…越", "只要", "只要…就（さえ）", "作为"], ["the more", "as long as", "if only", "as"], "「Nさえ〜ば」表示最低条件。", "さえ〜ば = if only that condition is met.", "#/day/2-4/p0"),
            q(12, 1, "免费体验课仅限一次。", "The free trial lesson is limited to one session.", ["仅限", "大约", "甚至", "作为"], ["limited to", "about", "even", "as"], "「1回かぎり」＝只有这一次。", "かぎり after a number = only that many.", "#/day/2-3/p3"),
            q(13, 3, "那么好的人居然做坏事，不可能。", "There's no way such a good person would do something bad.", ["可能", "可能（书面）", "不可能", "非词"], ["possible", "possible (formal)", "impossible", "not a word"], "「ありえない」＝不可能。", "ありえない = cannot be.", "#/day/2-2/p2"),
            q(14, 2, "请按照这份一周菜单做菜。", "Please cook according to this week's menu.", ["随着", "按照", "伴随着", "和…一起"], ["as … changes", "in accordance with", "along with", "together with"], "「Nにしたがって」表示按照指示。", "にしたがって = following / according to.", "#/day/2-6/p3"),
            q(15, 1, "明天首相访问本市，随之这条路预计会堵。", "The prime minister visits tomorrow, so this road is expected to be congested.", ["伴随着", "随着（渐变）", "按照", "一起"], ["accompanying", "as it gradually changes", "according to", "together"], "「それにともなって」表示随之发生。", "にともなって = accompanying that change.", "#/day/2-6/p1"),
        ],
        "mondai2": [
            q(16, 1, "汉字、听解、读解都还行，语法只要肯做应该就没问题。", "Kanji, listening and reading are OK, so grammar should be fine if you just do it.", ["如果做", "语法", "就好", "只要"], ["if you do it", "grammar", "will be fine", "if only"], "「さえ〜ば」＝只要。", "さえ〜ば = if only.", "#/day/2-4/p0", {"order": "2→4→1→3"}),
            q(17, 2, "对只能在休息日旅行的人来说，这套收费很残酷。", "For people who can only travel on holidays, this pricing is harsh.", ["不能旅行", "对那个人来说", "只有休息日", "痛苦。"], ["cannot travel", "from that person's view", "only on holidays", "painful"], "「Nにしたら」站在对方立场。", "にしたら = from that person's standpoint.", "#/day/2-5/p0", {"order": "3→1→2→4"}),
            q(18, 3, "派对准备都好了，就只等客人了。", "Party prep is done; all that's left is to wait for the guests.", ["只差", "剩下的是", "等待", "客人"], ["just about to / only left", "the rest is", "wait", "the guests"], "「待つばかり」＝只等着。", "Vるばかり = nothing left but to.", "#/day/2-4/p3", {"order": "2→4→3→1"}),
            q(19, 4, "这几年随着景气恶化，就业率大幅下降。", "Employment has fallen sharply along with the worsening economy in recent years.", ["景气的", "几年的", "伴随着", "恶化"], ["of the economy", "of recent years", "along with", "worsening"], "「Nにともない」书面，表示伴随。", "にともない = along with (formal).", "#/day/2-6/p1", {"order": "2→1→4→3"}),
            q(20, 4, "随着手机普及，公用电话不再被使用。", "As cell phones spread, public phones stopped being used.", ["公用电话", "做", "普及", "随着"], ["public phones", "do", "spread", "as"], "「につれて」表示一边变化一边发生。", "につれて = as X changes, Y happens.", "#/day/2-6/p2", {"order": "3→2→4→1"}),
        ],
        "mondai3": [
            q(21, 4, "尽管各国努力，情况却毫无改善。", "Despite various countries' efforts, the situation hasn't improved at all.", ["只要有就", "有成效", "只要", "毫无成效"], ["if only there is", "worth the effort", "as long as", "to no avail"], "「かいもなく」＝白费。", "かいもなく = without the effort paying off.", "#/day/2-1/p1"),
            q(22, 1, "状况一个劲儿地恶化。", "The situation just keeps getting worse.", ["一个劲儿地…", "也不是不…", "不该…", "不能（光）…"], ["only / increasingly", "not that it doesn't", "must not", "can't afford to"], "「するばかりだ」＝一个劲儿地变糟。", "ばかりだ = keep doing / only getting worse.", "#/day/2-4/p3"),
            q(23, 4, "据说南极冰全部融化也是有可能的。", "They say it is possible all the Antarctic ice will melt.", ["毫无意义", "不可能", "只限于有", "有可能"], ["pointless", "impossible", "limited to existing", "possible"], "「ありうる」＝有可能。", "ありうる = can happen.", "#/day/2-2/p2"),
            q(24, 2, "甚至用混凝土保护海岸来阻止海面上升。", "Some places even protect the coast with concrete to hold it back.", ["只要保护", "甚至保护到这个地步", "正因保护了", "保护有成效"], ["if only we protect", "go so far as to protect", "precisely because we protected", "worth protecting"], "「てまで」表示甚至做到那种程度。", "てまで = going so far as to.", "#/day/2-1/p3"),
            q(25, 1, "只要我们活着，就必须保护环境。", "For as long as we live we must protect the environment.", ["只要…期间", "只是", "即使作为", "趁…的时候"], ["as long as", "just", "even as", "while"], "「生きている限り」＝只要活着。", "Vている限り = so long as that state continues.", "#/day/2-3/p2"),
        ],
    },
    "w3": {
        "mondai1": [
            q(1, 2, "那人来上课只有一次。", "That person came to class only once.", ["哪里谈得上", "仅那一次", "满是", "按照"], ["far from", "only that once", "full of", "as"], "「一度きり」＝仅此一次。", "きり = only that and nothing more.", "#/day/3-5/p1"),
            q(2, 4, "因为太高兴，忍不住叫了出来。", "I was so happy I couldn't help crying out.", ["うれしい词干", "い形容词原形", "て形", "うれしさ＋のあまり"], ["stem", "plain i-adj", "te-form", "noun + のあまり"], "「Nのあまり」表示过度。", "Nのあまり = so much that.", "#/day/3-1/p3"),
            q(3, 3, "遗憾的是，养的兔子死了。", "To my regret, the rabbit I was keeping died.", ["悲しみ（接续不对）", "かわいそう（接续不对）", "残念なことに", "さびしさ（接续不对）"], ["wrong form", "wrong form", "it's regrettable that", "wrong form"], "「なことに」接な形容词。", "なことに follows na-adjectives.", "#/day/3-1/p2"),
            q(4, 4, "搬了很多次家，家具已经伤痕累累。", "We've moved so often the furniture is covered in scratches.", ["仅那次", "哪里谈得上", "过度", "满是"], ["only that", "far from", "so much that", "covered in"], "「傷だらけ」＝满是伤。", "だらけ = covered with (negative).", "#/day/3-5/p0"),
            q(5, 3, "虽然按医生说的做，病却总不好。", "I'm doing as the doctor told me, but the illness just won't go away.", ["说（主动）", "指示了（缺に）", "被吩咐的那样", "指示（名词）"], ["say (active)", "instructed (needs に)", "as I was told", "instruction (noun)"], "「言われたとおり」＝按照被告知的。", "Vられたとおり = as one was told.", "#/day/3-1/p0"),
            q(6, 4, "他让我们干等一个小时，到头来又说今天的商量要取消。", "After making us wait an hour, he ended up saying today's meeting was off.", ["就那样", "一方面", "另一方面", "结果／到头来"], ["since then", "on one hand", "on the other", "in the end (after trouble)"], "「あげく」表示折腾之后的结果。", "あげく = after all that (usually bad).", "#/day/3-3/p1"),
            q(7, 2, "停业是考虑再三之后的结论。", "Closing the shop is the conclusion we reached after much thought.", ["按照的", "…之后的", "相反", "过度的"], ["as per", "after / in the end", "contrary", "excessive"], "「Vた末」＝经过之后的结果。", "Vた末 = after doing that to the end.", "#/day/3-3/p2"),
            q(8, 3, "她吓得连动都不能动。", "She was so terrified she couldn't even move.", ["令人…的是", "与…相反", "过度以至于", "…的结果"], ["it's … that", "contrary to", "so much that", "after"], "「恐怖のあまり」。", "Nのあまり = so much that.", "#/day/3-1/p3"),
            q(9, 1, "非常抱歉，把借来的书弄脏了。", "I'm terribly sorry — I soiled the book I borrowed.", ["令人…的是", "时候", "哪里谈得上", "最后"], ["it's … that", "occasion", "far from", "in the end"], "「申し訳ないことに」。", "ことに comments on the whole situation.", "#/day/3-1/p2"),
            q(10, 1, "身子发飘，量了体温一看，居然39度。", "I felt unsteady, and when I took my temperature it was 39°.", ["一看／结果发现", "刚一…就", "到头来", "哪里谈得上"], ["when I did, I found", "the moment", "after all that", "far from"], "「Vたところ」表示做了之后的发现。", "Vたところ = when I did, I found.", "#/day/3-4/p1"),
            q(11, 1, "书借给谁以后就一直没还回来。", "I lent the book to someone and haven't gotten it back since.", ["就那样以后", "刚一…", "令人…的是", "一方面"], ["ever since then", "the moment", "it's … that", "on one hand"], "「Vたきり」＝那之后再没…。", "Vたきり = since then, nothing more.", "#/day/3-5/p1"),
            q(12, 1, "与居民意愿相反，公寓还是建起来了。", "The condominium was built against the residents' wishes.", ["与…相反", "另一方面", "另一方面", "别说"], ["contrary to", "on the other hand", "meanwhile", "far from"], "「Nに反して」。", "に反して = contrary to.", "#/day/3-6/p0"),
            q(13, 4, "这几年城市开发，这一带的树林一个劲儿地减少。", "Urban development in recent years has only made the woods around here disappear.", ["不可能", "不能那样做", "到头来", "一个劲儿地"], ["no way", "cannot very well", "after all that", "keep / only becoming more"], "「なくなる一方だ」＝一个劲儿地消失。", "一方だ = keep going in that direction.", "#/day/3-6/p3"),
            q(14, 2, "这么贵重的东西我不能收。", "I really can't accept such an expensive gift.", ["いけない（禁止）", "いきません（不能那样）", "ありません", "できません"], ["must not", "cannot very well", "is not", "cannot"], "「わけにはいきません」＝情理上不能。", "わけにはいかない = can't very well do that.", "#/day/3-2/p3"),
            q(15, 4, "因故暂时请假，但并不是要辞职。", "I'll take some time off, but that doesn't mean I'm quitting.", ["一个劲儿", "就是这么回事", "哪里谈得上辞职", "并不是辞职"], ["keep doing", "it follows that", "far from quitting", "it doesn't mean I quit"], "「わけではありません」否定那种理解。", "わけではない = it doesn't mean that.", "#/day/3-2/p1"),
        ],
        "mondai2": [
            q(16, 1, "我家孩子刚从学校回来，转眼又去玩了。", "My kid had no sooner come home from school than they ran off to play.", ["一…就觉得", "回来", "一想", "来了吗"], ["thought", "returned", "when I thought", "had come?"], "「Vたかと思ったら」表示紧接着发生。", "Vたかと思ったら = no sooner had A than B.", "#/day/3-3/p3", {"order": "2→4→1→3"}),
            q(17, 4, "那边是早上9点？这边是傍晚4点，所以时差是7小时吧。", "It's 9 a.m. there and 4 p.m. here, so that means a seven-hour time difference.", ["7小时", "时差是", "道理／也就是", "变成"], ["7 hours", "the time difference is", "it follows that", "become"], "「わけですね」确认推论。", "わけだ = that figures / so that means.", "#/day/3-2/p0", {"order": "2→1→4→3"}),
            q(18, 3, "明明是夏天，别说热了，冷得还穿着毛衣。", "It's summer, but far from being hot I'm wearing a sweater because it's cold.", ["穿着", "冷得", "毛衣", "别说"], ["wearing", "so cold that", "a sweater", "far from"], "「どころか」表示岂止如此，情况相反。", "どころか = far from it / on the contrary.", "#/day/3-4/p3", {"order": "4→2→3→1"}),
            q(19, 2, "今早地震弄得盘子都碎了，哪里还顾得上吃饭。", "The earthquake smashed dishes this morning — I was in no state to eat.", ["盘子碎了什么的", "吃饭", "哪里谈得上", "做了"], ["plates breaking and so on", "a meal", "in no state to", "doing"], "「どころではなかった」。", "どころではない = in no condition to.", "#/day/3-4/p2", {"order": "1→4→3→2"}),
            q(20, 1, "虽然按人家告诉的路去了，要找的房子却没找到。", "I went the way I was told, but still couldn't find the house.", ["按照", "得到", "告诉", "去了"], ["as", "received", "was told", "went"], "「とおりに」＝按照那样。", "とおりに = exactly as.", "#/day/3-1/p0", {"order": "3→2→1→4"}),
        ],
        "mondai3": [
            q(21, 2, "检查了一下，说是没什么异常。", "When I had it checked, they said there was nothing unusual.", ["一边检查", "检查之后发现", "检查到头来", "别说检查"], ["while examining", "when I had it checked", "after endless tests", "far from examining"], "「Vたところ」＝做了之后的结果。", "Vたところ = when I did, I found.", "#/day/3-4/p1"),
            q(22, 1, "刚说没异常，反而更担心了。", "The moment they said nothing was wrong I started worrying even more.", ["刚一…就", "就那样以后", "到头来", "另一方面"], ["the instant", "ever since", "after all that", "on the other hand"], "「Vたとたん」＝刚一…马上。", "Vたとたん = the moment that happened.", "#/day/3-3/p0"),
            q(23, 2, "这么疼却说哪儿都没病，不可能。", "There's no way nothing is wrong when it hurts this much.", ["并不是", "不可能", "不能那样做", "也就是说"], ["it isn't that", "there's no way", "cannot very well", "it follows that"], "「わけがない」＝没道理。", "わけがない = there's no reason / no way.", "#/day/3-2/p2"),
            q(24, 3, "苦恼到最后，决定去大医院的神经科。", "After much anguish I decided to go to the neurology department of a big hospital.", ["过度以至于", "因为是…", "…的结果", "按照"], ["so much that", "because it is", "in the end after", "as"], "「悩んだ末」。", "Vた末 = after doing it to the end.", "#/day/3-3/p2"),
            q(25, 4, "脑子里一直想着去大医院。", "I just kept thinking of heading to a big hospital.", ["顾不上前去", "一个劲儿前去", "并不是前去", "一直想着前往"], ["in no state to go", "keep going", "doesn't mean I go", "keep heading there in my mind"], "文脉是心里一直想着去，用「向かいっぱなし」。", "っぱなし = left in that state / keep doing.", "#/day/3-5/p2"),
        ],
    },
    "w4": {
        "mondai1": [
            q(1, 4, "值此应试之际，请注意以下几点。", "Please note the following points as you sit the exam.", ["取决于", "沿着", "持续整个", "正当…的时候"], ["depending on", "along", "over the whole", "on the occasion of"], "「Nにあたり」＝正当那个时候。", "にあたり = on the occasion of.", "#/day/4-5/p0"),
            q(2, 2, "从B国出口到日本的农产品有八成是水果。", "80% of farm products exported from country B to Japan are fruit.", ["适合…的", "以…为对象的", "朝着", "对面"], ["suited to", "aimed at", "facing", "over there"], "「N向け」＝面向该对象。", "向け = intended for.", "#/day/4-6/p1"),
            q(3, 1, "一有新消息就通知您。", "We'll let you know as soon as new information comes in.", ["ます形＋次第", "词典形（不对）", "て形（不对）", "た形（不对）"], ["masu-stem + 次第", "dict. form (wrong)", "te-form (wrong)", "ta-form (wrong)"], "「入り次第」＝一进来就。", "次第 after a masu stem = as soon as.", "#/day/4-2/p0"),
            q(4, 1, "这道菜做法简单，而且材料也便宜。", "This dish is easy to make, and on top of that the ingredients are cheap.", ["而且", "在…之后／之上", "既然", "在…方面"], ["on top of that", "after / on the basis of", "now that", "in terms of"], "「A上にB」＝不但A而且B。", "上に = and what's more.", "#/day/4-1/p0"),
            q(5, 3, "她对他突然求婚既吃惊，却又显得高兴。", "She was surprised at his sudden proposal, yet she looked happy.", ["虽然", "没有理由", "虽然…却", "持续整个"], ["although", "no reason to", "even while", "over the whole"], "「ながらも」表示逆接。", "ながらも = even while / and yet.", "#/day/4-3/p2"),
            q(6, 1, "在会议开始之前，对与会者做了问卷调查。", "A questionnaire was given to participants before the meeting.", ["在…之前", "持续整个", "沿着", "相反"], ["prior to", "over the whole of", "along", "contrary to"], "「に先立ち」＝在那之前。", "に先立ち = prior to.", "#/day/4-5/p1"),
            q(7, 2, "从数字上看景气在恢复，我们却感觉不到。", "On paper the economy is recovering, but we don't feel it.", ["去掉", "在…之上／从数据上看", "比较起来", "面向"], ["without", "on the surface / on paper", "considering", "aimed at"], "「数字の上では」。", "Nの上では = on paper / in terms of.", "#/day/4-1/p3"),
            q(8, 3, "即便情况相同，幸福与否也取决于想法。", "Even in the same situation, happiness depends on how you think.", ["适合地", "沿着", "取决于", "正当…"], ["suited", "along", "depending on", "on the occasion of"], "「N次第で」＝视…而定。", "次第で = depending on.", "#/day/4-2/p1"),
            q(9, 2, "这本习题集是按照实际考试形式编写的。", "This workbook is written along the lines of the real exam.", ["正当…之际", "沿着／按照", "持续整个", "在…之前"], ["on the occasion of", "along / in line with", "over the whole", "prior to"], "「Nにそって」＝按照。", "にそって = along / in accordance with.", "#/day/4-4/p0"),
            q(10, 4, "这是汇总了长达六年观测数据的资料。", "This summarizes observational data spanning six years.", ["在…之前的", "有关", "沿着", "持续整个期间的"], ["prior", "concerning", "along", "spanning"], "「にわたる」修饰名词，表示时间跨度。", "にわたる = spanning (prenominal).", "#/day/4-4/p1"),
            q(11, 3, "看过实物之后再决定买不买。", "I'll decide whether to buy it after I've seen the real thing.", ["看（词典形）", "看（て形）", "看了之后", "不看"], ["see (dict.)", "see (te)", "after seeing", "not see"], "「Vた上で」＝做完之后再。", "Vた上で = after doing that, then.", "#/day/4-1/p1"),
            q(12, 2, "一边对孩子说要学习，大人自己却不学，我觉得不好。", "It's wrong for adults to tell children to study while not studying themselves.", ["言う", "言い＋つつ", "言って", "言った"], ["say", "masu-stem + つつ", "te-form", "ta-form"], "「言いつつ」＝一边说着。", "つつ = while (written).", "#/day/4-3/p1"),
            q(13, 3, "按老规矩，女性不得进入这里面。", "By long-standing custom, women are not allowed inside.", ["正在逐渐", "应该", "规定是…", "不能那样做"], ["gradually -ing", "should", "it is a rule that", "cannot very well"], "「ことになっている」表示规定。", "ことになっている = it is the rule.", "#/day/4-6/p2"),
            q(14, 2, "日本美丽的传统正在被日本人遗忘。", "Japan's beautiful traditions are gradually being forgotten by the Japanese.", ["不得不忘", "正在被遗忘", "规定要忘", "只不过忘"], ["have no choice but to forget", "are in the process of being forgotten", "it is arranged we forget", "merely forget"], "「つつある」表示正在进行的变化。", "つつある = be in the process of.", "#/day/4-3/p0"),
            q(15, 2, "这商品现在确实受欢迎，但不过是一时的流行。", "The product is popular now, but it's only a passing fad.", ["取决于", "只不过是", "不得不", "并不是"], ["depends on", "is nothing more than", "have no choice", "it isn't that"], "「にすぎない」＝只不过。", "にすぎない = nothing more than.", "#/day/4-6/p0"),
        ],
        "mondai2": [
            q(16, 3, "我不想撒谎，所以被问到就不得不说真话。", "I don't want to lie, so if I'm asked I have no choice but to tell the truth.", ["如果…的话", "不得不", "说真话", "被问"], ["if", "have no choice but to", "tell the truth", "if asked"], "「ざるをえない」。", "ざるをえない = have no choice but to.", "#/day/4-5/p2", {"order": "4→1→3→2"}),
            q(17, 1, "既然已经这样，就再找个别的爱好吧。", "Now that it's come to this, let's look for some other hobby.", ["什么", "别的", "既然", "已经这样了"], ["something", "other", "now that", "it's come to this"], "「こうなった上は」。", "Vた上は = now that it has come to this.", "#/day/4-1/p2", {"order": "4→3→1→2"}),
            q(18, 4, "总是拖到最后才准备。这次本该更早准备好的。", "I always leave prep to the last minute. I should have started earlier this time too.", ["准备", "更早", "应该", "事先"], ["prepare", "earlier", "should", "in advance"], "「ておくべきだった」。", "ておくべき = should have done it in advance.", "#/day/4-4/p2", {"order": "2→1→4→3"}),
            q(19, 2, "因此想请大家给予协助。", "So I would like to ask for everyone's cooperation.", ["情况是", "做", "请求", "协助"], ["the situation is that", "do", "request", "your cooperation"], "「お願いする次第です」郑重说明原委。", "次第です = (formal) that is how it stands / I hereby.", "#/day/4-2/p0", {"order": "4→3→2→1"}),
            q(20, 3, "与此相对，四五十岁的人并不支持他。", "By contrast, people in their 40s and 50s don't support him.", ["与此", "人们", "四五十岁的", "相对"], ["in contrast", "people", "those in their 40s–50s", "versus"], "「それに対し」。", "に対し = in contrast to that.", "#/day/4-6/p3", {"order": "1→4→3→2"}),
        ],
        "mondai3": [
            q(21, 1, "值此就业之际，承蒙您多方照顾。", "Thank you for all your help as I started my job.", ["正当…之际", "沿着", "持续整个", "响应"], ["on the occasion of", "along", "over the whole", "in response to"], "「就職にあたっては」。", "にあたって = at the time of.", "#/day/4-5/p0"),
            q(22, 3, "视努力情况，也有可能调到一直希望的营业部。", "Depending on my efforts I may be able to move to sales, which I wanted.", ["面向方面", "在那之前", "视…而定", "对于"], ["for the purpose of", "prior to", "depending on", "toward"], "「努力次第では」。", "次第では = depending on.", "#/day/4-2/p1"),
            q(23, 4, "一边学习前辈的做法，一边一件件记工作。", "I'm learning the job piece by piece while following my seniors.", ["一学习就", "却学习", "在学习方面", "一边学习一边"], ["as soon as I copy", "even though I copy", "for copying", "while copying"], "「見習いつつ」。", "つつ = while.", "#/day/4-3/p1"),
            q(24, 2, "夏天也不得不用空调。", "In summer we have no choice but to use the air conditioner.", ["只不过用", "不得不使用", "不该用", "正在被用"], ["merely use", "have no choice but to use", "should not use", "is being used"], "「使わざるをえない」。", "ざるをえない = cannot avoid doing.", "#/day/4-5/p2"),
            q(25, 4, "想努力达到前辈的期待。", "I want to work hard to live up to my seniors' expectations.", ["相当于", "与…有关", "对于", "响应／不辜负"], ["amount to", "be involved in", "toward", "respond to / live up to"], "「期待にこたえる」。", "にこたえる = live up to (expectations).", "#/day/4-6/p2"),
        ],
    },
    "w5": {
        "mondai1": [
            q(1, 2, "这座寺因绣球花出名，所以被称为绣球花寺。", "The temple is famous for hydrangeas, which is why it's called Hydrangea Temple.", ["令人…的是", "由于这个原因", "就因为是…", "如果能…"], ["it's … that", "from that fact", "precisely because", "if only"], "「ことから」表示判断的依据。", "ことから = on the grounds that.", "#/day/5-1/p0"),
            q(2, 3, "就因为个子高，我在哪儿都很显眼。", "Just because I'm tall I stand out wherever I am.", ["比较起来", "作为交换", "就因为", "别说"], ["considering", "in exchange", "precisely because (often unwelcome)", "far from"], "「ばかりに」表示就因为这个（多带来坏结果）。", "ばかりに = just because (unfortunate result).", "#/day/5-2/p2"),
            q(3, 4, "可以根据预算享受用餐。", "You can enjoy a meal according to your budget.", ["对于", "正当…之际", "和…相比", "根据／按照"], ["toward", "on the occasion of", "compared with", "in accordance with"], "「に応じて」＝视情况相应地。", "に応じて = according to / in response to.", "#/day/5-3/p1"),
            q(4, 1, "不亲自问问本人，就不知道为什么那样做。", "Unless I ask the person themselves I won't know why they did it.", ["如果不…的话", "由于这个原因", "就因为是…", "如果能…"], ["unless", "from that fact", "precisely because", "if only"], "「ないことには」＝如果不那样就。", "ないことには = unless that happens.", "#/day/5-1/p3"),
            q(5, 3, "入住本宿舍时，请先读好以下规定。", "When you move into this dorm, please read the following rules first.", ["根据", "按照", "正当…的时候", "相反"], ["based on", "according to", "at the time of", "contrary to"], "「に際して」＝在那个时候。", "に際して = when / at the time of.", "#/day/5-3/p2"),
            q(6, 1, "正如他自己也承认的，他确实没长性。", "As even he admits, he really does get bored easily.", ["到底不愧是", "不但…", "由于这个原因", "与其说"], ["as one would expect", "not only", "from that fact", "rather than"], "「だけあって」＝到底不愧。", "だけあって = as you'd expect from.", "#/day/5-4/p0"),
            q(7, 4, "税金是按照这张表计算的。", "Tax is calculated on the basis of this table.", ["随着", "根据（对应）", "和…相比", "以…为依据"], ["as", "in proportion to", "compared with", "based on"], "「Nに基づいて」。", "に基づいて = based on.", "#/day/5-4/p2"),
            q(8, 3, "酒驾不但危害驾驶者，也危害其他人。", "Drunk driving endangers not only the driver but other people too.", ["到底是", "比较起来", "不但…也", "一说起"], ["precisely because", "considering", "not only … but", "when it comes to"], "「ばかりか」＝不但，甚至。", "ばかりか = not only, but even.", "#/day/5-2/p1"),
            q(9, 1, "希望孩子能在可信赖的教育者指导下学习。", "I want my child to study under a trustworthy educator.", ["在…之下", "根据", "正当…之际", "根据"], ["under", "according to", "at the time of", "based on"], "「Nの下で」＝在其指导／影响下。", "の下で = under the guidance of.", "#/day/5-6/p0"),
            q(10, 2, "她的想法和行动普通人很难理解。", "Ordinary people find her thinking and behavior hard to understand.", ["能够", "难以", "很可能会", "只好"], ["can", "hard to", "might well", "have no choice but to"], "「理解しがたい」。", "がたい = hard to (often psychological).", "#/day/5-5/p1"),
            q(11, 4, "黄花开满田野，简直像铺了黄色地毯。", "Yellow flowers cover the fields, just as if a yellow carpet had been laid.", ["多么…啊", "都怪", "到底不愧", "仿佛…似的"], ["how …!", "it's because", "as expected", "as if"], "「かのようだ」＝宛如。", "かのようだ = as if it were.", "#/day/5-5/p3"),
            q(12, 2, "明天大家一起去给本校足球队加油吧！", "Tomorrow let's all go and cheer on our school's soccer team!", ["哪会去", "去吧（劝诱）", "去才是", "去来着"], ["as if I'd go", "let's go", "going is what", "was going, wasn't I"], "「行こうではないか」表示提议。", "Vようではないか = let's.", "#/day/5-6/p1"),
            q(13, 2, "就算许下做不到的诺言，也绝不可能遵守。", "There's no way you can keep a promise you can't actually fulfill.", ["难以遵守", "绝不可能遵守", "当然遵守", "很可能遵守"], ["hard to keep", "no chance of keeping", "of course keep", "might well keep"], "「っこない」＝不可能。", "っこない = no chance of.", "#/day/5-5/p2"),
            q(14, 3, "会员的个人信息恕难告知。", "I'm afraid we cannot give out members' personal information.", ["就是要告诉", "告诉得不得了", "难以告知", "很可能会告诉"], ["it follows we tell", "can't help telling", "cannot readily tell", "might well tell"], "「しかねます」委婉拒绝。", "かねる = cannot readily (polite refusal).", "#/day/5-5/p0"),
            q(15, 4, "那样下去很可能会搞坏身体。", "At that rate she's liable to ruin her health.", ["没法搞坏", "绝不会搞坏", "难以搞坏", "很可能会搞坏"], ["no way to break", "no chance of breaking", "hard to break", "might well break"], "「かねない」＝很有可能（多指坏事）。", "かねない = might well (negative outcome).", "#/day/5-5/p0"),
        ],
        "mondai2": [
            q(16, 2, "那只鸟不但叫声美，姿态也美。", "That bird is beautiful not only in song but in form.", ["美丽", "姿态也", "叫声", "不但"], ["beautiful", "the figure too", "the cry", "not only"], "「のみか」＝不但。", "のみか = not only (written).", "#/day/5-2/p0", {"order": "3→4→2→1"}),
            q(17, 3, "他很懂意大利，也难怪他一直想去。", "He knows Italy well — no wonder he's been wanting to go.", ["这件事", "一直", "不愧想去的", "有"], ["the fact", "all along", "enough that he wants to go", "there is"], "「だけのことはある」。", "だけのことはある = it makes sense / as you'd expect.", "#/day/5-4/p1", {"order": "2→3→4→1"}),
            q(18, 3, "以他那么在意时间的脾气，迟到了准会生气。", "Knowing how fussy he is about time, he's sure to be angry if we're late.", ["啰嗦", "就因为他是…", "他的", "对时间"], ["fussy", "knowing he is the sort who", "his", "about time"], "「ことだから」＝就因为他是那种人。", "ことだから = knowing what he's like.", "#/day/5-1/p2", {"order": "3→1→4→2"}),
            q(19, 3, "无论怎么练都不见进步，但她仍不放弃地继续练。", "Practice brought no progress, but she kept at it without giving up.", ["放弃", "练习", "没有", "这件事"], ["give up", "practice", "without", "the act of"], "「あきらめることなく」。", "ことなく = without doing.", "#/day/5-6/p2", {"order": "1→4→3→2"}),
            q(20, 4, "即便没说出口，那种态度也等于在说讨厌。", "Even if it isn't said aloud, that attitude is the same as saying you dislike it.", ["态度是", "等于", "讨厌", "也是在说"], ["the attitude is", "tantamount to", "dislike", "is also saying"], "「言っているのも同然だ」。", "も同然だ = tantamount to.", "#/day/5-6/p3", {"order": "1→3→4→2"}),
        ],
        "mondai3": [
            q(21, 2, "就因为英语不好，在海外没法沟通。", "Just because my English is weak I couldn't communicate abroad.", ["就因为是…", "就因为", "没有…地", "如果不…"], ["knowing one is", "precisely because (bad result)", "without", "unless"], "「苦手なばかりに」。", "ばかりに = just because (unfortunate).", "#/day/5-2/p2"),
            q(22, 3, "那样一来旅行的乐趣也很可能会减半。", "Then the fun of the trip might well be cut in half.", ["难以减半", "难以减半（礼貌）", "很可能会减半", "不像要减半"], ["hard to halve", "cannot readily halve", "might well be halved", "doesn't look like it will"], "「しかねません」＝很可能。", "かねない = might well.", "#/day/5-5/p0"),
            q(23, 3, "说一周就能说流利英语，一时难以相信。", "It's hard to believe English would become fluent in just a week.", ["相信是应该的", "很可能会信", "难以相信", "不愧会信"], ["of course believe", "might well believe", "hard to believe", "as expected believe"], "「信じがたい」。", "がたい = hard to.", "#/day/5-5/p1"),
            q(24, 1, "教材仿佛魔法一般好用。", "The materials work as if by magic.", ["仿佛", "到底不愧", "不但", "就因为"], ["as if", "as you'd expect", "not only", "just because"], "「かのように」。", "かのように = as if.", "#/day/5-5/p3"),
            q(25, 4, "报名参加课程时请确认费用。", "Please check the fee when you sign up for the course.", ["在…之下", "根据", "根据", "正当…之际"], ["under", "according to", "based on", "at the time of"], "「に際して」。", "に際して = when doing.", "#/day/5-3/p2"),
        ],
    },
    "w6": {
        "mondai1": [
            q(1, 4, "既然要招待，就打算办成愉快的聚会。", "Since we're inviting people, we intend to make it an enjoyable party.", ["以来", "从…来看", "据说", "既然…就"], ["since (time)", "judging from", "I hear", "now that / as long as"], "「からには」＝既然。", "からには = now that / as long as.", "#/day/6-1/p0"),
            q(2, 2, "那么失礼的人，我再也不会邀请。", "I'll never invite such a rude person again.", ["因为嘛", "不会…的", "正是", "多么…啊"], ["because", "will not (speaker's will)", "precisely", "how …!"], "「誘うまい」＝不打算再邀请。", "まい = will not (volition / conjecture).", "#/day/6-4/p1"),
            q(3, 1, "从学校方面来说，家里的问题很难管到。", "From the school's standpoint, they can hardly deal with problems at home.", ["从…来说", "单从…就", "虽说…也不", "既然"], ["from the point of view of", "even from", "even if", "now that"], "「からいえば」＝从该立场说。", "からいえば = speaking from that side.", "#/day/6-2/p0"),
            q(4, 3, "今日下午两点起在站前广场举行候选人演说。", "From 2 p.m. today there will be a candidate's speech in the plaza in front of the station.", ["正当…之际", "在那之前", "在…地点", "到…为止"], ["on the occasion of", "prior to", "at (place, formal)", "through / until"], "「Nにおいて」表示场所（郑重）。", "において = at (formal place).", "#/day/6-6/p2"),
            q(5, 3, "从梅雨到夏天，日本又热又难受。", "From the rainy season through summer, Japan is uncomfortably hot.", ["以来", "以…为首", "从…到…", "围绕"], ["since", "starting with", "from … through", "over / concerning"], "「から〜にかけて」表示时间跨度。", "にかけて = from A through B.", "#/day/6-3/p2"),
            q(6, 2, "不做准备活动就不能游泳。", "You must not swim until you've done a warm-up.", ["既然做了", "做了之后才行", "既然做了就", "虽说没做也不"], ["now that I did", "not until after doing", "now that", "not that I didn't"], "「てからでないと」＝在那之前不行。", "てからでないと = not until after.", "#/day/6-3/p1"),
            q(7, 4, "妹妹理解得慢，但论起认真谁也比不过。", "My sister is slow to understand, but when it comes to effort nobody beats her.", ["既然", "按…来说还算", "虽说也不", "论到这方面"], ["now that", "considering", "even if", "when it comes to"], "「にかけては」＝在这一方面。", "にかけては = when it comes to this point.", "#/day/6-3/p3"),
            q(8, 1, "既然过集体生活，就必须守规则和礼节。", "If you're going to live together, you have to keep the rules and manners.", ["既然", "虽说也不", "持续整个", "从…来看"], ["now that / since", "even if", "over the whole", "from the viewpoint of"], "「以上」＝既然处于这种情况。", "以上 = now that that's the case.", "#/day/6-1/p2"),
            q(9, 1, "这汤单看颜色就显得很辣。", "This soup looks spicy just from the color.", ["单从…就", "以…为首", "既然", "代替"], ["even from", "starting with", "now that", "in place of"], "「色からして」＝单从颜色就。", "からして = even judging from that alone.", "#/day/6-2/p1"),
            q(10, 3, "从外来人的角度看，这里的习惯也许很难接受。", "From an outsider's point of view these customs may be hard to accept.", ["既然", "单从…就", "从…来看", "如果不…"], ["now that", "even from", "seen from", "if not"], "「からみると」。", "からみると = seen from.", "#/day/6-2/p2"),
            q(11, 4, "这本小说主人公的原型肯定是那个人。", "The model for this novel's hero is undoubtedly that person.", ["有点像", "只不过", "仿佛", "一定是"], ["-ish", "nothing more than", "as if", "no doubt"], "「に相違ない」书面，表示断定。", "に相違ない = there is no mistake that.", "#/day/6-5/p3"),
            q(12, 3, "必须思考日本在亚洲的角色。", "We have to think about Japan's role in Asia.", ["围绕的", "到…为止", "在…之中的", "对于"], ["concerning", "through", "in (a field)", "toward"], "「における」是「において」的连体形。", "における = in (prenominal).", "#/day/6-6/p2"),
            q(13, 3, "本校可以学习以英语为首的七种语言。", "Our school offers seven languages, starting with English.", ["单从…就", "围绕", "以…为首", "在"], ["even from", "over", "starting with", "at"], "「をはじめ」。", "をはじめ = starting with / including foremost.", "#/day/6-6/p0"),
            q(14, 2, "听说昨晚的地震是震度3。", "They say last night's quake was intensity 3.", ["这件事", "据说", "多么…啊", "就是…的"], ["the fact", "I hear / they say", "how …!", "the kind of thing"], "「〜とか」表示不确定的传闻。", "とか = I hear (soft hearsay).", "#/day/6-4/p0"),
            q(15, 1, "教也就是被教。", "Teaching is nothing other than being taught.", ["正是／不外乎", "只好", "规定是", "到底不愧"], ["nothing other than", "have no choice", "it is arranged", "as you'd expect"], "「にほかならない」。", "にほかならない = nothing other than.", "#/day/6-5/p3"),
        ],
        "mondai2": [
            q(16, 1, "我输了是事实，只好承认。", "It's a fact that I lost, so I have no choice but to admit it.", ["其他", "比起", "承认", "没有"], ["other", "than", "admit", "there is not"], "「認めるよりほかない」。", "よりほかない = nothing else to do but.", "#/day/6-5/p2", {"order": "3→2→1→4"}),
            q(17, 3, "他连写都不练，光盯着汉字看，那样肯定记不住。", "He doesn't even practice writing, just stares at the kanji — that way he certainly won't remember them.", ["对／于", "被记住", "不", "那样的话"], ["in / by", "be remembered", "not", "with that"], "「に決まっている」。", "に決まっている = it's certain that.", "#/day/6-5/p0", {"order": "4→1→2→3"}),
            q(18, 4, "节约虽好，但不能因为可惜就不开灯学习，那样眼睛会坏。", "Saving is good, but you shouldn't study with the light off just because it's a waste.", ["虽说也不", "可惜", "如果学习", "不开灯"], ["even if", "wasteful", "if you study", "without turning on the light"], "「からといって」＝虽说如此也不能。", "からといって = just because … it doesn't mean.", "#/day/6-3/p0", {"order": "1→4→2→3"}),
            q(19, 3, "参加自由。不必为参加不参加而烦恼。", "Attendance is optional. There's no need to agonize over whether to go.", ["不会为难吧", "烦恼是没有的", "什么的", "要不要参加"], ["probably won't settle", "no need to worry", "or something", "whether to"], "「しようかすまいか」。", "V(よ)うかVまいか = whether to or not.", "#/day/6-4/p3", {"order": "4→3→1→2"}),
            q(20, 1, "自从听到同学在教室说自己坏话，他就没再来学校。", "Ever since he overheard classmates badmouthing him, he has stopped coming to school.", ["以来", "他", "听到", "完了"], ["since", "he", "hearing", "ended up"], "「て以来」。", "て以来 = ever since.", "#/day/6-1/p3", {"order": "3→4→2→1"}),
        ],
        "mondai3": [
            q(21, 2, "从四月上旬到中旬举办郁金香节。", "A tulip festival is held from early to mid-April.", ["持续整个", "从…到…", "正当…之际", "随着"], ["over the whole period", "from … through", "on the occasion of", "as"], "「にかけて」表示期间。", "にかけて = from A through B.", "#/day/6-3/p2"),
            q(22, 4, "虽说有节日，并不等于很多人在种郁金香。", "Just because there's a festival doesn't mean many people grow tulips.", ["从…来看", "既然", "单从…就", "虽说也不"], ["judging from", "now that", "even from", "just because … not"], "「からといって」。", "からといって = that doesn't mean.", "#/day/6-3/p0"),
            q(23, 3, "不先把花种上，节日就办不成。", "You can't hold the festival until the flowers have been planted.", ["种了的时候", "种了以来", "种了之后才行", "既然要种"], ["when planted", "since planting", "not until after planting", "now that we plant"], "「てからでないと」。", "てからでないと = not until after.", "#/day/6-3/p1"),
            q(24, 4, "以日本产量第一的富山为首，各地的花都汇集过来。", "Flowers gather from tulip-growing areas nationwide, starting with Toyama, Japan's top producer.", ["在（口语）", "围绕", "在", "以…为首"], ["at (casual)", "over", "at", "starting with"], "「をはじめ」。", "をはじめ = starting with.", "#/day/6-6/p0"),
            q(25, 1, "听说数量之多全国数一数二。", "I hear it's one of the top one or two in the country for volume.", ["据说有", "不会有吧", "就是有的", "正是有才"], ["they say there is", "probably isn't", "it is that there is", "only because there is"], "「のだとか」传闻。", "とか = I hear.", "#/day/6-4/p0"),
        ],
    },
    "w7": {
        "mondai1": [
            q(1, 1, "无论是买还是借，课本都必须带来。", "Whether you buy it or borrow it, you must bring the textbook.", ["无论是…还是", "又是…又是", "也…也", "又…又"], ["whether … or", "X and Y and", "also / also", "and / and"], "「にしろ〜にしろ」。", "にしろ〜にしろ = whether A or B.", "#/day/7-2/p2"),
            q(2, 1, "以住院为契机买了保险。", "Hospitalization was the trigger for taking out insurance.", ["以…为契机", "以…为基础", "不顾", "尽管"], ["taking … as a turning point", "based on", "without caring about", "despite"], "「を契機として」。", "を契機として = taking that as a turning point.", "#/day/7-6/p2"),
            q(3, 2, "收到带着心意的礼物会很高兴。", "It's nice to receive a gift that has feeling put into it.", ["转了一圈的", "倾注了（心意）", "通过了", "贯穿了"], ["went around", "filled with (feeling)", "went through", "ran through"], "「心のこもった」。", "こめる = put (feeling) into.", "#/day/7-4/p1"),
            q(4, 2, "她既听不见也看不见。", "She could neither hear nor see.", ["听不见就", "既听不见也", "如果不听见", "即使听见"], ["if she can't hear", "can't hear, and also", "if she doesn't hear", "even if she hears"], "「も〜ば〜も」并列。", "も〜ば〜も = neither … nor / both.", "#/day/7-2/p3"),
            q(5, 3, "他顾不上衣服弄脏，抱起了受伤的人。", "He scooped up the injured person without caring that his clothes would get dirty.", ["不问", "每当", "不顾", "即使"], ["regardless of", "every time", "without caring about", "even if"], "「もかまわず」。", "もかまわず = without minding.", "#/day/7-1/p0"),
            q(6, 1, "那位钢琴家在国内外都很活跃。", "That pianist is active both at home and abroad.", ["不问", "以…为中心", "通过", "以…为契机"], ["regardless of", "centered on", "through", "taking as a chance"], "「内外を問わず」。", "を問わず = regardless of.", "#/day/7-1/p3"),
            q(7, 2, "通过志愿者活动为社会做贡献。", "Contribute to society through volunteer work.", ["关于", "通过", "根据", "在那之前"], ["concerning", "through", "according to", "prior to"], "「を通じて」。", "を通じて = through.", "#/day/7-4/p2"),
            q(8, 3, "今天又是打雷又是地震，总觉得不平常。", "What with thunder and then an earthquake, today feels anything but normal.", ["无论是…还是", "每当…每当", "又是…又是", "也…也"], ["whether", "every time", "X and Y and (messy list)", "also"], "「やら〜やら」列举杂乱事物。", "やら〜やら lists mixed items.", "#/day/7-2/p0"),
            q(9, 2, "人就是会想要自己没有的东西。", "People naturally want what they don't have.", ["多么…啊", "就是会…的（本质）", "不必", "有…之处"], ["how …!", "that's what people do", "no need", "there is something"], "「ものだ」谈一般倾向。", "ものだ states a general truth.", "#/day/7-3/p0"),
            q(10, 3, "每当穿上这件衣服，就会想起母亲。", "Whenever I wear this dress I think of my mother.", ["又是", "每（公文）", "每当", "沿着"], ["and", "per (formal)", "every time", "along"], "「Vるにつけ」。", "につけ = every time / whenever.", "#/day/7-2/p1"),
            q(11, 2, "那种病有从动物传到人的危险。", "That disease may spread from animals to humans.", ["契机", "危险／恐怕", "略微", "倾向"], ["turning point", "risk / fear that", "a touch of", "a leaning"], "「恐れがある」。", "恐れがある = there is a risk that.", "#/day/7-5/p0"),
            q(12, 4, "虽说对身体好，也不是吃得越多越好。", "Just because it's healthy doesn't mean the more you eat the better.", ["有道理", "也就是说", "取决于", "也并非如此"], ["there is reason", "it follows that", "depends", "not necessarily"], "「というものでもない」。", "というものでもない = not necessarily.", "#/day/7-5/p2"),
            q(13, 3, "这座小镇有让人心情平静下来的东西。", "This town has something that soothes the heart.", ["就是会…", "哪会", "有…之处", "不该"], ["that's what one does", "as if I would", "there is something that", "one shouldn't"], "「ものがある」表示确实能感觉到某种特质。", "ものがある = there is something (notable).", "#/day/7-5/p1"),
            q(14, 1, "这本习题集是以实际课堂教材为基础编写的。", "This workbook is based on materials actually used in class.", ["以…为基础", "不问", "倾注", "以…为契机"], ["based on", "regardless of", "putting into", "taking as a chance"], "「をもとにして」。", "をもとに = based on.", "#/day/7-6/p0"),
            q(15, 2, "网上预约时需要密码。", "A password is required when you reserve online.", ["正在…之中", "在…的时候", "每次", "作为交换"], ["in the middle of", "when / on the occasion of", "every time", "in place of"], "「Nの際には」。", "際 = when / at the time of.", "#/day/7-6/p3"),
        ],
        "mondai2": [
            q(16, 4, "他们不可能理解。那纯粹是浪费时间。", "There's no way they'll understand. It would just be a waste of time.", ["浪费", "东西／就是", "时间的", "所谓"], ["waste", "thing / the very", "of time", "what you call"], "「というものだ」表示说话人的评价。", "というものだ = that's what I'd call.", "#/day/7-3/p2", {"order": "3→1→4→2"}),
            q(17, 2, "别人讨厌的事自己不该做。", "You shouldn't do to others what they hate.", ["讨厌", "做", "事情", "不该"], ["hate", "do", "the thing", "one shouldn't"], "「ものではない」表示劝戒。", "ものではない = that's not what one should do.", "#/day/7-3/p1", {"order": "1→3→2→4"}),
            q(18, 1, "邮购目录常送来。不管希望不希望都会寄来。", "Mail-order catalogs often arrive, whether you asked for them or not.", ["不管", "不做", "希望", "被寄来"], ["regardless of", "not do", "wish", "are sent"], "「にかかわらず」。", "にかかわらず = regardless of.", "#/day/7-1/p2", {"order": "3→2→1→4"}),
            q(19, 3, "书借给他以后被弄脏还回来了。再也不借了。", "I lent him a book and it came back dirty. Never again.", ["绝不再借", "还回来了", "绝对再", "弄脏了之后"], ["as if I'd lend again", "came back", "absolutely again", "having gotten dirty"], "「ものか」强烈否定。", "ものか = as if I would.", "#/day/7-3/p3", {"order": "4→2→3→1"}),
            q(20, 1, "以香烟涨价为契机想戒烟，但失败了。", "I tried to quit smoking when the price went up, but failed.", ["以…为契机", "涨价了", "想戒", "把那件事"], ["taking as a chance", "went up", "tried to quit", "that (nominalizer)"], "「のをきっかけに」。", "をきっかけに = taking that as a chance.", "#/day/7-6/p1", {"order": "2→4→1→3"}),
        ],
        "mondai3": [
            q(21, 3, "以父母的友人为中心开始了募捐。", "A fund-raising drive began, centered on the parents' friends.", ["以…为契机", "以…为基础", "以…为中心", "围绕"], ["taking as a chance", "based on", "centered on", "over"], "「を中心に」。", "を中心に = centered on.", "#/day/7-4/p0"),
            q(22, 1, "在海外也有不问年龄就能做手术的国家。", "Overseas there are countries where you can have the operation regardless of age.", ["不问年龄", "尽管年龄", "靠年龄", "倾注年龄"], ["regardless of age", "despite age", "relying on age", "putting age into"], "「を問わず」。", "を問わず = regardless of.", "#/day/7-1/p3"),
            q(23, 4, "国家就不能想想办法吗？", "Can't the government do something about this situation?", ["就是那样吧", "有…之处", "也并非如此", "就不能…吗"], ["that's what it is, right", "there is something", "not necessarily", "can't they …?"], "「ものでしょうか」表示不满的反问。", "ものか／ものでしょうか = (rhetorical) surely not / can't they.", "#/day/7-5/p3"),
            q(24, 3, "通过媒体报道，捐款从全国汇来。", "Donations came in from all over the country through media coverage.", ["每", "不问", "通过", "在…的时候"], ["per", "regardless of", "through", "when"], "「を通じて」。", "を通じて = through.", "#/day/7-4/p2"),
            q(25, 1, "收到了许多充满心意的信件。", "Many heartfelt letters arrived.", ["充满了（心意）的", "不顾", "又是", "即使"], ["filled with feeling", "without caring", "and", "even if"], "「心のこもった」。", "こもった = filled with (feeling).", "#/day/7-4/p1"),
        ],
    },
    "w8": {
        "mondai1": [
            q(1, 3, "未成年也能入会。不过需要监护人许可。", "Minors can join. However, a guardian's permission is required.", ["于是", "总之", "不过", "因此"], ["then", "in short", "however / provided that", "therefore"], "「ただし」补充例外条件。", "ただし = provided that / however.", "#/day/8-4/p3"),
            q(2, 4, "“第一次看歌舞伎。”“那感觉怎么样？”", "“I saw kabuki for the first time.” “So how was it?”", ["另外", "于是（解决问题）", "且说", "那么／所以呢"], ["incidentally", "so (to deal with it)", "now then", "and so / well?"], "「それで」催促往下说。", "それで = and so? (prompting).", "#/day/8-1/p3"),
            q(3, 1, "请带驾照或健康保险证等身份证明。", "Please bring a driver's license or health-insurance card to prove your identity.", ["或者", "也就是说", "不过", "话虽如此"], ["or", "namely", "however", "admittedly"], "「あるいは」表示选择。", "あるいは = or.", "#/day/8-3/p1"),
            q(4, 3, "开瓶盖总是很费劲。于是就开发了这个商品。", "I always struggled with jar lids. So I developed this product.", ["于是（一…就）", "且说", "于是（为此）", "另外"], ["thereupon", "now then", "and so (that's why I acted)", "incidentally"], "「そこで」表示因此采取行动。", "そこで = and so (I did X).", "#/day/8-2/p1"),
            q(5, 4, "“这张小猫照片真可爱。”“是啊。对了，最近没看见邻居家的猫呢。”", "“This kitten photo is cute.” “Yeah. Come to think of it, I haven't seen the neighbor's cat lately.”", ["之所以", "也就是说", "不过", "说起来"], ["the reason is", "which means", "admittedly", "come to think of it"], "「そういえば」表示突然想起。", "そういえば = that reminds me.", "#/day/8-2/p2"),
            q(6, 1, "人气职业高尔夫选手后面跟着一大群也就是观众的人。", "A popular pro golfer has a crowd of spectators — that is, a gallery — trailing after him.", ["也就是说", "或者", "而且（加码）", "顺便一提"], ["namely", "or", "what's more", "by the way"], "「すなわち」换一种说法。", "すなわち = namely / that is.", "#/day/8-3/p0"),
            q(7, 2, "“信帮我寄了吗？”“那个啊，我忘了，还在包里。”", "“Did you mail the letter?” “Well, I forgot — it's still in my bag.”", ["说起来", "可是（结果不如意）", "对了换话题", "于是"], ["come to think of it", "well actually (unexpected)", "anyway, changing topic", "and so"], "「それが」引出不如意的结果。", "それが = well, as it turns out.", "#/day/8-2/p0"),
            q(8, 3, "“为什么不要收据？”“因为用不着嘛。”", "“Why don't you take the receipt?” “Because I don't need it.”", ["且说", "可是", "因为（辩解）", "另外"], ["now then", "but", "because (justifying)", "incidentally"], "「だって」口语申辩。", "だって = because (defensive).", "#/day/8-3/p3"),
            q(9, 1, "啊，左手无名指有戒指…也就是说已经结婚了吧。", "Ah, a ring on the left ring finger… so that means they're married?", ["也就是说", "之所以", "因此", "对了换话题"], ["which means", "the reason is", "therefore", "anyway"], "「ということは」从事实推出结论。", "ということは = which means that.", "#/day/8-4/p0"),
            q(10, 2, "我能来这儿今天是最后一次。因为我要换工作了。", "Today is the last time I can come here. That's because I'm changing jobs.", ["不过", "之所以／因为", "于是", "尽管如此"], ["admittedly", "the reason is", "and so", "even so"], "「というのは」解释原因。", "というのは = the reason is.", "#/day/8-4/p1"),
            q(11, 2, "“想了解日本传统文化。”“那就选这个课程吧。”", "“I want to learn about traditional Japanese culture.” “In that case this course is good.”", ["所以", "如果是那样的话", "尽管如此", "尽管那样"], ["so", "in that case", "even so", "and yet"], "「それなら」承接对方的话给建议。", "それなら = in that case.", "#/day/8-1/p2"),
            q(12, 4, "“昨天真不容易。”“是啊，好累。对了，高桥选手拿奖牌了呢！”", "“Yesterday was rough.” “Yeah, I was exhausted. Anyway — Takahashi won a medal!”", ["总之", "也就是说", "尽管那样", "对了换话题"], ["in short", "which means", "and yet", "anyway / changing topic"], "「それはそうと」转换话题。", "それはそうと = anyway (new topic).", "#/day/8-2/p3"),
            q(13, 2, "感谢您的订购。另外，这封邮件是系统自动回复的。", "Thank you for your order. Also, this email is an automatic reply.", ["且说", "另外补充", "可是", "只是"], ["now then", "additionally / please note", "but", "only"], "「なお」补充说明。", "なお = additionally (formal).", "#/day/8-5/p1"),
            q(14, 1, "从书架取下一本书打开。于是里面夹着一张旧照片。", "I took a book from the shelf and opened it. Then I found an old photo inside.", ["于是（一…就发现）", "也就是说", "于是（为此行动）", "如果那样"], ["thereupon / when I did", "namely", "and so I acted", "if so"], "「すると」表示一做就发生。", "すると = and then (what happened next).", "#/day/8-5/p3"),
            q(15, 3, "学分不够。因此你就不能毕业。", "You don't have enough credits. Therefore you cannot graduate.", ["不过", "于是（一…就）", "因此", "可是（不如意）"], ["admittedly", "thereupon", "therefore", "well actually"], "「したがって」表示逻辑结论。", "したがって = therefore (formal).", "#/day/8-4/p2"),
        ],
        "mondai2": [
            q(16, 4, "全球变暖被大肆炒作。可据某位知识人说，也有人认为没那回事。", "Global warming is much talked about. But according to one intellectual, some say it isn't so.", ["可是", "也有人说没那回事", "某位知识人", "根据"], ["but", "some say it isn't so", "a certain intellectual", "according to"], "「によれば」。", "によれば = according to.", "#/day/8-5/p0", {"order": "3→4→2→1"}),
            q(17, 1, "请参加自治会清扫。不过这不是义务，而是自愿。", "Please join the neighborhood cleanup. This is not an obligation, however, but voluntary.", ["不是义务", "这是", "不过", "出于自主的"], ["not a duty", "this is", "admittedly / however", "of one's own will"], "「もっとも」补充修正。", "もっとも = although / that said.", "#/day/8-5/p0", {"order": "2→3→1→4"}),
            q(18, 1, "多次提醒这会考到别弄错。尽管如此还是有很多学生错了，真遗憾。", "I warned them again and again this would be on the test. Even so, many students got it wrong.", ["学生", "尽管如此", "弄错了", "有很多是遗憾的"], ["students", "even so", "got it wrong", "it was a pity many did"], "「それなのに」逆接。", "それなのに = and yet.", "#/day/8-1/p0", {"order": "2→1→3→4"}),
            q(19, 2, "可以使用信用卡，或者便利店后付也可以。", "You can use a credit card, or pay later at a convenience store.", ["或者", "在便利店的", "后付也可以", "可以使用"], ["or", "at a convenience store", "later payment is also possible", "can be used"], "「あるいは」连接选择。", "あるいは = or.", "#/day/8-3/p1", {"order": "1→4→2→3"}),
            q(20, 3, "这个项目的主题是“生态”，也就是考虑环境。", "The theme of this project is “eco,” that is, thinking about the environment.", ["也就是生态", "主题是生态", "换句话说", "考虑环境"], ["namely ecology", "the theme is eco", "in other words", "think about the environment"], "「すなわち／つまり」。", "すなわち = namely.", "#/day/8-3/p0", {"order": "2→1→3→4"}),
        ],
        "mondai3": [
            q(21, 3, "且说，绿山市将为从未用过电脑的人开办电脑班。", "Now then, Midoriyama City will offer a computer class for people who have never used a PC.", ["可是", "另外", "且说（转入正题）", "于是"], ["but", "additionally", "now then (starting the topic)", "thereupon"], "通知开头用「さて」转入正题。", "さて = now then (opening a topic).", "#/day/8-5/p2"),
            q(22, 1, "去年的参加者说“很实用，而且免费真好”。", "Last year's participants said it was practical and, what's more, free.", ["免费真帮了大忙", "没意思", "学费贵", "明年还想参加"], ["being free was a help", "was boring", "the fee was high", "I want to join next year"], "和「わかりやすく、しかも」并列好评。", "しかも adds another plus.", "#/day/8-6/p1"),
            q(23, 2, "“说起来，我还没用过电脑呢。”", "“Come to think of it, I've never used a computer.”", ["之所以", "说起来", "也就是说", "尽管那样"], ["the reason is", "come to think of it", "which means", "and yet"], "「そういえば」想起自己的情况。", "そういえば = that reminds me.", "#/day/8-2/p2"),
            q(24, 1, "可以来教室，或者使用网上教材。", "You can come to the classroom, or use the online materials.", ["或者", "也就是说", "而且", "所以"], ["or", "namely", "what's more", "so"], "「あるいは」表示选择。", "あるいは = or.", "#/day/8-3/p1"),
            q(25, 3, "另外，教材费另计。", "Also, the cost of materials is extra.", ["尽管如此", "因此", "另外", "可是（不如意）"], ["even so", "therefore", "additionally", "well actually"], "「なお」补充注意事项。", "なお = additionally.", "#/day/8-5/p1"),
        ],
    },
}
