def t(cn, en, opts_cn=None, opts_en=None, point="", point_en=""):
	return {"cn": cn, "en": en, "opts_cn": opts_cn or [], "opts_en": opts_en or [], "point": point, "point_en": point_en}


VOCAB_EXAM = {
	"1-1": t("我住在一栋建了20年的独栋房子里。", "I live in a detached house that is 20 years old.", ["经过", "度过", "建造", "建筑年数"], ["elapse", "pass", "build", "years since built"], "房子年数用「築」。", "Use 築 for how old a building is."),
	"1-2": t("电车从我家正后方开过。", "Trains run right behind my house.", ["正后方", "这附近", "这一带", "正中间"], ["right behind", "this vicinity", "this area", "the middle"]),
	"1-3": t("换成节能的新冰箱后，电费便宜了。", "After switching to an energy-saving fridge, the electric bill went down.", ["回收", "节能", "节约", "再利用"], ["recycle", "energy-saving", "economize", "reuse"]),
	"1-4": t("在银行汇了房租。手续费很贵。", "I transferred the rent at the bank. The fee was high.", ["管理费", "押金", "房租", "手续费"], ["management fee", "deposit", "rent", "handling fee"]),
	"1-5": t("逃跑的银行劫匪终于被抓住了。", "The fleeing bank robber was finally caught.", ["被抓住", "收拾了", "上当了", "处理了"], ["was caught", "tidied up", "got tricked", "disposed of"]),
	"1-6": t("那些垃圾会成为回收资源，请不要当可燃垃圾扔掉。", "That trash becomes a recycling resource, so don't put it with burnable garbage.", ["用品", "资源", "再利用", "不可燃"], ["supplies", "resource", "reuse", "non-burnable"]),
	"1-7": t("发烧出了很多汗，所以换了内衣。", "I ran a fever and sweated a lot, so I changed my underwear.", ["划了", "沐浴了", "照到了", "出了（汗）"], ["rowed", "bathed", "exposed", "sweated"]),
	"1-8": t("在外面吃太贵，所以我自己做饭。", "Eating out is costly, so I cook for myself.", ["自己做饭", "不足", "炊事", "独居"], ["home cooking", "shortage", "cooking work", "living alone"]),
	"1-9": t("大纸箱请当作资源垃圾扔掉。", "Please put large cardboard out as recyclable trash.", ["资源垃圾", "厨余", "分类", "碗碟"], ["recyclables", "food waste", "sorting", "dishes"]),
	"1-10": t("喝醉的上班族在街上撒野。", "A drunken office worker is causing a scene in the street.", ["打", "放松", "潜", "撒野"], ["hit", "relax", "dive", "rampage"]),
	"1-11": t("做客时主人端出茶点，可以说「请别张罗」。", "When a host serves tea, you can say 'please don't go to any trouble.'", ["打扰了", "请慢用", "请别张罗", "托您的福"], ["excuse the intrusion", "take your time", "don't trouble yourself", "thanks to you"]),
	"1-12": t("生气时大声喊叫。", "To shout loudly when angry.", ["撒野", "溺水", "欺负", "呵斥"], ["rage", "drown", "bully", "yell at"]),
	"1-13": t("花钱超过必要程度叫奢侈。", "Spending more than necessary is extravagance.", ["奢侈", "支付", "亏空", "余裕"], ["luxury", "payment", "deficit", "leeway"]),
	"1-14": t("液体从有洞的容器漏出去。", "Liquid leaking out of a container with a hole.", ["冲洗", "泄漏", "潜入", "省略"], ["rinse", "leak", "dive under", "omit"]),
	"1-15": t("把传单、海报从墙上揭下来。", "Peeling flyers and posters off the wall.", ["贴", "泄漏", "揭下", "洒出"], ["paste", "let leak", "peel off", "spill"]),
	"1-16": t("把穿不了的西装扔掉了。", "I threw out a suit I could no longer wear.", ["处理掉", "分类了", "节约了", "省掉了"], ["disposed of", "sorted", "saved", "omitted"]),
	"1-17": t("又不是小孩子，那种事别做了。", "You're not a child, so stop doing that.", ["停下", "蹬", "别做了", "钓"], ["stop it", "pedal", "cut it out", "fish"]),
	"1-18": t("那人摘下墨镜后，眼睛看起来很温和。", "When that person took off the sunglasses, they had kind eyes.", ["摘下", "拉", "抽出", "淋"], ["take off", "pull", "draw out", "pour over"]),
	"1-19": t("啤酒罐等请冲洗后再当不可燃垃圾扔掉。", "Please rinse beer cans before putting them out as non-burnable trash.", ["压扁", "积着", "冲洗", "洒出"], ["crush", "accumulate", "rinse", "spill"]),
	"1-20": t("今年过年在家里悠闲度过。", "I spent New Year at home at a leisurely pace.", ["吵闹", "悠闲", "奢侈", "无聊"], ["noisily", "leisurely", "extravagantly", "boringly"]),
	"1-21": t("「一点心意，请收下」是送礼物时的说法。", "'It's nothing much, but please take it' is said when giving a gift.", ["您身体好吗", "请慢坐", "这是一点心意，请收下", "不客气我收下了"], ["how have you been", "please stay", "a small gift, please take it", "I'll gratefully accept"]),
	"1-22": t("「高くつく」是花费变多，不是建筑物高。", "高くつく means it ends up costing more.", ["36层很贵", "路费一加反而更贵", "富士山最高", "拍卖卖得贵"], ["36 floors cost a lot", "travel costs made it more expensive", "Mt. Fuji is tallest", "sold high at auction"], "高くつく＝结果变贵。", "高くつく = ends up expensive."),
	"1-23": t("小猫撒娇地叫。", "The kitten mewed in a spoiled voice.", ["小猫撒娇叫", "蛋糕很撒娇", "被娇惯长大", "社长心情不好在撒娇"], ["kitten mewed sweetly", "cake is spoiled", "raised spoiled", "the boss is sulking"]),
	"1-24": t("别用脚踢前面的座位。", "Don't kick the seat in front of you.", ["脸被脚踢伤", "被爸爸大声踢", "别踢前面座位", "没把球踢进球门"], ["kicked in the face", "kicked loudly by dad", "don't kick the seat", "couldn't kick a goal"]),
	"1-25": t("请趁热享用。", "Please enjoy it before it gets cold.", ["我正在享用茶", "请进屋里享用", "远道而来请享用", "趁热请用"], ["I am partaking of tea", "please come in and eat", "welcome, please eat", "please eat while it's hot"]),
	"2-1": t("选定打印范围再打印。", "Select the print range and then print.", ["作成", "转换", "选择", "消除"], ["create", "convert", "select", "erase"]),
	"2-2": t("我是从大阪分公司调过来的田中。", "I'm Tanaka, transferred from the Osaka branch.", ["转发", "派遣", "通勤", "调动"], ["forward", "dispatch", "commute", "transfer"]),
	"2-3": t("在网上检索了那家公司的信息。", "I searched for that company's information online.", ["检索", "签约", "插入", "录用"], ["search", "contract", "insert", "hire"]),
	"2-4": t("不景气，要拿到奖金很难。", "In a slump it's hard to get a bonus paid out.", ["赚钱", "挣到", "发放", "连接"], ["profit", "earn", "pay out", "connect"]),
	"2-5": t("把旧文件删除了。", "I deleted the outdated files.", ["删除", "拒绝", "放大", "作成"], ["erase", "refuse", "enlarge", "create"]),
	"2-6": t("请把细节再具体说明一下。", "Please explain the details more concretely.", ["确定地", "消极地", "抽象地", "具体地"], ["definitely", "passively", "abstractly", "concretely"]),
	"2-7": t("那件事明天商量吧。", "Let's discuss that tomorrow.", ["导入", "干劲", "传达", "商量"], ["take in", "enthusiasm", "relay", "meeting"]),
	"2-8": t("会议上被征求意见，很为难。", "I was asked for an opinion in the meeting and didn't know what to say.", ["被征求", "被汇总", "被偷懒", "被连接"], ["asked for", "summarized", "slacked", "connected"]),
	"2-9": t("一直唱歌是她的生存意义。", "Singing on is what gives her life meaning.", ["值得做", "生存意义", "值得唱", "值得干"], ["worth doing", "reason for living", "worth singing", "worth it"]),
	"2-10": t("下个月的日程还没排。", "I still haven't put together next month's schedule.", ["编排", "摄入", "错开", "做完"], ["assemble", "take in", "shift", "finish off"]),
	"2-11": t("把不好的地方改正确。", "Correcting something so it is right.", ["修改", "缩小", "选择", "插入"], ["revise", "reduce", "select", "insert"]),
	"2-12": t("聚集到一处。", "Gathering things into one place.", ["合并", "得到", "送回", "聚拢"], ["combine", "obtain", "return", "gather"]),
	"2-13": t("当作不需要而去掉。", "Removing something as unnecessary.", ["汇总", "省略", "对齐", "做完"], ["summarize", "omit", "align", "handle"]),
	"2-14": t("和某物相称、合适的样子。", "Being appropriate / a good match.", ["轻松的", "费事", "相称", "有意义"], ["casual", "time-consuming", "suitable", "rewarding"]),
	"2-15": t("电脑突然不动了。", "The computer suddenly froze.", ["下载", "死机", "光标", "粘贴"], ["download", "freeze", "cursor", "paste"]),
	"2-16": t("不报销交通费，所以拒绝了那份兼职。", "They don't pay travel costs, so I turned the job down.", ["不发放", "不赚钱", "挣不到", "出错"], ["not paid out", "not profitable", "can't earn", "mistaken"]),
	"2-17": t("打开了那家公司的主页。", "I accessed that company's homepage.", ["启动", "检索", "接收", "连接访问"], ["boot", "search", "receive", "connect/access"]),
	"2-18": t("把网上找到的图片贴进了文件。", "I pasted an image from the internet into the document.", ["剪切", "复制", "粘贴", "保存"], ["cut", "copy", "paste", "save"]),
	"2-19": t("复印纸快用完了，先买着吧。", "We're about to run out of copy paper, so let's buy some.", ["错开", "用尽", "送回", "做完"], ["shift", "run out", "return", "handle"]),
	"2-20": t("忙得连吃午饭的空档都没有。", "I was so busy I didn't even have a moment to eat lunch.", ["空闲", "期间", "心思", "休假"], ["free time", "period", "mood", "leave"]),
	"2-21": t("按日程把工作一件件做完。", "I worked through the jobs on schedule.", ["做完会议", "提前做完午饭", "做完保留", "按日程做完工作"], ["finish a meeting", "finish lunch early", "finish hold", "get through the work"]),
	"2-22": t("他拍上司马屁往上爬。", "He got ahead by sucking up to his boss.", ["部长向社长拍马", "为了不拍马上司而出主意", "拍马上司出人头地", "累了可以拍马吗"], ["the manager flattered the president", "advised without flattering", "got promoted by flattering", "may I flatter because I'm tired"]),
	"2-23": t("铃木科长这会儿不在座位上。", "Section chief Suzuki is away from his desk at the moment.", ["不巧现在离开座位", "离开座位前来拜访", "在公交上让座说成离开座位", "电车离开座位运行"], ["unfortunately away from his desk", "leaving the seat to visit", "gave up a bus seat", "trains running without seats"]),
	"2-24": t("商量拖长了，下一个约会迟到了。", "The meeting ran long and I was late for the next appointment.", ["等久了", "文章很长", "通勤时间变长", "商量拖长迟到"], ["the wait dragged on", "the email is long", "commute takes longer", "the meeting ran over"]),
	"2-25": t("请把照片附在简历里寄出。", "Please attach a photo to your resume and send it.", ["把光标附到最右", "简历附上照片", "把多余图片从电脑附走", "墨水附上了"], ["attached the cursor", "attach a photo to the CV", "attached extra images away", "the ink attached"]),
}

VOCAB_EXAM.update({
	"3-1": t("扮成圣诞老人的人扛着大袋子走。", "Someone dressed as Santa is walking with a big bag on their shoulder.", ["扛着", "抱着", "贴着", "靠着"], ["shouldering", "holding", "sticking", "leaning"]),
	"3-2": t("那支队伍功亏一篑没拿到冠军。", "The team missed the title by a frustratingly small margin.", ["不甘心", "丢人", "对不起", "可惜"], ["regrettable", "pathetic", "sorry", "so close"]),
	"3-3": t("轮胎被雨滑得撞上了墙。", "The tires slipped in the rain and hit the wall.", ["绊倒", "打滑", "拧", "跨过"], ["trip", "slip", "twist", "step over"]),
	"3-4": t("不能一直依赖父母。", "You mustn't keep depending on your parents.", ["让父母轻松", "改正", "被眷顾", "依靠"], ["ease them", "reform", "be blessed", "rely on"]),
	"3-5": t("连好友都背叛了，再也信不过任何人。", "Even my best friend betrayed me; I can't trust anyone now.", ["被背叛", "被安慰", "被干掉", "被顶撞"], ["betrayed", "comforted", "beaten", "opposed"]),
	"3-6": t("别含糊回答，不愿意就直说不愿意。", "Don't give a vague answer — if you don't want to, say so.", ["难看", "含糊", "相称", "常见"], ["ugly", "vague", "suitable", "common"]),
	"3-7": t("他总是叼着烟看报。", "He's always reading the paper with a cigarette in his mouth.", ["啃", "抱", "夹", "叼"], ["gnaw", "hold", "sandwich", "hold in mouth"]),
	"3-8": t("他总是笑着，是个开朗的人。", "He's always smiling — a cheerful person.", ["开朗", "吵闹", "舒适", "卑鄙"], ["cheerful", "noisy", "comfortable", "cowardly"]),
	"3-9": t("肺部检查拍了X光。", "They took an X-ray in the lung exam.", ["症状", "X光", "体检", "医生诊疗"], ["symptom", "X-ray", "checkup", "consultation"]),
	"3-10": t("他净跟别人要烟抽，脸皮真厚。", "He always cadges cigarettes — he's shameless.", ["可靠", "自尊心高", "清爽", "厚脸皮"], ["reliable", "proud", "refreshing", "shameless"]),
	"3-11": t("靠着、倚着。", "To lean against something.", ["跨过", "抱着", "倚靠", "拧"], ["step over", "hold", "lean", "twist"]),
	"3-12": t("心情变低落。", "To feel down.", ["无聊", "消沉", "过意不去", "嫌麻烦"], ["bored", "feel down", "sorry", "bothersome"]),
	"3-13": t("想起往事觉得亲切怀念。", "To feel fond nostalgia.", ["怀念", "恋慕", "向往", "感激"], ["nostalgic", "long for", "admire", "grateful"]),
	"3-14": t("说别人坏话。", "To speak ill of someone.", ["伤害", "欺负", "贬低", "背叛"], ["hurt", "bully", "disparage", "betray"]),
	"3-15": t("意见不合而争执。", "To quarrel because opinions clash.", ["欺骗", "贬低", "欺负", "争执"], ["deceive", "disparage", "bully", "quarrel"]),
	"3-16": t("在她耳边轻轻说了“我爱你”。", "He whispered 'I love you' by her ear.", ["顶撞", "低语", "跪拜", "发誓"], ["defy", "whisper", "pray", "vow"]),
	"3-17": t("出了麻烦问题，必须好好想着解决。", "A messy problem came up and must be thought through.", ["可惜", "不得要领", "难看", "麻烦棘手"], ["a pity", "clumsy", "unseemly", "troublesome"]),
	"3-18": t("今天客人很多，忙乱的一天。", "Lots of customers today — a hectic day.", ["粗暴", "吵", "忙乱", "平静"], ["rough", "noisy", "hectic", "calm"]),
	"3-19": t("好吃，但天天吃也会腻。", "It's tasty, but you get tired of it every day.", ["吃腻", "吃惊", "慌张", "着急"], ["get tired of", "be amazed", "panic", "fret"]),
	"3-20": t("牙疼还忍着继续干活。", "My tooth hurt but I bore it and kept working.", ["闷着", "沉默", "开玩笑", "忍住"], ["shut in", "stay silent", "fool around", "endure"]),
	"3-21": t("大雨过后迎来清爽的早晨。", "After the storm came a refreshing morning.", ["落榜后心情清爽", "雨后清爽的早晨", "爱喝酒的清爽男性", "清爽的饭菜"], ["failed exams feel refreshing", "a refreshing morning", "a loud refreshing man", "a refreshing meal"]),
	"3-22": t("她总是偷别人点子，是个卑鄙的人。", "She always steals ideas — she's cowardly/underhanded.", ["偷点子很卑鄙", "穿卑鄙的衣服", "迟到会被当成卑鄙", "最近卑鄙的措辞很多"], ["steals ideas, underhanded", "wears underhanded clothes", "lateness looks underhanded", "underhanded wording"]),
	"3-23": t("小儿子长成了可靠的青年。", "My little son has grown into a dependable young man.", ["帅气又礼貌可靠", "买可靠的车", "院子里有可靠的树", "儿子长成可靠青年"], ["handsome and polite", "buy a reliable car", "a reliable tree", "grew into a reliable youth"]),
	"3-24": t("他很会抓要领，所以一路升职。", "He's good at the knack of things, so he kept getting promoted.", ["衣服要领好", "手的要领好", "会来事所以升职", "小猫要领好"], ["good at clothes", "good with hands", "street-smart so he rose", "the kitten is savvy"]),
	"3-25": t("厚着脸皮拜托您送我去车站，不好意思。", "It's shameless, but could you drive me to the station?", ["夏天夜晚厚脸皮", "厚脸皮百科", "音量厚脸皮", "厚着脸皮拜托"], ["shameless summer nights", "shameless encyclopedia", "shameless volume", "a shameless favor"]),
	"4-1": t("犯了法的议员不久就会被逮捕吧。", "That law-breaking assemblyman will be arrested before long.", ["不断", "已经", "充其量", "近日"], ["constantly", "already", "at most", "soon"]),
	"4-2": t("随着时间过去，疼痛渐渐消失了。", "As time passed the pain gradually faded.", ["充足", "渐渐", "相对", "仍然"], ["amply", "gradually", "comparatively", "still"]),
	"4-3": t("我公司终于成功开发了新产品。", "Our company finally succeeded in developing a new product.", ["终于", "不小心", "某天", "说不定"], ["at last", "unintentionally", "someday", "maybe"]),
	"4-4": t("那个艺人出事以后完全不上电视了。", "That celebrity hasn't appeared on TV at all since the incident.", ["反正", "非常", "并不", "一概／完全"], ["anyway", "very", "not particularly", "entirely"]),
	"4-5": t("吃饭前先点杯啤酒吧。", "For now let's order a beer before the food.", ["照旧", "先暂且", "刚才", "不由得"], ["as usual", "for the time being", "just now", "unconsciously"]),
	"4-6": t("奥运会明天终于开幕。", "The Olympics finally open tomorrow.", ["事先", "终于要", "屡次", "一下子"], ["in advance", "at last (imminent)", "repeatedly", "smoothly"]),
	"4-7": t("他很固执，一旦决定做就绝不会停。", "He's stubborn: once he decides, he never quits.", ["暂且", "不知为何", "一旦", "马上"], ["for now", "somehow", "once", "right away"]),
	"4-8": t("热门公寓一开卖转眼就卖光了。", "The popular condos sold out in no time.", ["不久", "转眼", "早就", "好容易"], ["before long", "in an instant", "long since", "finally"]),
	"4-9": t("怕被人看见，悄悄把信交给了田中。", "I secretly handed Tanaka the letter so no one would see.", ["正好", "满满", "悄悄", "仔细"], ["exactly", "packed", "secretly", "thoroughly"]),
	"4-10": t("比赛马上开始。", "The match is about to start.", ["早就", "突然", "不久", "频繁"], ["long ago", "suddenly", "soon", "frequently"]),
	"4-11": t("塞得满满的样子。", "Packed tightly.", ["渐渐", "一排", "满满当当", "大大地"], ["gradually", "in a row", "packed full", "greatly"]),
	"4-12": t("反复做同样的事。", "Doing the same thing over and over.", ["频繁地", "早就", "突然", "立即"], ["repeatedly", "long since", "suddenly", "immediately"]),
	"4-13": t("稍微、有点。", "A little; somewhat.", ["相当", "比较", "多少", "相对"], ["considerably", "rather", "somewhat", "comparatively"]),
	"4-14": t("很多、充分。", "A lot; plenty.", ["多多地", "一下子", "更加", "更加一层"], ["lots", "with a jump", "more", "even more"]),
	"4-15": t("下决心去做的样子。", "Doing something resolutely.", ["不由得", "一口气", "横下心", "尽情"], ["unconsciously", "in one go", "resolutely", "to one's heart's content"]),
	"4-16": t("那起事故快满一年了。", "It's almost a year since that accident.", ["不断", "早晚", "仅仅", "不久"], ["constantly", "sooner or later", "mere", "soon"]),
	"4-17": t("本不该说，却不小心把真话讲了出来。", "I didn't mean to, but I accidentally told the truth.", ["反正", "不小心", "实在", "不巧"], ["anyway", "inadvertently", "truly", "unfortunately"]),
	"4-18": t("车里汽油还很充足。", "The car still has plenty of gas.", ["比较", "姑且", "多少", "充分"], ["comparatively", "for now", "somewhat", "plenty"]),
	"4-19": t("又不好吃又贵，那种餐厅再也不去了。", "It wasn't very good and it was expensive, so I won't go back.", ["并不怎么", "究竟", "彻底", "反正"], ["not that much", "as expected", "to the end", "anyway"]),
	"4-20": t("她老早就离婚了。", "She got divorced a long time ago.", ["早就", "难道", "一旦", "看来"], ["long since", "no way", "once", "apparently"]),
	"4-21": t("她居然其实是男的，简直不敢相信。", "I can't believe she was actually a man.", ["狗聪明得像人", "她居然是男的", "那正是我想说的", "今天居然有工作"], ["the dog is as smart as a person", "no way she was a man", "that's exactly what I meant", "I have work today, no way"]),
	"4-22": t("突然这么说，一时也决定不了。", "I can't decide just like that when you spring it on me.", ["突然说也一下子决定不了", "演出7点突然开始", "突然有100人", "请突然过来"], ["can't decide on the spot", "the show suddenly started at 7", "suddenly 100 people", "please come suddenly"]),
	"4-23": t("与其到处修，不如干脆把房子重建。", "Rather than patching it everywhere, we might as well rebuild.", ["披萨还没来", "干脆重建房子", "加酒更好吃", "水一口气喝完"], ["the pizza hasn't come", "might as well rebuild", "sake made it tastier", "gulped the water"]),
	"4-24": t("妈妈老是发牢骚。", "Mom is always complaining.", ["票常常卖光", "吉他常常变好", "妈妈常常抱怨", "单词常常记住了"], ["tickets often sell out", "guitar often improved", "mom constantly nags", "I often memorized words"]),
	"4-25": t("与其说是猴子，那只猩猩更接近人。", "That chimp is closer to a human than to a monkey.", ["与其说猴不如说接近人", "训练让身体被锻炼", "社长很有钱", "大楼已经完工"], ["more human than monkey", "training built the body", "the president has money", "the tower is finished"]),
	"5-21": t("购物金额合计三万日元。", "The purchase comes to 30,000 yen in total.", ["做了新工作的合计", "学习的合计吃点心", "和其他队合计练习", "购物合计三万"], ["totaled the new job", "total of study", "practiced in total", "the bill totals 30,000"]),
	"5-22": t("他是做蛋包饭的高手。", "He's a master at making omelets.", ["古典名人", "做蛋包饭的名人", "申请书上写了名人", "职场名人关系不好"], ["a classical master", "an omelet master", "wrote a master on the form", "workplace master relations"]),
	"5-23": t("她对下属等下级非常严格。", "She's very strict with subordinates.", ["对下级很严", "眼睛下面有痣", "从最高层看下面发晕", "在百货楼下购物"], ["strict with juniors", "a mole under the eye", "looking down from the top", "shopped downstairs"]),
	"5-24": t("那部电影里她的角色很不起眼。", "Her role in that film was very low-key.", ["角色很朴素不起眼", "昨晚地震很朴素", "汤很淡很朴素", "山上空气很朴素"], ["a plain unnoticed role", "last night's quake was plain", "the soup is plain", "the air is plain"]),
	"5-25": t("凡事都有里外两面。", "Everything has two sides.", ["家里挤满物事", "为了物事拼命学习", "物事的作者是人气作家", "凡事都有表里"], ["the house overflows with things", "studied for things", "the author of things", "everything has two sides"]),
	"6-1": t("看您很忙，改日再来。", "You seem busy, so I'll come again another day.", ["全部", "改日", "重新", "挪开"], ["all", "another day", "anew", "move aside"]),
	"6-2": t("哥哥在媒体相关的公司上班。", "My brother works at a media company.", ["酒店前台", "媒体", "商务", "专业"], ["hotel front", "mass media", "business", "pro"]),
	"6-3": t("我对鸡蛋过敏，所以尽量不吃含蛋的东西。", "I'm allergic to eggs, so I avoid foods that contain them.", ["能量", "潮流", "超过", "过敏"], ["energy", "boom", "over", "allergy"]),
	"6-4": t("她房间脏得让我目瞪口呆。", "Her room was so dirty I was stunned.", ["吃腻", "惊呆", "放弃", "被腻烦"], ["tired of", "appalled", "give up", "be tired of"]),
	"6-5": t("没事，这不过是普通感冒，过一阵就好。", "It's all right — it's just a simple cold.", ["仅仅是", "只是", "意外地", "没想到"], ["mere", "just", "unexpectedly", "surprisingly"]),
	"6-6": t("用信用卡积分换了商品券。", "I used credit-card points to get gift certificates.", ["积分", "平衡", "服务", "预约"], ["points", "balance", "service", "appointment"]),
	"6-7": t("他的世界纪录时隔十年被打破了。", "His world record was broken after ten years.", ["被挪开", "被打破", "被撕碎", "被改正"], ["moved aside", "broken", "torn", "revised"]),
	"6-8": t("这是先前会议上决定的。", "This was decided at the earlier meeting.", ["主要", "实在", "第一", "先前"], ["mainly", "truly", "firstly", "previously"]),
	"6-9": t("电脑中了病毒，数据全没了。", "The computer got a virus and all the data vanished.", ["病", "病毒", "流感", "伤"], ["illness", "virus", "flu", "wound"]),
	"6-10": t("挡路了，请把这把椅子挪一下。", "It's in the way — please move this chair.", ["悬挂", "摔倒", "埋", "挪开"], ["hang", "fall", "bury", "move aside"]),
	"6-11": t("由人手制作。", "Made by human hands.", ["人手", "复制", "人工", "打字"], ["manpower", "copy", "artificial", "type"]),
	"6-12": t("事情推进的速度。", "The speed at which things proceed.", ["预约", "平衡", "高峰", "节奏"], ["appointment", "balance", "rush", "tempo"]),
	"6-13": t("超市等付款的地方。", "The place you pay in a supermarket.", ["收银台", "讨论课", "关掉", "专柜"], ["register", "seminar", "off", "corner"]),
	"6-14": t("用手指撕成小块。", "Tearing into small pieces with the fingers.", ["悬挂", "撕碎", "吮吸", "洒出"], ["hang", "tear off", "suck", "spill"]),
	"6-15": t("数量或时间超过限度。", "Going over a limit of amount or time.", ["专业", "通缩", "超时超额", "通胀"], ["pro", "deflation", "over", "inflation"]),
	"6-16": t("从前这一带有公园。", "There used to be a park around here.", ["第一", "曾经", "先前", "最先"], ["firstly", "formerly", "earlier", "first of all"]),
	"6-17": t("未经允许请不要用别人的东西。", "Don't use other people's things without permission.", ["最先", "勉强", "意外", "擅自"], ["first", "forcibly", "unexpectedly", "without leave"]),
	"6-18": t("今天考试比预想难。", "Today's exam was harder than expected.", ["仅仅", "实在", "没想到", "多余"], ["merely", "truly", "unexpectedly", "extra"]),
	"6-19": t("把今天的安排挪到了明天。", "I shifted today's plans to tomorrow.", ["错开", "带来", "埋了", "泄漏"], ["shift", "bring about", "bury", "leak"]),
	"6-20": t("她进公司第二年就结婚了。", "She got married the year after joining the company.", ["两三年", "过了几年", "第二年", "某一年"], ["in a few years", "after some years", "the next year", "one year"]),
	"6-21": t("长颈鹿的特征是脖子长。", "Giraffes are characterized by long necks.", ["冰箱有节能特征", "长颈鹿脖子长是特征", "东京人口特征多", "不能特征地对待他"], ["energy-saving feature", "long neck is the trait", "Tokyo's population is trait-many", "don't treat him as a trait"]),
	"6-22": t("他被老师提醒后改正了态度。", "After the teacher warned him, he changed his attitude.", ["改正态度", "换频道", "改了味道", "核对答案"], ["reformed his attitude", "change the channel", "changed the flavor", "checked the answer"]),
	"6-23": t("感冒嗓子疼，所以含着糖。", "My throat hurt from a cold, so I sucked on a candy.", ["雨突然吮吸", "吮吸拉面", "把信吮吸扔掉", "含着糖"], ["rain sucked suddenly", "slurped ramen", "sucked the letter", "sucked a candy"]),
	"6-24": t("想不出答案，不禁哼哼起来。", "I groaned, unable to find the answer.", ["宝宝哼哼睡着", "雷在哼", "想不出答案哼哼", "被爸爸大声哼"], ["the baby hummed asleep", "thunder groaned", "groaned over the problem", "dad groaned at me"]),
	"6-25": t("打了流感疫苗。", "I got a flu vaccine.", ["疫苗不足皮肤变差", "他充满疫苗", "电脑感染疫苗", "打流感疫苗"], ["vaccine shortage ruined skin", "he's full of vaccine", "the PC caught a vaccine", "got a flu shot"]),
	"7-1": t("无意识地咬起指甲。", "I chew my nails unconsciously.", ["不", "无", "非", "未"], ["un-", "without", "non-", "not yet"]),
	"7-2": t("交了大学入学费。", "I paid the university entrance fee.", ["金", "费", "代", "租"], ["money", "fee", "charge", "fare"]),
	"7-3": t("超时劳动换句话说就是加班。", "Overtime work is another way of saying extra hours.", ["其他", "外", "超", "后"], ["other", "outside", "over / extra", "after"]),
	"7-4": t("世界和平是全人类共同的梦想。", "Peace is a dream shared by all humankind.", ["各", "总", "全", "合"], ["each", "total", "all", "combine"]),
	"7-5": t("观众倾听长笛的精彩演奏。", "The audience listened to a masterful flute performance.", ["名", "高", "有", "超"], ["masterful", "high", "famous", "super"]),
	"7-6": t("她出了名校，自尊心很高。", "She went to a top university and has a lot of pride.", ["轻", "暗", "高", "多"], ["light", "dark", "high", "many"]),
	"7-7": t("大学之后就没见过，一晃20年。", "I haven't seen him since university — it's been 20 years.", ["眼", "隔", "每", "时隔"], ["eye", "every other", "each", "for the first time in"]),
	"7-8": t("许可证不能补发，请别弄丢。", "Permits cannot be reissued, so don't lose yours.", ["发售", "销售", "生产", "签发"], ["release", "sell", "produce", "issue"]),
	"7-9": t("随口答应了，其实不该接下。", "I said OK lightly, but I shouldn't have taken it on.", ["轻松", "沉重", "高", "低"], ["light", "heavy", "high", "low"]),
	"7-10": t("这个过了赏味期限，还能吃吗？", "This is past its best-before date — is it still okay?", ["过期", "没了", "挂着", "取下"], ["expired", "gone", "hanging", "taken off"]),
	"7-11": t("看东西时眼睛的神情。", "The look in someone's eyes.", ["眼风", "眼神", "眼用法", "眼附近"], ["eye manner", "look in the eyes", "eye usage", "around the eyes"]),
	"7-12": t("知识习惯变成自己的本事。", "Knowledge or habits becoming second nature.", ["心里掌握", "身上掌握", "气上掌握", "真正掌握"], ["stick in the heart", "stick to the body", "stick to the spirit", "make it one's own"]),
	"7-13": t("传达意志感情的身体动作。", "Body movements that convey feeling.", ["身势", "体势", "身用法", "体用法"], ["gesture", "body style", "body use", "physique use"]),
	"7-14": t("人突然情绪化地爆发。", "Suddenly snapping in anger.", ["勒紧", "爆发", "训练", "记账"], ["tighten", "snap / lose it", "train", "charge"]),
	"7-15": t("季节交替的时候。", "The turning point between seasons.", ["换季间隙", "换季时节", "变化时", "变化间"], ["between seasons", "the turn of the seasons", "change time", "change interval"]),
	"7-16": t("飞机每隔一小时一班。", "Planes leave every other hour.", ["用", "每", "以内", "以上"], ["by", "every", "within", "or more"]),
	"7-17": t("高水平的大学不容易进。", "A high-level university isn't easy to get into.", ["学费贵", "难", "高级", "豪华"], ["expensive fees", "difficult", "high-class", "luxurious"]),
	"7-18": t("从模拟考结果看，合格没问题。", "Judging from the mock exam, passing is a sure thing.", ["估计", "看法", "合计", "决心"], ["estimate", "viewpoint", "total", "decide"]),
	"7-19": t("药劲过了，牙又开始疼。", "The medicine wore off and the tooth started hurting again.", ["得了", "剩下", "失效", "结束"], ["caught", "left over", "ran out", "finished"]),
	"7-20": t("学生时代没钱，日子过得很紧。", "As a student I had no money and every day was hard.", ["激烈", "穷", "辛苦", "无聊"], ["intense", "poor", "tough", "dull"]),
	"7-21": t("新干线以前被称为“梦想的超特快”。", "The shinkansen was once called the 'dream super express.'", ["别吃超卡路里", "她是超女演员", "超气压天气好", "梦想的超特快"], ["don't eat super-calories", "a super actress", "super pressure", "the dream super express"]),
	"7-22": t("地铁票价涨了。", "The subway fare went up.", ["去美国的运费很贵", "修车费多少", "地铁票价涨了", "电车费比以前贵"], ["shipping to America is costly", "repair charge", "subway fare rose", "train fare costs more"]),
	"7-23": t("这家店的乌冬是关东风，汤色发黑。", "This shop's udon is Kanto-style, so the broth is dark.", ["关东风的汤", "日常风遛狗", "衣服看起来风不好", "有立体风的画"], ["Kanto-style broth", "walk the dog everyday-style", "the costume looks bad", "a 3D-style painting"]),
	"7-24": t("这台机器每卖出一台就有很多利润。", "This machine makes a large profit each time one is sold.", ["每天洗澡", "连皮吃苹果", "每卖一台就赚钱", "按老师说的学习"], ["bathe every day", "eat apples peel and all", "profit per unit sold", "study as the teacher said"]),
	"7-25": t("他说话的神情活像他父亲。", "The way he talks is just like his father.", ["说话神情像父亲", "刚吃完饭去哪", "刚开始用电脑很难", "刚做好"], ["his manner of speaking", "just after eating", "hard when newly using a PC", "freshly made"]),
	"8-1": t("车送去修了，想去也没交通工具。", "The car's in the shop, so I have no way to get there.", ["手", "脚／交通", "眼", "头"], ["hand", "wheels / transport", "eye", "head"]),
	"8-2": t("这张桌子稍加修理就能用。", "This desk will be fine if we fix it up a little.", ["出手", "加把手", "稍加修理", "伸手"], ["put out a hand", "add a handle", "fix up", "reach out"]),
	"8-3": t("排了三小时队，终于到手了。", "I lined up three hours and finally got it.", ["入手", "伸手", "出手", "松手"], ["obtain", "reach", "start", "let go"]),
	"8-4": t("出门兜风忘了东西，中途折回家。", "We went for a drive, forgot something, and turned back.", ["取回", "追回", "坐回", "折回"], ["take back", "chase back", "ride back", "turn back"]),
	"8-5": t("上幼儿园前的孩子最费事。", "Kids before kindergarten take the most looking after.", ["举到手上", "手能拿", "转到手上", "费事"], ["raise in the hand", "the hand takes", "goes around the hand", "takes a lot of work"]),
	"8-6": t("孩子收到礼物高兴的样子浮现在眼前。", "I can picture the child delighting in the present.", ["显眼", "沁入", "挂上", "浮现"], ["catch the eye", "soak in", "get involved", "come to mind"]),
	"8-7": t("15岁就上奥运会，真了不起。", "Making the Olympics at 15 is really something.", ["了不起", "正经", "理所当然", "路子广"], ["impressive", "decent", "natural", "well connected"]),
	"8-8": t("你说我那么说过，可我没那个印象。", "You say I said that, but I have no recollection.", ["想法", "心情", "思念", "记得"], ["thought", "feeling", "thoughts", "memory"]),
	"8-9": t("我们家没那么宽裕，买不起那么贵的。", "We don't have that kind of spare money.", ["准备", "费用", "余裕", "金额"], ["preparation", "cost", "leeway", "amount"]),
	"8-10": t("被人批评，听着心里难受。", "It's painful to hear yourself criticized.", ["耳朵严", "耳背", "刺耳／心里难受", "耳朵硬"], ["harsh ears", "hard of hearing", "hits a nerve", "stubborn ears"]),
	"8-11": t("连细节都操心。", "Paying attention even to small things.", ["跟上", "散开", "拘泥／讲究", "能行"], ["keep up", "expose", "be particular", "can drink/go"]),
	"8-12": t("运气好。", "To be in luck.", ["有效", "能喝", "写着", "走运"], ["working", "can handle drinks", "writing", "lucky"]),
	"8-13": t("偷偷做不让人发现。", "Doing something on the sly.", ["避开别人眼睛", "偷脸", "没脚", "没眼光"], ["steal a look / do unseen", "steal a face", "no legs", "no eye for"]),
	"8-14": t("正经、没什么古怪的样子。", "Proper; nothing odd about it.", ["正经", "还算好", "可惜", "理所当然"], ["decent", "better than nothing", "wasteful", "natural"]),
	"8-15": t("把取消的票款退回来了。", "I got a refund for the canceled ticket.", ["支付了", "退还了", "折回了", "垫付了"], ["paid", "refunded", "turned back", "paid on behalf"]),
	"8-16": t("他说话粗鲁，人却很温柔。", "His language is rough, but he's kind.", ["身子坏", "没身子", "嘴损", "没嘴"], ["unhealthy", "no body", "sharp-tongued", "speechless"]),
	"8-17": t("她做饭越来越好了。", "She's gotten better at cooking.", ["抬手", "抬嘴", "手艺提高", "抬脸"], ["raised a hand", "raised her mouth", "improved her skill", "raised her face"]),
	"8-18": t("有空，所以去集会露了个面。", "I had a spare moment so I showed my face at the meeting.", ["露脸", "有面子", "来劲", "机灵"], ["showed up", "had influence", "felt like it", "was thoughtful"]),
	"8-19": t("东西很重，能帮一下忙吗？", "It's heavy — could you give me a hand?", ["帮忙", "费心", "露脸", "回头"], ["lend a hand", "be considerate", "show up", "turn your head"]),
	"8-20": t("都说那家牙医技术很好。", "That dentist has a reputation for being skillful.", ["右边胳膊好", "长袖胳膊好", "胳膊好的生活", "牙医技术好"], ["right arm is good", "long sleeves are good", "a good-arm life", "a skillful dentist"]),
	"8-21": t("尽偷懒瞎玩，迟早要吃苦头。", "If you just slack off, you'll be in for it.", ["被夸后很风光", "尽玩会倒大霉", "淘气真倒霉", "碰上吃的机会"], ["looks cool being praised", "you'll pay for slacking", "the prank was unlucky", "got a chance to eat"]),
	"8-22": t("同样的东西买两件就给打折了。", "They gave me a discount when I bought two.", ["衣服打折变得好穿", "买两件给打折", "把大石头打折搬走", "用词典打折查汉字"], ["discounted clothes fit better", "bought two and got a discount", "split a rock and carried it", "looked up kanji at a discount"]),
	"8-23": t("电车费我先垫上了。", "I paid the train fare for now.", ["改了公司体制", "从银行垫了工资", "车费我垫付了", "门口有人垫着"], ["reorganized the company", "advanced the salary", "I covered the fare", "someone is standing in the entrance"]),
	"8-24": t("她嘴不严，别把秘密告诉她。", "She can't keep a secret, so don't tell her private things.", ["嘴不严别说秘密", "嘴轻所以吃点心", "他只说自己的事", "这酒喝完口感轻"], ["loose-lipped", "light mouth so snacks", "he only talks about himself", "the sake finishes light"]),
	"8-25": t("她嘴不严，别把秘密告诉她。", "She can't keep a secret.", ["嘴不严", "嘴轻吃点心", "只说自己", "酒后口轻"], ["can't keep secrets", "eats snacks", "talks only of himself", "light aftertaste"]),
})

KANJI_EXAM = {
	"1-1": t("此处禁止停车。", "No parking here.", ["住车", "调车", "停车", "乘车"], ["live-car", "adjust-car", "parking", "boarding"]),
	"1-2": t("口香糖请包在纸里再扔掉。", "Wrap chewing gum in paper before throwing it away.", ["夹着", "包着", "叠着", "主动"], ["sandwich", "wrap", "fold", "willingly"]),
	"1-3": t("外汇窗口在2楼。", "The foreign-exchange counter is on the second floor.", ["换衣", "试", "外汇", "兑换"], ["change clothes", "try", "exchange", "change money"]),
	"1-4": t("吸烟席在那边。", "The smoking seats are over there.", ["禁年席", "禁烟席", "吸烟席", "吃烟席"], ["year-ban", "no-smoking", "smoking seats", "eat-smoke"]),
	"1-5": t("食堂还在准备中。", "The cafeteria is still getting ready.", ["整备", "营业", "停业", "准备"], ["maintenance", "open", "closed", "preparing"]),
	"1-6": t("去百货店的关门甩卖。", "I'm going to the department store's closing sale.", ["关门", "开店", "祭典", "晴天"], ["closing", "opening", "festival", "fine weather"]),
	"1-7": t("做医疗相关的工作。", "I do medical-related work.", ["治疗", "医疗", "肥料", "诊疗"], ["treatment", "medical care", "fertilizer", "consultation"]),
	"1-8": t("叫救护车请打119。", "Call 119 for an ambulance.", ["救急", "供给", "究京", "京京"], ["emergency", "supply", "wrong reading", "wrong reading"]),
	"1-9": t("富士山下了初雪。", "The first snow fell on Mt. Fuji.", ["始雪", "初雪", "初雪（音错）", "初雪（音错）"], ["first-start snow", "first snow", "wrong reading", "wrong reading"]),
	"1-10": t("用机器也能精算。", "You can also settle the fare by machine.", ["销算", "解散", "精算", "计算"], ["sales calc", "dissolve", "fare adjustment", "calculate"]),
	"1-11": t("这部电梯限乘9人。", "This elevator's capacity is nine people.", ["办事员", "乘员", "店员", "定员"], ["clerk", "crew", "clerk", "capacity"]),
	"1-12": t("洗手间正在清扫。", "The restroom is being cleaned.", ["清归", "清扫", "精扫", "精归"], ["wrong kanji", "cleaning", "wrong kanji", "wrong kanji"]),
	"1-13": t("地面数字广播是什么？", "What is terrestrial digital broadcasting?", ["邮送", "包送", "放送", "发送"], ["mail", "pack-send", "broadcast", "dispatch"]),
	"1-14": t("这封信请用快递。", "Please send this letter by express.", ["快递", "投递", "发达", "朋友"], ["express mail", "delivery", "development", "friend"]),
	"1-15": t("坐机场大巴去了机场。", "I took the limousine bus to the airport.", ["机场", "航空", "港口", "高中"], ["airport", "aviation", "port", "high school"]),
	"1-16": t("能帮我换开一万日元纸币吗？", "Could you break a 10,000-yen bill?", ["符", "纸币", "附", "段"], ["token", "bill", "attach", "step"]),
	"1-17": t("从日本出国旅行1964年自由化了。", "Overseas travel from Japan was liberalized in 1964.", ["科", "化", "案", "席"], ["department", "-ize", "plan", "seat"]),
	"1-18": t("再次办理入境手续。", "Go through entry procedures again.", ["改", "际", "御", "再"], ["revise", "occasion", "honorific", "again"]),
	"1-19": t("这路公交车先付车费。", "On this bus you pay the fare first.", ["代", "料", "费", "贷"], ["substitute", "fee", "fare", "lend"]),
	"1-20": t("1号车厢是禁烟车厢。", "Car 1 is a no-smoking car.", ["号", "两", "番", "层"], ["number", "both", "number", "floor"]),
	"1-21-25": t("看完的报纸会再生为包装纸、卫生纸。不当垃圾扔掉、总是注意回收的人在增加。", "Finished newspapers are recycled into wrapping paper and tissue. More people always take care not to throw them away as trash."),
	"2-1": t("这种天气登山可行吗？", "Is climbing possible in this weather?", ["彼の", "苦能", "昨日", "可能"], ["his", "wrong", "yesterday", "possible"]),
	"2-2": t("办理退票。", "Get a refund on a ticket.", ["退还", "换回", "卸下", "剩下"], ["refund", "exchange back", "unload", "leave"]),
	"2-3": t("这个记号表示取消。", "This mark means cancellation.", ["印章", "记号", "表面", "印刷"], ["seal", "mark", "front", "printing"]),
	"2-4": t("房间中央有桌子。", "There's a table in the center of the room.", ["中央", "中心", "中影", "正中间"], ["center", "core", "wrong", "middle"]),
	"2-5": t("最近年幼孩子的事故在增加。", "Accidents involving small children are increasing.", ["痛切", "直截", "年幼", "幼小（音错）"], ["painful", "frank", "young", "wrong reading"]),
	"2-6": t("请打印并放大复印。", "Please print and enlarge the copy.", ["放大", "广大", "特大", "增大"], ["enlarge", "vast", "extra large", "increase"]),
	"2-7": t("选定文字再转换。", "Select the text and convert it.", ["编辑", "变更", "偿还", "转换"], ["edit", "change", "repay", "convert"]),
	"2-8": t("这个时期湿度很高。", "Humidity is high at this time of year.", ["秩序", "湿度", "必度", "一度"], ["order", "humidity", "wrong", "wrong"]),
	"2-9": t("小区阳台上晒着被子。", "Futons are airing on the danchi balcony.", ["毯子", "地毯", "被子", "枕头"], ["blanket", "carpet", "futon", "pillow"]),
	"2-10": t("数复印纸的张数。", "Count the sheets of copy paper.", ["凑齐", "数（音错）", "空着", "数"], ["arrange", "wrong reading", "empty", "count"]),
	"2-11": t("本日营业结束了。", "We are closed for the day.", ["终了", "修了", "完了", "未了"], ["ended", "completed a course", "finished", "unfinished"]),
	"2-12": t("那件事还没谈完，先保留。", "That matter isn't settled, so it's on hold.", ["保留", "保存", "保湿", "保温"], ["pending", "save", "moisturize", "keep warm"]),
	"2-13": t("日本年末会大扫除。", "In Japan we do a big year-end cleaning.", ["清扫", "除湿", "扫除", "洗濯"], ["cleaning", "dehumidify", "housecleaning", "laundry"]),
	"2-14": t("这一带道路也整备得不错了。", "The roads around here have been improved a lot.", ["常备", "设备", "准备", "整备"], ["standing stock", "equipment", "prepare", "maintain/improve"]),
	"2-15": t("订立今年的目标。", "Set this year's goals.", ["目标", "目表", "木标", "木表"], ["goal", "wrong", "wrong", "wrong"]),
	"2-16": t("这本书由上中下三卷构成。", "This book consists of three volumes.", ["券", "卷", "件", "张"], ["ticket", "volume", "matter", "sheet"]),
	"2-17": t("用量杯量米。", "Measure the rice with a cup.", ["能", "计", "类", "量"], ["ability", "meter", "kind", "quantity"]),
	"2-18": t("记住日本式的寒暄和礼仪。", "Learn Japanese-style greetings and manners.", ["修", "带", "玉", "式"], ["study", "belt", "jewel", "style"]),
	"2-19": t("和邮件一起发送画像。", "Send an image with the email.", ["历", "机", "像", "表"], ["history", "machine", "image", "chart"]),
	"2-20": t("读短篇小说。", "Read a short story.", ["编", "片", "期", "数"], ["compile", "piece", "period", "number"]),
	"2-21": t("今早因地震停电了。", "There was a power cut this morning because of the quake.", ["止", "停", "不", "满"], ["stop", "cut/stop", "un-", "full"]),
	"2-22-25": t("日本到处都有自动售货机。外国人常说，不满20岁禁止的东西也能自由买到，真不可思议。", "Japan has vending machines everywhere. Foreigners often say it's strange you can freely buy things banned for under-20s."),
	"3-1": t("收据。", "A receipt.", ["领主", "领收（音错）", "料主", "领收"], ["wrong", "wrong reading", "wrong", "receipt"]),
	"3-2": t("写给某某殿。", "The honorific 殿 after a name.", ["さま", "殿", "君", "电"], ["sama", "dono", "kun", "electricity"]),
	"3-3": t("号码。", "A number.", ["番号（音错）", "番号（音错）", "番号（音错）", "番号"], ["wrong", "wrong", "wrong", "number"]),
	"3-4": t("金额。", "An amount of money.", ["价钱", "金额", "价格", "费用"], ["price", "amount", "price", "fee"]),
	"3-5": t("从千叶来的田畑先生，您的同伴在等您。", "Mr. Tabata from Chiba, your companion is waiting.", ["出", "奇", "年", "光临"], ["put out", "strange", "year", "coming (honorific)"]),
	"3-6": t("填海建造机场。", "Reclaim the sea and build an airport.", ["埋（音错）", "梦填", "填埋", "滑填"], ["wrong", "wrong", "reclaim/fill", "wrong"]),
	"3-7": t("这份资料请务必带来。", "Be sure to bring this material.", ["必（音错）", "务必", "音错", "音错"], ["wrong", "without fail", "wrong", "wrong"]),
	"3-8": t("照片和实物稍有不同。", "The photo is a little different from the real thing.", ["重叠", "伴随", "不同", "说"], ["overlap", "accompany", "differ", "say"]),
	"3-9": t("男女平等地给予工作机会。", "Give men and women equal job opportunities.", ["平等", "平等（音错）", "音错", "音错"], ["equality", "wrong", "wrong", "wrong"]),
	"3-10": t("播报寻人启事。", "We will make a lost-child announcement.", ["名片", "名子", "走失儿童", "音错"], ["business card", "wrong", "lost child", "wrong"]),
	"3-11": t("各位有关人员：服务器将停止。", "To all concerned: the server will be down.", ["客位", "各位", "名位", "角位"], ["guest rank", "everyone", "name rank", "corner rank"]),
	"3-12": t("请协助填写问卷。", "Please cooperate with the questionnaire.", ["共力", "强力", "协力", "助力"], ["joint force", "powerful", "cooperation", "help"]),
	"3-13": t("正月很多人去寺庙神社参拜。", "At New Year many people visit temples and shrines.", ["参拜", "迷路", "谢绝", "周围"], ["visit to pray", "get lost", "refuse", "around"]),
	"3-14": t("这张卡的有效期限是一年。", "This card is valid for one year.", ["发行", "流行", "用效", "有效"], ["issue", "popular", "wrong", "valid"]),
	"3-15": t("训练因雨推迟到下周。", "Training was postponed to next week because of rain.", ["延期", "震", "平", "系"], ["extended/postponed", "quake", "flat", "tie"]),
	"3-16": t("把信拆开。", "Open the letter.", ["记", "顶", "封", "叶"], ["write", "receive", "seal", "leaf"]),
	"3-17": t("考试当天车站很挤，回程票最好也买好。", "Stations are crowded on exam day, so buy the return ticket too.", ["当", "平", "本", "现"], ["that very", "ordinary", "this", "current"]),
	"3-18": t("今早冷得水管结冰了。", "The pipes froze in this morning's cold.", ["断", "枝", "管", "藏"], ["cut", "branch", "pipe", "store"]),
	"3-19": t("这是瑞士制造的表。", "This watch is Swiss-made.", ["个", "作", "整", "制"], ["piece", "make", "arrange", "manufactured"]),
	"3-20": t("便利店问“要装袋吗”，我说不用。", "The clerk asked if I wanted a bag; I said no.", ["容", "袋", "装", "衣"], ["container", "bag", "pack", "clothes"]),
	"3-21": t("拿起电话听筒。", "Pick up the receiver.", ["机", "器", "记", "气"], ["machine", "device", "record", "spirit"]),
	"3-22": t("您的信用卡额度是80万日元。", "Your credit limit is 800,000 yen.", ["额", "料", "代", "金"], ["amount", "fee", "charge", "money"]),
	"4-1": t("他主张自己没有错。", "He insisted he wasn't wrong.", ["抽象", "出差", "受听", "主张"], ["abstract", "business trip", "wrong", "insist"]),
	"4-2": t("百货店挤满买岁暮礼的人。", "The department store was packed with year-end gift shoppers.", ["岁暮", "岁暮（音错）", "年暮", "压岁钱"], ["year-end gift", "wrong reading", "year-end", "New Year money"]),
	"4-3": t("今天承蒙招待，非常感谢。", "Thank you for inviting me today.", ["音错", "招待", "音错", "音错"], ["wrong", "invite", "wrong", "wrong"]),
	"4-4": t("失去信用就做不成生意。", "You can't do business once you lose trust.", ["失去", "养", "应付", "补充"], ["lose", "raise", "treat", "supplement"]),
	"4-5": t("想住在被花和绿环绕的家里。", "I want to live in a house surrounded by flowers and greenery.", ["被眷顾", "被包着", "被环绕", "被经营"], ["blessed", "wrapped", "surrounded", "run"]),
	"4-6": t("互相注意身体，一起加油。", "Let's take care of ourselves and do our best.", ["课题", "互相", "颚", "高"], ["topic", "each other", "chin", "high"]),
	"4-7": t("希望孩子天真率直地成长。", "I want the child to grow up straightforward.", ["正直", "素直（音错）", "率直", "素直"], ["honest", "wrong", "frank", "ingenuous"]),
	"4-8": t("这首歌里包含着停止争斗的信息。", "The song carries a message to stop fighting.", ["战斗", "竞争", "争执", "口角"], ["battle", "compete", "quarrel", "row"]),
	"4-9": t("结婚以来我完全靠妻子。", "Since marrying I've come to rely entirely on my wife.", ["沉迷", "保持", "沉浸", "依靠"], ["be hooked", "keep", "immerse", "depend"]),
	"4-10": t("演讲读错汉字，丢了脸。", "I misread a kanji in the speech and was embarrassed.", ["汗", "鼾", "耻", "盘腿"], ["sweat", "snore", "shame", "sit cross-legged"]),
	"4-11": t("文化习惯因国家而异。", "Culture and customs differ by country.", ["周刊", "习惯", "主观", "周刊杂志"], ["weekly", "custom", "subjective", "weekly magazine"]),
	"4-12": t("碰头会从两点开始。", "The meeting starts at two.", ["商量碰头", "等候会合", "手头有", "掉下来会合"], ["planning meeting", "rendezvous", "happen to have", "wrong"]),
	"4-13": t("明天是节日，休息。", "Tomorrow is a holiday, so we're off.", ["节日", "察日", "际日", "祭日"], ["celebration day", "wrong", "wrong", "festival day"]),
	"4-14": t("请在这里写下工作单位和部门名。", "Write your workplace and department here.", ["部暑", "部所", "部署", "部诸"], ["wrong", "wrong", "section", "wrong"]),
	"4-15": t("小孩子规规矩矩打招呼，让我很佩服。", "I was impressed that such a small child greeted me properly.", ["喜心", "关心", "寒心", "佩服"], ["joy", "interest", "chilled", "admiration"]),
	"4-16": t("通过这场考试的人可以参加二次考试。", "Those who pass can take the second exam.", ["期", "次", "部", "助"], ["term", "second/next", "section", "help"]),
	"4-17": t("因家里的情况决定休学。", "I decided to take a leave from school for family reasons.", ["无", "退", "误", "中"], ["none", "withdraw", "error", "mid / suspend"]),
	"4-18": t("哥哥在消防署工作。", "My brother works at the fire station.", ["著", "所", "暑", "署"], ["work", "place", "hot", "government office"]),
	"4-19": t("朋友石田君来玩了。", "My friend Ishida-kun came over.", ["殿", "様", "君", "奥"], ["dono", "sama", "kun", "interior"]),
	"4-20": t("印刷年贺状。", "Print New Year's cards.", ["状", "札", "礼", "纸"], ["card/letter", "bill", "thanks", "paper"]),
	"4-21": t("托您的福，父母都健在。", "Thankfully both my parents are still living.", ["存", "健", "现", "保"], ["exist", "healthy/alive", "current", "keep"]),
	"4-22": t("听关于现代社会诸问题的演讲。", "Listen to a talk on various problems of modern society.", ["诸", "第", "总", "要"], ["various", "ordinal", "total", "essential"]),
	"4-23-25": t("哥哥老捉弄我，有时觉得可恨。但他有困难总会帮我，是个可靠的人。半年没见，很想念哥哥。", "My brother teases me and I sometimes find him hateful. But he always helps — he's reliable. I haven't seen him in half a year and I miss him."),
	"5-1": t("都说一辛苦白头发就变多。", "They say hardship brings more gray hair.", ["假发", "白毛", "白发（音错）", "白发"], ["wig", "white hair", "wrong reading", "gray hair"]),
	"5-2": t("把书放进布制包里。", "Put the books in a cloth bag.", ["无的", "菜的", "布的", "布（音错）"], ["wrong", "wrong", "cloth", "wrong"]),
	"5-3": t("地震把房子震歪了。", "The quake left the house leaning.", ["裂纹", "受伤", "倾斜", "吃惊"], ["crack", "get hurt", "tilt", "be surprised"]),
	"5-4": t("日本伴手礼送浴衣怎么样？", "How about a yukata as a souvenir from Japan?", ["浴衣", "扇子", "团扇", "茶杯"], ["yukata", "folding fan", "uchiwa", "teacup"]),
	"5-5": t("这种虫子用手指一碰就会把身体缩成一团。", "This insect curls up when you touch it.", ["摆弄", "接触（自动）", "触摸", "碰到"], ["fiddle", "come in contact", "touch", "hit"]),
	"5-6": t("回收堆在储物间里的闲置物品。", "We'll collect unused items sitting in the storeroom.", ["仓库", "物置（音错）", "物置（音错）", "储物间"], ["warehouse", "wrong", "wrong", "storeroom"]),
	"5-7": t("我是五兄妹中最小的。", "I'm the youngest of five siblings.", ["末子（音错）", "老小", "三子", "独生"], ["wrong", "youngest", "third", "only child"]),
	"5-8": t("捡拾树上的果实。", "Gather nuts/fruit from the tree.", ["果实", "叶", "子", "根"], ["fruit", "leaf", "child", "root"]),
	"5-9": t("水开了。", "The water has boiled.", ["降", "播", "沸", "鸣"], ["fall", "sow", "boil", "cry"]),
	"5-10": t("没有可以商量烦恼的人。", "I have no one to talk over my worries with.", ["烦恼", "胡乱", "愿望", "嫉妒"], ["worry", "rashly", "hope", "envy"]),
	"5-11": t("台风正在接近日本。", "The typhoon is approaching Japan.", ["最近", "接近", "近在眼前", "远近"], ["recently", "approach", "close by", "distance"]),
	"5-12": t("她是北海道出身。", "She's from Hokkaido.", ["里面", "自身", "蛋白", "出身"], ["inside", "oneself", "white meat", "birthplace"]),
	"5-13": t("不买家具，改成租赁。", "Instead of buying furniture, I'll rent it.", ["家具", "家贝", "家见", "家旦"], ["furniture", "wrong", "wrong", "wrong"]),
	"5-14": t("墙上贴着海报。", "There's a poster on the wall.", ["柱", "壁", "地板", "布"], ["pillar", "wall", "floor", "cloth"]),
	"5-15": t("请给我满满一杯水。", "A full glass of water, please.", ["一张", "一杯", "一技", "一牧"], ["one sheet", "one cupful", "one skill", "one flock"]),
	"5-16": t("受不了浓味，所以选无香料的。", "I can't stand strong smells, so I choose unscented ones.", ["无", "非", "不", "全"], ["without", "non-", "un-", "all"]),
	"5-17": t("一个月伙食费大概多少？", "About how much is a month's food cost?", ["租", "代", "费", "料"], ["fare", "charge", "expense", "fee"]),
	"5-18": t("这里是禁止超车路段。", "This is a no-passing zone.", ["跟随", "挤入", "赶出", "超车"], ["follow", "cut in", "drive out", "overtake"]),
	"5-19": t("1分钟是60秒。", "One minute is 60 seconds.", ["沙", "科", "秒", "料"], ["sand", "subject", "second", "fee"]),
	"5-20": t("参加日本有代表性的节日。", "Take part in a representative Japanese festival.", ["式", "的", "色", "化"], ["ceremony", "-like", "color", "-ize"]),
	"5-21": t("有低温烫伤的危险。", "Risk of low-temperature burns.", [], []),
	"5-23": t("不要叠着使用。", "Do not use it folded.", [], []),
	"5-24": t("上面不要放重物。", "Do not put heavy things on it.", [], []),
	"5-25": t("毯子请手洗。", "Hand-wash the blanket.", [], []),
	"6-1": t("不问有无经验。", "Experience not required.", ["有无（音错）", "有无（音错）", "有无", "有无（音错）"], ["wrong", "wrong", "whether or not", "wrong"]),
	"6-2": t("为省做饭手续用微波炉。", "I use the microwave to save cooking effort.", ["排除", "省去", "怀抱", "解开"], ["exclude", "omit/save", "embrace", "untie"]),
	"6-3": t("正在招募住户。", "Seeking tenants.", ["入居（音错）", "入居（音错）", "入居（音错）", "入居"], ["wrong", "wrong", "wrong", "move in"]),
	"6-4": t("住在从车站步行3分钟的地方。", "I live a three-minute walk from the station.", ["徒步（音错）", "音错", "徒步", "音错"], ["wrong", "wrong", "on foot", "wrong"]),
	"6-5": t("得到财富未必幸福。", "Gaining wealth doesn't always mean happiness.", ["有", "需要", "得到", "在"], ["have", "need", "obtain", "be"]),
	"6-6": t("这一带没看到钱包吗？", "Has anyone seen a wallet around here?", ["街道", "便利", "周围", "这一带"], ["street", "convenient", "around", "this area"]),
	"6-7": t("穿棉衬衫。", "Wear a cotton shirt.", ["米棉", "黄棉", "木棉/棉", "小棉"], ["wrong", "wrong", "cotton", "wrong"]),
	"6-8": t("长头发请用皮筋扎起来。", "Please tie long hair back with a band.", ["扎起", "音错", "损害", "束（音错）"], ["tie up", "wrong", "harm", "wrong"]),
	"6-9": t("乱停的自行车由市里处理。", "Abandoned bicycles are disposed of by the city.", ["古文", "处分", "居文", "贮文"], ["old text", "disposal", "wrong", "wrong"]),
	"6-10": t("着火房子里的孩子被平安救了出来。", "The child in the burning house was rescued unharmed.", ["无事（音错）", "无事（音错）", "精彩", "平安"], ["wrong", "wrong", "splendid", "safe"]),
	"6-11": t("我的故乡自然很丰富。", "My hometown is rich in nature.", ["富", "丰", "财", "泉"], ["wealth", "abundant", "money", "spring"]),
	"6-12": t("手一滑把盘子打破了。", "My hand slipped and I broke the plate.", ["器", "盘", "甜", "宝"], ["vessel", "plate", "sweet", "treasure"]),
	"6-13": t("今天牛肉很划算。", "Beef is a bargain today.", ["说", "特", "得/划算", "读"], ["theory", "special", "a good deal", "read"]),
	"6-14": t("日本最大的湖在哪里？", "Where is Japan's largest lake?", ["湖", "谷", "湾", "岸"], ["lake", "valley", "bay", "shore"]),
	"6-15": t("第一名选手会获赠奖金。", "The first-place athlete is given prize money.", ["招募", "迟到", "层", "赠送"], ["recruit", "late", "layer", "present"]),
	"6-16": t("干电池正负极一接，电就通了。", "Connect the battery's plus and minus poles and current flows.", ["角", "局", "曲", "极"], ["corner", "bureau", "tune", "pole"]),
	"6-17": t("在找六叠一间带浴厕的房子。", "Looking for a 6-tatami room with bath and toilet.", ["粒", "叠", "部", "屋"], ["grain", "tatami mats", "section", "house"]),
	"6-18": t("买了24色的颜料。", "I bought 24-color paints.", ["具", "材", "笔", "画"], ["tools/paints", "material", "brush", "picture"]),
	"6-19": t("去美术馆看了国宝展，非常棒。", "I saw the national-treasure exhibition; it was wonderful.", ["园", "展", "艺", "财"], ["garden", "exhibition", "art", "asset"]),
	"6-20": t("读早报。", "Read the morning edition.", ["版", "刊", "组", "编"], ["edition", "publication", "set", "compile"]),
	"6-21": t("这本书在分馆。", "This book is in the branch library.", ["次", "古", "支", "旧"], ["next", "old", "branch", "former"]),
	"6-22": t("为了节能，不用的插座都拔了。", "To save energy I unplug unused outlets.", ["节", "略", "省", "消"], ["cut down", "omit", "save/reduce", "erase"]),
	"6-23-25": t("“超好吃”“超漂亮”是俗语。新干线叫超特急、特别便宜叫超特价、特别挤叫超满员，才是正确用法。", "'Super tasty' is slang. Calling the shinkansen a super limited express, a bargain a super special price, or a crush super full is the proper use of 超."),
	"7-1": t("给对方思考的时间。", "Give the other person time to think.", ["锻炼", "回答", "给予", "传达"], ["train", "respond", "give", "convey"]),
	"7-2": t("喜欢味道浓一点的咖啡。", "I like my coffee on the strong side.", ["拔目", "之目", "浓一点", "吸目"], ["wrong", "wrong", "on the strong side", "wrong"]),
	"7-3": t("把人们引向幸福的未来。", "Lead people toward a happy future.", ["飘", "引导", "拖长", "低语"], ["trail", "guide", "drag on", "whisper"]),
	"7-4": t("清楚地陈述自己的主张。", "State your position clearly.", ["陈述", "滑动", "锅", "烧"], ["state", "slip", "pot", "burn"]),
	"7-5": t("字迹潦草，请见谅。", "Please forgive my messy handwriting.", ["原谅", "尝试", "度过", "体谅"], ["forgive", "try", "spend", "infer"]),
	"7-6": t("宇宙旅行已不再是梦想。", "Space travel is no longer just a dream.", ["愉调", "宇调", "府中", "宇宙"], ["wrong", "wrong", "wrong", "outer space"]),
	"7-7": t("希望听到率直的意见。", "I'd like to hear frank opinions.", ["坦率", "实直", "利直", "率直"], ["honest", "wrong", "wrong", "straightforward"]),
	"7-8": t("把材料充分搅拌。", "Mix the ingredients well.", ["搅拌", "音错", "音错", "音错"], ["mix", "wrong", "wrong", "wrong"]),
	"7-9": t("报考许可下来了。", "Permission to sit the exam came through.", ["结果", "许可", "豪华", "市厅"], ["result", "permission", "luxury", "city hall"]),
	"7-10": t("今晚好像会暴风雪。", "It looks like a blizzard tonight.", ["暴风雪", "水花", "初雪", "雪崩"], ["blizzard", "spray", "first snow", "avalanche"]),
	"7-11": t("手术有时需要输血。", "Surgery sometimes requires a transfusion.", ["输血", "输盘", "轮血", "轮盘"], ["transfusion", "wrong", "wrong", "wrong"]),
	"7-12": t("有时过程比结果更重要。", "Sometimes the process matters more than the result.", ["假定", "家庭", "课程", "过程"], ["assumption", "family", "curriculum", "process"]),
	"7-13": t("考上第一志愿的大学很高兴。", "I'm happy I got into my first-choice university.", ["脂肪", "志愿", "死亡", "预防"], ["fat", "aspiration", "death", "prevention"]),
	"7-14": t("播下花种。", "Sow flower seeds.", ["竹", "根", "灰", "种"], ["bamboo", "root", "ash", "seed"]),
	"7-15": t("海鸥丸因恶劣天气停航。", "The Kamome-maru was canceled due to bad weather.", ["决行", "不错", "停航", "血行"], ["go ahead", "fine", "flight/ship canceled", "circulation"]),
	"7-16": t("帮我买一本杂志来好吗？", "Could you buy a magazine?", ["刊", "册", "杯", "张"], ["issue", "bound volume", "cup", "sheet"]),
	"7-17": t("现在开始口试。", "The oral exam starts now.", ["面", "笔", "记", "述"], ["face/interview", "written", "record", "describe"]),
	"7-18": t("不是要一直住，只是临时住所。", "I'm not staying forever — it's temporary housing.", ["临时", "公", "单", "应"], ["temporary", "public", "single", "respond"]),
	"7-19": t("工作业绩上去，工资也会涨吧。", "If job performance rises, so should pay.", ["责", "积", "绩", "渍"], ["duty", "pile", "achievements", "pickle"]),
	"7-20": t("把茶装进水筒带着。", "Put tea in a flask and take it along.", ["竹", "筒", "封", "包"], ["bamboo", "cylinder/flask", "seal", "wrap"]),
	"7-21-25": t("狗和猫等小动物用“匹”数，牛和马等大型动物用“头”。房子店铺用“轩”，房子也可以用“户”。", "Small animals like dogs and cats are counted with 匹; large ones like cows and horses with 頭. Houses and shops take 軒; houses can also take 戸."),
	"8-1": t("演唱会场挤满了粉丝，超满员。", "The concert hall was packed beyond capacity.", ["大成", "大势（音错）", "体制", "大势"], ["success", "wrong reading", "system", "a crowd"]),
	"8-2": t("妈妈是典型的旧式日本女性。", "Mom is a typical old-fashioned Japanese woman.", ["模范", "理想", "传统", "典型"], ["model", "ideal", "traditional", "typical"]),
	"8-3": t("孩子的意愿也应尊重。", "A child's will should also be respected.", ["敬重", "尊重", "敬听", "尊重"], ["wrong", "wrong", "wrong", "respect"]),
	"8-4": t("现代人是不是缺少尊敬他人的心？", "Have people today lost the feeling of respecting others?", ["违抗", "尊敬", "应付", "跟随"], ["defy", "revere", "treat", "follow"]),
	"8-5": t("请允许我补充说明。", "Allow me to add a supplementary explanation.", ["不足", "补充", "附属", "补足（音错）"], ["shortage", "supplement", "affiliated", "wrong"]),
	"8-6": t("哥哥在县厅当职员。", "My brother works as a staffer at the prefectural office.", ["县厅", "县定", "县章", "县所"], ["prefectural office", "wrong", "wrong", "wrong"]),
	"8-7": t("被告主张无罪。", "The defendant claims innocence.", ["破告", "被告", "布告", "闭告"], ["wrong", "the accused", "notice", "wrong"]),
	"8-8": t("希望他弥补所犯的罪。", "I want him to atone for the crime he committed.", ["本", "发生", "版", "犯"], ["main", "cause", "edition", "commit (a crime)"]),
	"8-9": t("思考环境问题。", "Think about environmental problems.", ["研京", "环境", "换球", "研究"], ["wrong", "environment", "wrong", "research"]),
	"8-10": t("各国选手较量技艺。", "Athletes from each country competed in skill.", ["较量", "争执", "夺取", "尊敬"], ["compete", "quarrel", "seize", "revere"]),
	"8-11": t("努力恢复公司的信赖。", "Work to restore the company's trust.", ["担任", "上班", "努力", "勤勉"], ["serve as", "work at", "strive", "study hard"]),
	"8-12": t("日本队在决赛中落败。", "Japan lost in the final.", ["败", "破", "折", "倒"], ["be defeated", "tear", "break", "fall"]),
	"8-13": t("热水温度怎么样？", "How's the water temperature?", ["增减", "加减", "削减", "过减"], ["increase/decrease", "adjustment", "cut", "wrong"]),
	"8-14": t("因不景气半数员工被解雇。", "Half the staff were laid off in the slump.", ["解子", "解放", "解雇", "解户"], ["wrong", "release", "dismiss", "wrong"]),
	"8-15": t("太太的厨艺真棒。", "Your wife's cooking skill is amazing.", ["腕每", "腕力", "腕米", "腕前"], ["wrong", "physical strength", "wrong", "skill"]),
	"8-16": t("新型流感正在流行。", "A new strain of flu is going around.", ["米", "型", "兵", "星"], ["rice", "type/strain", "soldier", "star"]),
	"8-17": t("外国人有选举权吗？", "Do foreigners have voting rights?", ["件", "令", "条", "权"], ["matter", "order", "article", "right"]),
	"8-18": t("大雨导致各地发生水灾。", "Heavy rain has caused flooding in many places.", ["害", "绝", "爆", "暴"], ["damage", "cut off", "explode", "violent"]),
	"8-19": t("我从美国加利福尼亚州来。", "I'm from the state of California.", ["周", "集", "州", "宗"], ["week", "gather", "state", "sect"]),
	"8-20": t("在野党批评首相的发言。", "The opposition criticized the prime minister's remarks.", ["党", "军", "童", "觉"], ["party", "army", "child", "sense"]),
	"8-21": t("国家有巨额债务。", "The country has a huge debt.", ["亡", "总", "巨", "满"], ["perish", "total", "huge", "full"]),
	"8-22-25": t("公司之长是社长，学校是校长，大学是学長，政府之长是总理大臣。厚生劳动省等各省之长也是大臣，气象厅、警察厅等厅则称长官。", "A company's head is the president; a school's the principal; a university's the president; the government's is the prime minister. Ministry heads are also ministers; agency heads are called 長官."),
}


