def t(cn, en, opts_cn=None, opts_en=None, point="", point_en=""):
	return {"cn": cn, "en": en, "opts_cn": opts_cn or [], "opts_en": opts_en or [], "point": point, "point_en": point_en}


VOCAB_EXAM = {
	"1-1": t("没有电饭煲，就用锅煮饭了。", "There was no rice cooker, so I cooked rice in a pot.", ["煮", "蒸", "煮饭", "炸"], ["boil", "steam", "cook rice", "deep-fry"]),
	"1-2": t("这条狗不咬也不叫，摸也没关系。", "This dog doesn't bite or bark, so it's fine to pet.", ["抚摸", "叫", "打", "揍"], ["stroke", "bark", "hit", "beat"]),
	"1-3": t("出门前把鞋擦干净吧。", "Let's polish the shoes before we go out.", ["拧", "擦亮", "穿", "晾"], ["wring", "polish", "wear", "dry"]),
	"1-4": t("不能给孩子太多钱。", "You mustn't give children too much money.", ["给", "凑齐", "做完", "保存"], ["give", "arrange", "finish", "store"]),
	"1-5": t("我一哭，妈妈就温柔地摸我的头。", "When I cried, Mom gently stroked my head.", ["搓", "打", "哼", "抚摸"], ["rub", "hit", "groan", "stroke"]),
	"1-6": t("把蔬菜切细再好好炒。", "Chop the vegetables fine, then stir-fry them well.", ["盖上", "包起来", "削皮", "切碎"], ["cover", "wrap", "peel", "mince"]),
	"1-7": t("这间房朝南有大窗户，采光很好。", "This room has a big south window, so it's very sunny.", ["空调很足", "采光好", "很冷", "收拾得开"], ["AC is strong", "gets good sun", "is cold", "tidies easily"]),
	"1-8": t("想瘦，所以尽量不吃高热量的东西。", "I want to lose weight, so I avoid high-calorie food.", ["均衡", "糖", "卡路里", "味道"], ["balance", "sugar", "calories", "taste"]),
	"1-9": t("“啊，锅糊了。”“糟了，忘了。”", "“The pot's burning!” “Oh no, I forgot.”", ["糊了", "盖着", "煮着", "焯着"], ["is burning", "is covered", "is simmering", "is boiling"]),
	"1-10": t("插座上积灰很危险。", "Dust on an outlet is dangerous.", ["干洗", "插座", "刷子", "水桶"], ["dry cleaning", "outlet", "brush", "bucket"]),
	"1-11": t("把上下或正反反过来。", "Turn something over, top to bottom or front to back.", ["搅拌", "翻转", "摩擦", "对齐"], ["mix", "flip over", "rub", "line up"]),
	"1-12": t("称重量的工具。", "A tool for measuring weight.", ["秤", "量杯", "大勺", "菜刀"], ["scale", "cup", "tablespoon", "knife"]),
	"1-13": t("晒干。", "Dry something in the sun.", ["弄湿", "挂起来", "叠", "晾晒"], ["wet", "hang", "fold", "dry in the sun"]),
	"1-14": t("把婴儿或小东西抱在怀里。", "Hold a baby or small thing in your arms.", ["抱（胸前）", "背", "牵手", "摸"], ["hold in arms", "piggyback", "hold hands", "stroke"]),
	"1-15": t("放进大量热油里炸。", "Cook by putting food in lots of hot oil.", ["炖", "蒸", "炸", "焯"], ["simmer", "steam", "deep-fry", "parboil"]),
	"1-16": t("拧水龙头。", "Turn the tap.", ["放下", "转", "按", "拿出"], ["lower", "turn", "push", "take out"]),
	"1-17": t("为了打扫把椅子挪开。", "Move the chairs aside to clean.", ["移动", "对齐", "放", "收拾"], ["move", "align", "put", "tidy"]),
	"1-18": t("往拉面上撒胡椒。", "Sprinkle pepper on the ramen.", ["撒/浇", "铺", "拌", "加热"], ["sprinkle", "spread", "mix", "heat"]),
	"1-19": t("羊毛衫缩水了。", "The wool sweater shrank.", ["变长了", "变旧了", "干透了", "变小了"], ["stretched", "got old", "dried well", "got smaller"]),
	"1-20": t("隔壁的狗经常叫。", "The neighbor's dog barks a lot.", ["叫", "习惯", "摸", "生气"], ["cry/bark", "get used to", "stroke", "get angry"]),
	"1-21": t("我在榻榻米上铺被睡觉。", "I spread a futon on the tatami and sleep.", ["请在桌上铺盘子", "客厅铺着沙发", "拧水龙头叫敷く", "榻榻米上铺被"], ["spread plates", "a sofa is 敷いて", "turn the tap", "spread a futon"]),
	"1-22": t("考虑营养均衡来吃饭。", "Let's eat with nutritional balance in mind.", ["均衡很凉快", "用秤称蔬菜均衡", "考虑营养均衡吃饭", "高均衡食品会胖"], ["balance is cool", "weigh vegetable balance", "think about nutrition balance", "high-balance food"]),
	"1-23": t("梅雨季食物易坏，放冰箱保存。", "Food spoils easily in tsuyu, so keep it in the fridge.", ["保存很多待洗衣物", "梅雨季把食物放冰箱保存", "养宠物叫保存", "用微波炉保存剩菜"], ["store laundry", "store food in the fridge", "store a pet", "store leftovers in a microwave"]),
	"1-24": t("洒了果汁，把裙子弄脏了。", "I spilled juice and stained my skirt.", ["用了十年很汚している", "雨没弄脏所以进烘干机", "把抹布弄脏来擦地", "洒果汁弄脏裙子"], ["have been dirtying it", "isn't dirty so use the dryer", "dirty a rag", "stained the skirt"]),
	"1-25": t("不要任性，别给妈妈添麻烦。", "Don't be selfish and trouble your mother.", ["虽小但わがままで了不起", "别任性难为妈妈", "谁わがまま了门打不开", "狗对谁都摇尾巴叫わがまま"], ["selfish and admirable", "don't be selfish", "who was わがまま", "friendly dog is わがまま"]),
	"2-1": t("每年都去海外旅行，今年没钱就国内游。", "I travel abroad every year, but this year I'll stay domestic.", ["外出", "外表", "海外", "外侧"], ["going out", "appearance", "overseas", "outside"]),
	"2-2": t("下下个月是再来月。", "The month after next is 再来月.", ["上个月", "上上个月", "下下个月（错词）", "再来月"], ["last month", "month before last", "wrong word", "month after next"]),
	"2-3": t("飞机座位我总是订靠过道的。", "I always book an aisle seat on the plane.", ["靠窗", "靠过道", "内侧", "外侧"], ["window side", "aisle side", "inside", "outside"]),
	"2-4": t("电车按时刻表从东京站发车了。", "The train departed Tokyo Station on schedule.", ["上车", "下车", "发车", "停车"], ["board", "get off", "depart", "stop"]),
	"2-5": t("让孩子坐在车上时，注意开关窗。", "When a child is in the car, watch the windows.", ["握着", "装着（货）", "牵着", "让乘坐"], ["grip", "load", "join", "have ride"]),
	"2-6": t("把大学学费汇进指定账户。", "I transferred the tuition into the designated account.", ["存款了", "汇入了", "填写了", "取出来了"], ["deposited", "transferred in", "filled in", "withdrew"]),
	"2-7": t("钥匙插着就停车，会被偷的。", "If you leave the key in, the car may be stolen.", ["插着", "抽出来", "递出去", "走到头"], ["inserted", "pulled out", "held out", "hit a dead end"]),
	"2-8": t("哥哥出了交通事故，住院了。", "My brother had a traffic accident and was hospitalized.", ["遇上", "撞了", "坐上", "被抓住"], ["met with", "ran over", "got on", "was caught"]),
	"2-9": t("开了银行账户，给了存折和卡。", "When I opened an account they gave me a passbook and card.", ["纸币", "存折", "印章", "硬币"], ["bills", "passbook", "seal", "coins"]),
	"2-10": t("旅行前一天取消，钱一分没退。", "I canceled the day before and got no refund.", ["申请", "调整", "变更", "取消"], ["apply", "adjust", "change", "cancel"]),
	"2-11": t("电车公交车最后到达的站。", "The last stop a train or bus reaches.", ["始发", "停车站", "末班车", "终点"], ["first train", "stop", "last train", "terminus"]),
	"2-12": t("期限内两站之间可无限次乘坐的票。", "A ticket for unlimited rides between set stations.", ["定期票", "特急票", "回数票", "车票"], ["commuter pass", "limited-express ticket", "multi-ride ticket", "ride ticket"]),
	"2-13": t("把自己的东西让给别人。", "Give something of yours to someone else.", ["让给", "错开", "塞紧", "取下"], ["yield/give", "shift", "pack in", "take down"]),
	"2-14": t("开车时手里握的部分。", "The part you hold when driving.", ["油门", "发动机", "兜风", "方向盘"], ["accelerator", "engine", "drive", "steering wheel"]),
	"2-15": t("出门当天回来。", "Go out and come back the same day.", ["单程", "绕远", "当天来回", "一日游"], ["one way", "detour", "day trip", "one-day trip"]),
	"2-16": t("昨天少见地电车很空。", "Yesterday the train was unusually empty.", ["非常挤", "非常空", "非常晚", "非常快"], ["very crowded", "very empty", "very late", "very fast"]),
	"2-17": t("在窗口取存款需要印章。（預金＝存着的钱）", "You need a seal to withdraw deposits at the counter.", ["存起来", "取出来", "寄放", "支付"], ["save up", "withdraw", "entrust", "pay"]),
	"2-18": t("突然有工作，旅行日程改了。", "Urgent work came up, so I shifted the travel dates.", ["错开了", "克制了", "取消了", "申请了"], ["shifted", "held back", "canceled", "applied"]),
	"2-19": t("斜着穿过马路。", "I crossed the road diagonally.", ["跑了", "走了", "停了", "过了"], ["ran", "walked", "stopped", "crossed"]),
	"2-20": t("尽量少用手机。", "Refrain from using a mobile phone.", ["不想做", "反复做", "尽量不做", "第一次做"], ["don't want to", "repeat", "try not to", "do for the first time"]),
	"2-21": t("买满一万日元就免运费。", "No shipping fee if you spend 10,000 yen or more.", ["换一万日元收了运费", "从银行取出运费", "汇款运费变贵了", "满一万免运费"], ["charged 送料 to change a bill", "withdrew 送料", "transfer 送料 got expensive", "no shipping over 10,000"]),
	"2-22": t("商品货款用现金支付。", "Pay for goods in cash.", ["用现金付货款", "为攒钱向银行支払う", "生活费不够就支払う存款", "把一万换成十张一千叫支払う"], ["pay the price in cash", "pay the bank to save", "pay savings", "break a 10,000-yen bill"]),
	"2-23": t("去东京那边旅行三晚四天。", "I'll take a 3-night trip toward Tokyo.", ["坐东京方面开往横滨的下行", "去东京那边旅行", "没定座位方面就上车", "看着方面到酒店"], ["a train 方面 from Tokyo", "travel in the Tokyo direction", "seat 方面", "watch 方面 to the hotel"]),
	"2-24": t("坐过了末班车该下的站，只好打车回去。", "I rode past my stop on the last train, so I took a taxi.", ["坐过末班，打车回去", "打盹坐过了该下的站", "特急坐过了车站", "从特急换乘各站停车叫乗り過ごす"], ["missed the last train home", "dozed and rode past the stop", "the express rode past", "changed trains"]),
	"2-25": t("差点撞上，赶紧踩了刹车。", "I almost hit something and slammed on the brakes.", ["天黑了请开刹车", "周日握住刹车", "差点撞上踩了刹车", "注意刹车出得太多"], ["turn on the brakes", "grip the brakes on Sunday", "hit the brakes", "don't put out too much brake"]),
	"3-1": t("这块表虽旧，我很喜欢。", "This watch is old, but I'm fond of it.", ["爱好", "合适", "中意", "流行"], ["be fond of doing", "suit", "like/be pleased with", "be in fashion"]),
	"3-2": t("今天冷，最好穿长袖。", "It's cold today, so you'd better wear long sleeves.", ["长袖", "条纹", "花纹", "素色"], ["long sleeves", "stripes", "pattern", "solid color"]),
	"3-3": t("这家餐厅的账我来付。", "I'll pay the bill at this restaurant.", ["存款", "生活费", "现金", "价款"], ["deposit", "living costs", "cash", "the bill"]),
	"3-4": t("今天聚餐大家 AA 吧。", "Let's split the bill tonight.", ["除法", "AA 制", "请客", "费用"], ["division", "split the bill", "treat", "expense"]),
	"3-5": t("胡子长了，得刮了。", "My beard's grown; I need to shave.", ["眼皮", "额头", "胡子", "脸颊"], ["eyelid", "forehead", "beard", "cheek"]),
	"3-6": t("哎呀，戴着好漂亮的戒指。", "Oh, what a lovely ring you're wearing.", ["戴（戒指）", "穿（下装）", "系", "放进"], ["wear (ring)", "wear (shoes/pants)", "fasten", "put in"]),
	"3-7": t("卡快到期了。", "The card is about to expire.", ["费用", "价款", "日程", "有效期"], ["cost", "price", "schedule", "expiration date"]),
	"3-8": t("（对服务员）那个，我想再点一些……", "I'd like to add to my order…", ["追加", "再来一份", "推荐", "决定"], ["add on", "another serving", "recommend", "decide"]),
	"3-9": t("对不起，下周不方便。", "Sorry, next week doesn't work for me.", ["不能", "不方便（都合がつかない）", "空不出来", "不花"], ["can't", "can't arrange it", "won't open", "doesn't take"]),
	"3-10": t("一台就够还买新车，不觉得太奢侈吗？", "One car is enough — isn't buying another extravagant?", ["麻烦", "不足", "穷", "奢侈"], ["nuisance", "shortage", "poor", "luxury"]),
	"3-11": t("被喜欢的人拒绝或提出分手。", "Be turned down or dumped by someone you like.", ["不受欢迎", "分开", "被甩", "被邀请"], ["unpopular", "become separate", "be dumped", "be invited"]),
	"3-12": t("声音太大、吵闹。", "Too loud and noisy.", ["吵", "热闹", "麻烦", "空荡"], ["noisy", "lively", "nuisance", "empty"]),
	"3-13": t("为做某事花的钱。", "Money it costs to do something.", ["现金", "账单", "费用", "存款"], ["cash", "the check", "expense", "deposit"]),
	"3-14": t("把钱换成零钱。", "Break money into smaller bills/coins.", ["省掉", "换成零钱", "除", "修好"], ["omit", "break a bill", "divide", "fix"]),
	"3-15": t("约别人一起去或一起做。", "Ask someone to go or do something together.", ["交往", "邀请", "请客", "和好"], ["go out with", "invite", "treat", "make up"]),
	"3-16": t("听说田中在和中村交往。", "I hear Tanaka is going out with Nakamura.", ["相称", "交往", "和好", "结婚"], ["suit", "date", "reconcile", "marry"]),
	"3-17": t("少浪费，尽量存钱。", "Cut waste and save as much as you can.", ["受穷", "节约", "不借钱", "赚到"], ["be poor", "economize", "not borrow", "profit"]),
	"3-18": t("醉汉大声吵闹。", "A drunk is being loud.", ["喊着", "添麻烦", "很吵", "享受着"], ["shouting", "causing trouble", "being noisy", "enjoying"]),
	"3-19": t("今年流行碎花裙。", "Floral skirts are in fashion this year.", ["正流行", "合适", "中意", "向往"], ["in fashion", "suits", "likes", "admires"]),
	"3-20": t("田中课长又温柔又帅，很受女性欢迎。", "Section chief Tanaka is kind and good-looking, so women like him.", ["被甩", "被申请", "被讨厌", "被喜欢"], ["dumped", "applied to", "disliked", "liked"]),
	"3-21": t("定不下来，就含糊回答了。", "I couldn't decide, so I gave a vague answer.", ["购物あいまい所以生活费不够", "两人あいまいに关系不好", "明确回答叫あいまい", "定不下来就含糊回答"], ["shopped vaguely", "they're vaguely on bad terms", "answered 必ず行きます vaguely", "answered vaguely"]),
	"3-22": t("绳子系得太紧，怎么也解不开。", "The cord is tied so tight I can't undo it.", ["绳子太紧解不开", "出门前解胡子", "吃撑了就解皮带", "开车时把手从方向盘ほどく"], ["can't untie the cord", "untie your beard", "untie the belt", "untie your hands from the wheel"]),
	"3-23": t("“我们分开付，请算一下。”", "We'll pay separately, please.", ["被求婚后別々にした", "有不懂的词就別々に查词典", "分开付请结账", "部长请客不必AA別々"], ["turned them down 別々", "look up words 別々", "pay separately", "no need to split 別々"]),
	"3-24": t("能用的扔掉太可惜，让给想要的人吧。", "It's a waste to throw away something usable — give it to someone who wants it.", ["后口袋放钱包走路もったいない", "能用的扔掉太可惜", "带我去もったいない氛围的餐厅", "问店员推荐もったいない"], ["wallet in back pocket", "wasteful to throw away", "a wasteful-atmosphere restaurant", "asking for a recommendation is wasteful"]),
	"3-25": t("店虽小，味道好，所以我喜欢。", "The shop is small, but I like it because the food is good.", ["店小但味道好所以中意", "我気に入っている他所以很喜欢", "小林気に入っている老师的话", "堵车能不能准时気に入っている"], ["like the shop for the taste", "like him so I like him", "Lin likes the teacher's words", "worried about being on time"]),
	"4-1": t("6 个人 6000 日元，一除每人 1000。", "6,000 yen for 6 people is 1,000 each if you divide.", ["加法", "减法", "乘法", "除法"], ["addition", "subtraction", "multiplication", "division"]),
	"4-2": t("8×3 读作 8 かける 3。", "8×3 is read 8 kakeru 3.", ["8 加 3", "8 乘 3", "8 除 3", "8 减 3"], ["plus", "times", "divided by", "minus"]),
	"4-3": t("要毕业必须修满一共 150 学分。", "You have to get 150 credits in all to graduate.", ["不接受", "不修/不拿", "不报考", "不专攻"], ["not receive", "not take/earn", "not sit the exam", "not major"]),
	"4-4": t("考试里问的问题意思没看懂。", "I didn't understand what the exam question was asking.", ["被问的", "听写着", "制作着", "被填写的"], ["being asked", "dictating", "creating", "filled in"]),
	"4-5": t("把简历附在邮件里寄出。", "I'll attach the resume to the email and send it.", ["转发", "回复", "附件", "整理"], ["forward", "reply", "attach", "organize"]),
	"4-6": t("一合计是两万日元。", "If you add it up, it's 20,000 yen.", ["算出", "得到", "变成", "做"], ["work out", "obtain", "become", "do"]),
	"4-7": t("铅笔圆了，削一下吧。", "The pencil's dull, so let's sharpen it.", ["汇总", "接上", "称", "削"], ["summarize", "connect", "weigh", "sharpen"]),
	"4-8": t("在电脑里输入「はな」转换成「花」。", "Type hana and convert it to 花.", ["发送", "变更", "作成", "转换"], ["send", "change", "create", "convert"]),
	"4-9": t("我和他在邮件来往。", "I exchange emails with him.", ["接收", "来往", "检查", "重复"], ["receive", "exchange", "check", "repeat"]),
	"4-10": t("太累，上课打瞌睡了。", "I was tired and dozed off in class.", ["打瞌睡", "休学", "偷懒", "逃课"], ["doze", "leave school", "slack", "skip"]),
	"4-11": t("不看任何东西也能写、能说地记住。", "Memorize so you can write or say it with nothing to look at.", ["背下来", "听写下来", "再看一遍", "办完"], ["memorize", "catch by ear", "review", "finish"]),
	"4-12": t("走运。", "To be lucky.", ["连着", "守着", "住着", "走运"], ["connected", "protecting", "living", "in luck"]),
	"4-13": t("经历多次后不再觉得特别。", "After many times it no longer feels special.", ["汇总", "习惯", "重复", "碰"], ["summarize", "get used to", "repeat", "touch"]),
	"4-14": t("高中大学毕业所需的基准。", "The units you need to graduate high school or university.", ["讲座", "专业", "补课", "学分"], ["lecture", "major", "makeup class", "credit"]),
	"4-15": t("把收到的邮件再发到别处。", "Send a received email on to somewhere else.", ["发送", "回复", "转发", "接收"], ["send", "reply", "forward", "receive"]),
	"4-16": t("用尺量纸的尺寸。", "Measure the paper size with a ruler.", ["秤", "尺子", "鼠标", "剪刀"], ["scale", "ruler", "mouse", "scissors"]),
	"4-17": t("大学学费一年比一年贵。", "University fees get higher every year.", ["学费", "奖学金", "工资", "报考费"], ["tuition", "scholarship", "salary", "exam fee"]),
	"4-18": t("把不需要的邮件删了。", "I deleted the unwanted mail.", ["检查了", "去掉了", "整理了", "转发了"], ["checked", "removed", "organized", "forwarded"]),
	"4-19": t("工地的活很累。", "Construction work is hard.", ["辛苦", "慢", "不走运", "不习惯"], ["tough", "slow", "unlucky", "unused to"]),
	"4-20": t("逃课了，所以听不懂内容。", "I skipped class, so I don't follow the material.", ["凑齐", "偷懒", "汇总", "削"], ["arrange", "slack off", "put together", "sharpen"]),
	"4-21": t("妹妹是文学部的吧，专业是什么？", "You're in the literature faculty, right? What's your major?", ["我在理工部専攻", "文学部専攻是什么", "经济学専攻迟到了", "専攻了心理学报告"], ["I 専攻 the faculty of science", "what's your major", "late for the 専攻", "専攻 a report"]),
	"4-22": t("进了擅长体育的高中。", "I entered a high school that's strong at sports.", ["我擅长游泳", "进了体育强的高中", "一次交齐一年学费更得意", "成绩好就対みんな得意にした"], ["I'm good at swimming", "a school good at sports", "paying in a lump is 得意", "made it 得意 to everyone"]),
	"4-23": t("做完这工作再吃饭。", "Let's eat after I finish this job.", ["交完来守期限", "做完这工作再吃饭", "写完简历再去面试", "读完医学部当了医生"], ["finish submitting", "finish this work then eat", "finish a resume", "finish medical school"]),
	"4-24": t("我和他每年只互寄贺年片。", "He and I only exchange New Year cards each year.", ["换了新电脑写报告", "把今天的课又やり取り了", "每年只互寄贺年片", "便利店打工やり取り生活费"], ["やり取り a new PC", "やり取り today's class", "exchange New Year cards", "やり取り living costs at a job"]),
	"4-25": t("新产品卖得好，店大赚了一笔。", "The new product sold well, so the shop made a lot.", ["赚很多所以必须节约", "客人少所以もうかった", "开销大生活费もうかった", "新产品好卖店很赚钱"], ["made so much we must save", "few customers so we profited", "living costs profited", "the shop made a big profit"]),
}

KANJI_EXAM = {
	"1-1": t("写着「注意突然冲出」。", "It says “Watch for people darting out.”", ["呼叫注意", "冲出注意", "冲出じゅうい", "呼叫じゅうい"], ["yobidashi", "tobidashi chūi", "wrong", "wrong"]),
	"1-2": t("这块表很准。", "This clock is accurate.", ["せいかく", "せっかく", "しょうかく", "しょうがく"], ["seikaku", "sekkaku", "wrong", "wrong"]),
	"1-3": t("走人行横道过马路。", "Let's cross at the crosswalk.", ["こうだん", "おうだん", "きんだん", "そうだん"], ["wrong", "ōdan", "kindan", "sōdan"]),
	"1-4": t("这口锅是铁做的。", "This pot is made of iron.", ["しつ", "ねつ", "れつ", "てつ"], ["shitsu", "netsu", "retsu", "tetsu"]),
	"1-5": t("优先席请不要用手机。", "Please don't use mobile phones in priority seats.", ["うせん", "にゅうせん", "ゆうせん", "よやく"], ["wrong", "wrong", "yūsen", "yoyaku"]),
	"1-6": t("车费请下车时付。", "Please pay the fare when you get off.", ["のりる", "ふりる", "こりる", "おりる"], ["wrong", "wrong", "wrong", "oriru"]),
	"1-7": t("无关人员请勿入内。", "No entry except authorized personnel.", ["かんけいしゃ", "かんれんしゃ", "けいけんしゃ", "かんきょうしゃ"], ["kankeisha", "related person", "experienced person", "environment person"]),
	"1-8": t("按下确认按钮。", "Press the confirm button.", ["せきにん", "かくにん", "しょうにん", "こうにん"], ["responsibility", "kakunin", "approval", "public official"]),
	"1-9": t("门旁边有开关。", "There's a switch beside the door.", ["旁边（そば）", "横", "竖", "隔壁"], ["nearby", "yoko (beside)", "vertical", "next door"]),
	"1-10": t("从高速公路看得见机场。", "You can see the airfield from the expressway.", ["航空", "飞行场（错读）", "空港", "飞行场"], ["kōkū", "wrong", "kūkō", "hikōjō"]),
	"1-11": t("座位是几号？", "What number is the seat?", ["何号", "向番", "何番", "向号"], ["what-gō", "wrong", "nanban", "wrong"]),
	"1-12": t("请退到黄线后等候。", "Please stand back behind the yellow line.", ["线", "信", "段", "侧"], ["line", "letter", "step", "side"]),
	"1-13": t("那位女演员很有表现力。", "That actress has great expressiveness.", ["表信", "表见", "表言", "表现"], ["wrong", "wrong", "wrong", "hyōgen"]),
	"1-14": t("社长承认了错误。", "The president admitted the mistake.", ["定", "认", "窗", "面"], ["decide", "admit", "window", "face"]),
	"1-15": t("这趟电车每站都停。", "This train stops at every station.", ["每", "次", "各", "两"], ["every", "next", "each", "both"]),
	"1-16": t("那个信号是按钮式的。", "That signal is the push-button type.", ["箱", "席", "向", "式"], ["box", "seat", "toward", "style/-shiki"]),
	"1-17": t("停车场现在已满。", "The parking lot is full now.", ["两", "满", "禁", "非"], ["both", "full", "ban", "non-"]),
	"1-18": t("一万日元以上免运费。", "No shipping charge over 10,000 yen.", ["非", "不", "无", "禁"], ["non", "un", "without", "ban"]),
	"1-19": t("请取整理券等候。", "Please take a number ticket and wait.", ["停", "箱", "路", "券"], ["stop", "box", "road", "ticket"]),
	"1-20": t("请把钱放进收费箱。", "Please put the money in the fare box.", ["箱", "式", "侧", "券"], ["box", "type", "side", "ticket"]),
	"2-1": t("感谢您的协助。", "Thank you for your cooperation.", ["きゅうりょく", "きょうりょく", "こうりょく", "こうりゃく"], ["wrong", "kyōryoku", "kōryoku", "wrong"]),
	"2-2": t("不懂日语，正发愁。", "I don't understand Japanese and I'm stuck.", ["くまって", "こまって", "よわって", "まいって"], ["wrong", "komatte", "weakened", "beaten"]),
	"2-3": t("能帮我一下吗？", "Could you give me a hand?", ["たすけって", "てつだって", "ことづかって", "つたえって"], ["wrong", "tetsudatte", "wrong", "wrong"]),
	"2-4": t("去美术馆看画了。", "I went to the art museum to see paintings.", ["ぶじゅつかん", "ぎじゅつかん", "びじゅつかん", "しゅじゅつかん"], ["wrong", "tech museum", "bijutsukan", "wrong"]),
	"2-5": t("机场是空中的港口。", "An airport is a harbor in the sky.", ["くうこう", "くうきょう", "こうきょう", "こうこう"], ["kūkō", "wrong", "wrong", "high school"]),
	"2-6": t("京都有金阁寺这座名寺。", "Kyoto has a famous temple called Kinkaku-ji.", ["じ", "ぎ", "に", "ち"], ["ji (temple)", "gi", "ni", "chi"]),
	"2-7": t("为防地震做了各种准备。", "We're preparing in various ways for earthquakes.", ["迎接", "凑齐", "按住", "备好"], ["meet", "arrange", "hold down", "prepare for"]),
	"2-8": t("预防流感。", "Prevent the flu.", ["ゆうぼう", "ようぼう", "ゆぼう", "よぼう"], ["wrong", "wrong", "wrong", "yobō"]),
	"2-9": t("能借我橡皮吗？", "Could you lend me an eraser?", ["きして", "けして", "かして", "さして"], ["wrong", "kesu", "kashite", "sashite"]),
	"2-10": t("危险，请退到黄线内侧等候。", "It's dangerous; please wait inside the yellow line.", ["内侧", "内側（错读）", "外侧", "后侧"], ["uchigawa", "wrong", "sotogawa", "ushigawa"]),
	"2-11": t("帮朋友是理所当然的。", "Helping a friend is only natural.", ["光", "当", "满", "面"], ["light", "of course / natural", "full", "face"]),
	"2-12": t("富士山的形状很美。", "The shape of Mt. Fuji is beautiful.", ["形", "骨", "样", "烟"], ["shape", "bone", "manner", "smoke"]),
	"2-13": t("现在正在准备中。", "We're preparing now.", ["预约中", "营业中", "关门中", "准备中"], ["reserved", "open", "closed", "preparing"]),
	"2-14": t("捡到钱包，送到警察那儿。", "I found a wallet, so I'll take it to the police.", ["派出所", "消防", "警察", "观光"], ["kōban", "fire", "police", "tourism"]),
	"2-15": t("本站禁止吸烟。", "This station is non-smoking.", ["本", "今", "御", "当"], ["this (hon)", "now", "honorific", "this (tō)"]),
	"2-16": t("这趟电车全部对号入座。", "All seats on this train are reserved.", ["满", "空", "全", "次"], ["full", "empty", "all", "next"]),
	"2-17": t("交叉路口内不许停车。", "You must not stop inside an intersection.", ["向", "侧", "线", "内"], ["toward", "side", "line", "inside"]),
	"2-18": t("在妇产科做前台。", "I work reception in obstetrics and gynecology.", ["科", "化", "系", "局"], ["department", "-ize", "section", "bureau"]),
	"2-19": t("我赞成 A 方案。", "I'm in favor of plan A.", ["番", "券", "案", "段"], ["number", "ticket", "proposal", "step"]),
	"2-20": t("这个镇人口大约 20 万。", "This town has a population of about 200,000.", ["各", "现", "过", "约"], ["each", "current", "excess", "about"]),
	"3-1": t("在自动售货机买饮料。", "I buy a drink from a vending machine.", ["はんばい", "へんばい", "はんまい", "へんまい"], ["hanbai", "wrong", "wrong", "wrong"]),
	"3-2": t("请尽快享用。", "Please eat it as soon as you can.", ["おみしあがり", "おねしあがり", "おめしあがり", "おむしあがり"], ["wrong", "wrong", "omeshiagari", "wrong"]),
	"3-3": t("找日语教材。", "I'm looking for Japanese teaching materials.", ["きょうざい", "きゅうざい", "きょうぜい", "きゅうぜい"], ["kyōzai", "wrong", "wrong", "wrong"]),
	"3-4": t("把粉放进去搅拌。", "Put the powder in and mix.", ["すな", "こめ", "むぎ", "こな"], ["sand", "rice", "wheat", "kona (powder)"]),
	"3-5": t("便当里有鸡蛋烧。", "There's a rolled omelet in the bento.", ["たなごやき", "たまごまき", "たなごまき", "たまごやき"], ["wrong", "wrong", "wrong", "tamagoyaki"]),
	"3-6": t("请遵守交通规则。", "Let's obey the traffic rules.", ["なもりましょう", "まもりましょう", "もまりましょう", "もなりましょう"], ["wrong", "mamorimashō", "wrong", "wrong"]),
	"3-7": t("请数一下数。", "Please count the number.", ["かぞ", "くず", "かず", "しゅう"], ["kazo- (verb stem)", "kuzu", "kazu (number)", "shū"]),
	"3-8": t("倒进热水，等三分钟就好了。", "Add hot water and wait three minutes.", ["ゆ", "よ", "や", "い"], ["yu (hot water)", "yo", "ya", "i"]),
	"3-9": t("把录下的留言播放出来。", "Play back the recorded message.", ["せいしょう", "さいせい", "せいせい", "さいしょう"], ["wrong", "saisei", "wrong", "wrong"]),
	"3-10": t("冷气太强了。", "The air conditioning is too strong.", ["れいぼう", "れいぞう", "れいとう", "れいどう"], ["reibō", "reizō (fridge)", "reitō (frozen)", "wrong"]),
	"3-11": t("把书还给图书馆。", "I'll return the book to the library.", ["边", "归", "替", "返"], ["edge", "go home", "replace", "return"]),
	"3-12": t("拳击手赛前减重。", "The boxer cuts weight before a match.", ["减量", "消量", "增量", "限量"], ["lose weight", "wrong", "gain weight", "limited"]),
	"3-13": t("用完请放回原处。", "When you're done, please put it back.", ["直", "返", "存", "戻"], ["fix", "return (to a person)", "keep", "put back"]),
	"3-14": t("今天到这儿，下回下周继续。", "That's all for today; we'll continue next week.", ["付", "续", "向", "次"], ["attach", "continue", "face", "next"]),
	"3-15": t("交通费多少？", "How much is the transportation cost?", ["金", "代", "料", "费"], ["money", "charge", "fee", "expense"]),
	"3-16": t("请把这份资料复印 30 份。", "Please copy 30 of this handout.", ["束", "部", "组", "点"], ["bundle", "copies (bu)", "set", "point"]),
	"3-17": t("要装进纸袋吗？", "Shall I put it in a paper bag?", ["袋", "库", "材", "制"], ["bag", "storehouse", "material", "made of"]),
	"3-18": t("写着需要冷冻。", "It says it must be kept frozen.", ["必", "限", "要", "保"], ["must", "limit", "need", "keep"]),
	"3-19": t("再按拨号键。", "Press the dial button again.", ["浓", "再", "薄", "传"], ["thick", "again", "thin", "transmit"]),
	"3-20": t("做短期留学。", "I'll study abroad for a short term.", ["机", "气", "期", "式"], ["machine", "spirit", "period", "style"]),
	"4-1": t("接到合格通知很高兴。", "I was glad at the news I'd passed.", ["ごかく", "あいきゃく", "ごうかく", "こうかく"], ["wrong", "wrong", "gōkaku", "wrong"]),
	"4-2": t("货款从银行汇。", "I'll transfer the payment from the bank.", ["はりこみ", "おりこみ", "ふりこみ", "ほりこみ"], ["wrong", "wrong", "furikomi", "wrong"]),
	"4-3": t("我叫田中。", "My name is Tanaka.", ["もよおします", "もおします", "まうします", "もうします"], ["hold an event", "wrong", "wrong", "mōshimasu"]),
	"4-4": t("在找中级日语书。", "I'm looking for an intermediate Japanese book.", ["ちゅうきゅう", "ちょうきゅう", "じょうきゅう", "しょうきゅう"], ["chūkyū", "wrong", "jōkyū (advanced)", "shōkyū (beginner)"]),
	"4-5": t("去美国留学。", "I'll study in the United States.", ["まいこく", "めいこく", "べいこく", "みいこく"], ["wrong", "wrong", "beikoku", "wrong"]),
	"4-6": t("手机很方便。", "Cell phones are convenient.", ["びんり", "べんり", "ばんり", "べんに"], ["wrong", "benri", "wrong", "wrong"]),
	"4-7": t("货到了会通知您。", "We'll let you know when the goods come in.", ["にゅうこ", "にゅうに", "にゅうこ", "にゅうか"], ["stock in", "wrong", "stock in", "nyūka (arrival of goods)"]),
	"4-8": t("在白沙上走。", "I walked on white sand.", ["しお", "いし", "たね", "すな"], ["salt", "stone", "seed", "suna (sand)"]),
	"4-9": t("红茶里加牛奶喝。", "I drink black tea with milk.", ["こうさ", "ほんちゃ", "こうちゃ", "きっさ"], ["wrong", "bancha", "kōcha", "kissa"]),
	"4-10": t("把文件邮到分公司。", "I'll mail the documents to the branch office.", ["ししゃ", "ちしゃ", "じしゃ", "ぎしゃ"], ["shisha", "wrong", "jisha", "gisha"]),
	"4-11": t("付公交费。", "Pay the bus fare.", ["去", "私", "佛", "付"], ["leave", "I", "Buddha", "pay"]),
	"4-12": t("用宅配寄。", "Send it by home delivery.", ["配達", "宅配", "心配", "速达"], ["delivery", "home delivery", "worry", "express mail"]),
	"4-13": t("把孩子托给父母。", "I'll leave the child with my parents.", ["送到", "接受", "寄存", "继续"], ["deliver", "receive", "entrust", "continue"]),
	"4-14": t("这一带绿化很少。", "There's little greenery around here.", ["缘", "录", "绿", "线"], ["edge", "record", "green", "line"]),
	"4-15": t("连休打算去旅行。", "I plan to travel over the long weekend.", ["连", "次", "来", "残"], ["consecutive", "next", "coming", "remaining"]),
	"4-16": t("从广告知道有特卖。", "I learned about the sale from an ad.", ["告", "例", "记", "込"], ["announce", "example", "write", "include"]),
	"4-17": t("以定价一半以下买到了。", "I bought it for less than half the list price.", ["割", "値", "価", "达"], ["percent off", "price (ne)", "price (ka)", "reach"]),
	"4-18": t("消费税是百分之几？", "What percent is the consumption tax?", ["税", "性", "岁", "额"], ["tax", "nature", "years old", "amount"]),
	"4-19": t("你有几张 CD？", "How many CDs do you have?", ["册", "枚", "本", "部"], ["books", "flat things", "long things", "copies"]),
	"4-20": t("大型卡车出了事故。", "A large truck caused an accident.", ["形", "倍", "型", "级"], ["shape", "times", "model/type", "class"]),
}
