# key: "w1d1-1" -> [cn, en]
DAILY = {
	"w1d1-1": ["日本酒是用米酿的。", "Sake is made from rice."],
	"w1d1-2": ["在超市各买了一个苹果和一个橘子。", "I bought one apple and one mandarin each at the supermarket."],
	"w1d1-3": ["我一周去三次健身房。", "I go to the gym three times a week."],
	"w1d1-4": ["山田：“田中，那个包真好看。在哪儿买的？”田中：“是日本做的，不过是我去夏威夷时买的。”", "Yamada: “Tanaka, that bag is lovely. Where did you buy it?” Tanaka: “It was made in Japan, but I bought it when I went to Hawaii.”"],
	"w1d1-5": ["A：“今天也很冷啊。”B：“是啊。不过没有昨天那么冷。”", "A: “It's cold today too.” B: “Yes. But it's not as cold as yesterday.”"],
	"w1d2-1": ["明天要交的报告作业一页都还没写完。", "I haven't even finished one page of tomorrow's report."],
	"w1d2-2": ["山田：“这个真好吃。是田中做的吗？”田中：“对，连我都会做，所以很简单。”", "Yamada: “This is delicious. Did you make it, Tanaka?” Tanaka: “Yes — even I can make it, so it was easy.”"],
	"w1d2-3": ["A：“明天休息呢。打算做什么？”B：“打算做打扫卫生、洗衣服之类的。”", "A: “Tomorrow's a day off. What will you do?” B: “I plan to do things like cleaning and laundry.”"],
	"w1d2-4": ["孩子：“妈妈，今天想吃寿喜烧。”母亲：“肉有，可是鸡蛋只剩一个了，明天再吃吧。”", "Child: “Mom, I want sukiyaki today.” Mother: “We have meat, but there's only one egg, so tomorrow.”"],
	"w1d2-5": ["今年暑假我想去哪儿旅行一下。", "I'm thinking of taking a trip somewhere this summer."],
	"w1d3-1": ["我的公寓离车站远，房间也小。", "My apartment is far from the station, and the room is small too."],
	"w1d3-2": ["A：“又胖了……”B：“因为你净吃甜的啊。”", "A: “I've put on weight again…” B: “That's because you keep eating nothing but sweets.”"],
	"w1d3-3": ["今天我想在 8 点之前回到家。", "I want to get home by 8 today."],
	"w1d3-4": ["母亲：“好了，快睡觉。”孩子：“等这个游戏结束，再等一下。”", "Mother: “Come on, go to bed.” Child: “Wait a bit until this game finishes.”"],
	"w1d3-5": ["A：“新老师怎么样？”B：“又漂亮又温柔，我超喜欢。”", "A: “How's the new teacher?” B: “She's pretty and kind — I love her.”"],
	"w1d4-1": ["上厕所的工夫，电车开走了。", "While I was in the restroom, the train left."],
	"w1d4-2": ["A：“对不起来晚了。等很久了吗？”B：“没有，我也刚到。”", "A: “Sorry I'm late. Did you wait long?” B: “No, I just got here too.”"],
	"w1d4-3": ["山田：“喂，我是山田，请找史密斯。”田中：“不好意思，史密斯现在正在开会。”", "Yamada: “Hello, this is Yamada. May I speak to Smith?” Tanaka: “Sorry — Smith is in a meeting now.”"],
	"w1d4-4": ["A：“吃蛋糕吗？”B：“刚吃完饭，肚子饱了，所以等会儿再吃。”", "A: “Want some cake?” B: “I just ate, so I'm full. I'll have it later.”"],
	"w1d4-5": ["A：“那个是在哪儿买的？”B：“去年去意大利的时候买的。”", "A: “Where did you buy that?” B: “I bought it when I went to Italy last year.”"],
	"w1d5-1": ["脚疼，已经走不动了。", "My feet hurt so much I can't walk anymore."],
	"w1d5-2": ["A：“啊，来邮件了。”B：“不行。不能一边开车一边看手机。”", "A: “Oh, I got an email.” B: “Don't. You can't look at your phone while driving.”"],
	"w1d5-3": ["A：“考试考得怎么样？”B：“不好，明明昨晚通宵复习了还是没考好。”", "A: “How was the exam?” B: “Not good. I studied all night and still couldn't do it.”"],
	"w1d5-4": ["A：“打车的话赶得上吗？”B：“这一带出租车也少，还是跑着去吧。”", "A: “If we take a taxi, will we make it?” B: “There aren't many taxis around here, so let's run.”"],
	"w1d5-5": ["请不要穿着 T 恤之类的衣服进泳池。", "Please don't go in the pool still wearing a T-shirt or other clothes."],
	"w1d6-1": ["这台电脑有时会死机。", "This computer freezes from time to time."],
	"w1d6-2": ["我晚上不喝咖啡和茶。", "I make it a rule not to drink coffee or tea at night."],
	"w1d6-3": ["A：“这里的午餐哪一种都好吃。”B：“是吗。那我要汉堡午餐。”", "A: “Any of the lunches here are good.” B: “Really? Then I'll have the hamburger lunch.”"],
	"w1d6-4": ["A：“令堂身体好吗？”B：“说起来，大概一年前开始就不太好了。”", "A: “How is your mother?” B: “Well, she hasn't been very well for about a year.”"],
	"w1d6-5": ["母亲：“便当我抓紧做，等一下。”孩子：“要迟到了，快点。”", "Mother: “I'll make the bento quickly, wait.” Child: “We'll be late — hurry up.”"],
	"w2d1-1": ["下周之内必须把学费交了。", "I have to pay the tuition within next week."],
	"w2d1-2": ["可以看那个书架上的漫画吗？", "May I read the manga on that bookshelf?"],
	"w2d1-3": ["A：“明天是公布考试结果的日子呢。”B：“是啊。要是考上就好了……”", "A: “Tomorrow they announce the exam results.” B: “Yes. I hope I passed…”"],
	"w2d1-4": ["学生：“对不起，报告忘在家里了。明天带来。”老师：“明天也行，但请在 10 号之前交上来。”", "Student: “Sorry, I left the report at home. I'll bring it tomorrow.” Teacher: “Tomorrow is fine, but please turn it in by the 10th.”"],
	"w2d1-5": ["A：“这把剪刀不锋利啊。”B：“得买把新的了。”", "A: “These scissors don't cut.” B: “We'll have to buy a new pair.”"],
	"w2d2-1": ["请提前买好派对用的啤酒。", "Please buy beer ahead of time for the party."],
	"w2d2-2": ["冰箱里的啤酒全喝光了。", "I drank all the beer that was in the fridge."],
	"w2d2-3": ["A：“从车站怎么去？”B：“啊，公交车刚走，打车去吧。”", "A: “How do we get there from the station?” B: “Ah, the bus just left, so let's take a taxi.”"],
	"w2d2-4": ["山田：“喂，对不起。出了车祸，大概晚一小时，请别等我，先开始吧。”田中：“好的。”", "Yamada: “Sorry — I had a car accident and I'll be about an hour late. Please start without waiting for me.” Tanaka: “Understood.”"],
	"w2d2-5": ["A：“那边新开的餐厅去过了吗？”B：“去过了，不好吃，所以再也不去了。”", "A: “Have you been to that new restaurant?” B: “Yes, I tried it, but it wasn't good, so I won't go again.”"],
	"w2d3-1": ["我上小学的时候，姐姐经常帮我做作业。", "When I was in elementary school, my sister often helped me with homework."],
	"w2d3-2": ["小时候父亲经常陪我玩。", "When I was little, my father often played with me."],
	"w2d3-3": ["A：“下周日要不要去看电影？”B：“谢谢你邀请我。不过那天另有约……”", "A: “Want to see a movie next Sunday?” B: “Thanks for asking. But I have another plan that day…”"],
	"w2d3-4": ["中村老师又温柔，教得又仔细，所以很受欢迎。", "Ms. Nakamura is kind and teaches carefully, so she's popular."],
	"w2d3-5": ["A：“要不要我陪你去？”B：“田中已经给我画了地图，我一个人没问题。”", "A: “Shall I go with you?” B: “Tanaka drew me a map, so I'll be fine on my own.”"],
	"w2d4-1": ["我尽量不吃甜食。", "I try not to eat sweet things."],
	"w2d4-2": ["这是外国人学日语用的书。", "This is a book for foreigners to study Japanese."],
	"w2d4-3": ["A：“从家到车站近吗？”B：“有点远，但我尽量不坐公交，走着去。”", "A: “Is it close from home to the station?” B: “A bit far, but I make a point of walking instead of taking the bus.”"],
	"w2d4-4": ["A：“在日本的生活怎么样？”B：“能说日语之后就变有趣了。”", "A: “How is life in Japan?” B: “It became fun after I got able to speak Japanese.”"],
	"w2d4-5": ["医生让我一天吃三次这个药，饭后吃。", "The doctor told me to take this medicine three times a day, after meals."],
	"w2d5-1": ["这个用日语怎么说？", "How do you say this in Japanese?"],
	"w2d5-2": ["A：“我不想再和你说话了。”B：“请不要说那种话。”", "A: “I don't want to talk to you anymore.” B: “Please don't say things like that.”"],
	"w2d5-3": ["约翰那么努力，听说还是落榜了。", "John tried so hard, but I hear he still failed the exam."],
	"w2d5-4": ["A：“去哪儿吃饭？”B：“车站附近那家叫『いろり』的居酒屋怎么样？”", "A: “Where shall we eat?” B: “How about the izakaya called Irori right near the station?”"],
	"w2d5-5": ["孩子：“我想住有泳池的房子。”父亲：“爸爸再怎么工作也买不起那样的房子。”", "Child: “I want to live in a house with a pool.” Father: “No matter how hard I work, I can't buy a house like that.”"],
	"w2d6-1": ["那儿危险，晚上最好别去。", "It's dangerous there, so you'd better not go at night."],
	"w2d6-2": ["今天的事最好别跟田中说。", "I think it's better not to tell Tanaka about today."],
	"w2d6-3": ["母亲：“还要玩到什么时候？快点睡觉。”孩子：“好——。”", "Mother: “How long are you going to play games? Go to bed.” Child: “Okaaay.”"],
	"w2d6-4": ["A：“这就要回去了？”B：“对，爸爸说必须 9 点之前到家。”", "A: “You're leaving already?” B: “Yes — Dad told me to be home by 9.”"],
	"w2d6-5": ["A：“烟戒掉了吗？”B：“没有，妻子每天也说‘戒掉’，可还是戒不了……”", "A: “Did you quit smoking?” B: “No. My wife tells me every day to quit, but I can't…”"],
	"w3d1-1": ["今天是星期天，不知道那家店开不开。", "It's Sunday, so I don't know whether that shop is open."],
	"w3d1-2": ["酒和烟都戒掉是很难的。", "Giving up both alcohol and cigarettes is hard."],
	"w3d1-3": ["A：“在找什么？”B：“手机，不知道放哪儿了……”", "A: “What are you looking for?” B: “My phone — I don't know where I put it…”"],
	"w3d1-4": ["A：“吉他变厉害了啊。”B：“谢谢。不过要弹出这首曲子花了三个月。”", "A: “You've gotten good at guitar.” B: “Thanks. But it took three months to get able to play this piece.”"],
	"w3d1-5": ["妻子：“去站前超市买番茄回来。”丈夫：“诶？那家超市倒了你不知道吗？”", "Wife: “Buy tomatoes at the supermarket by the station.” Husband: “What? You don't know that supermarket closed down?”"],
	"w3d2-1": ["这张卡谁都能做。", "Anyone can make this card."],
	"w3d2-2": ["小孩比大人更能听见高音。", "Children can hear higher sounds than adults."],
	"w3d2-3": ["A：“那是富士山吗？”B：“不是，从这儿看不见。”", "A: “Is that Mt. Fuji?” B: “No, you can't see it from here.”"],
	"w3d2-4": ["看鱼游泳很开心。", "It's fun to watch the fish swimming."],
	"w3d2-5": ["A：“好像能听见猫还是什么在哭。”B：“啊，那是隔壁的宝宝。”", "A: “I can hear a cat or something crying.” B: “Oh, that's the neighbor's baby.”"],
	"w3d3-1": ["那么用功，考试却没考上。", "I studied so hard, but I still didn't pass the exam."],
	"w3d3-2": ["妹妹怎么吃都不胖。", "No matter how much my sister eats, she doesn't gain weight."],
	"w3d3-3": ["A：“为什么搬家？”B：“因为找到了又大又便宜的地方。”", "A: “Why are you moving?” B: “Because we found a place that's bigger and cheaper.”"],
	"w3d3-4": ["A：“明天 3 点我大概赶不到。”B：“没关系，晚到也行，我等着。”", "A: “I don't think I can make it by 3 tomorrow.” B: “That's fine — even if you're late, I'll wait.”"],
	"w3d3-5": ["A：“好好向田中道歉了吗？”B：“道了，可怎么道歉他都不原谅，真愁人。”", "A: “Did you properly apologize to Tanaka?” B: “Yes, but no matter how much I apologize he won't forgive me.”"],
	"w3d4-1": ["从这儿去东京站有很多走法。", "There are many ways to get from here to Tokyo Station."],
	"w3d4-2": ["早上是晴天。可是中午突然下起雨来。", "It was sunny in the morning. But then it suddenly started raining at noon."],
	"w3d4-3": ["A：“这家店总是很挤。因为又便宜又好吃吧。”B：“对，而且份量也大，男的也很爱来。”", "A: “This place is always packed. Cheap and tasty, right?” B: “Yes, and on top of that the portions are big, so it's popular with men too.”"],
	"w3d4-4": ["客人：“这个也是一千日元吗？”店员：“对，大小不同，价钱一样。”", "Customer: “Is this a thousand yen too?” Clerk: “Yes — the size is different, but the price is the same.”"],
	"w3d4-5": ["A：“史密斯现在回国了。”B：“这样啊。所以打电话也不接、发邮件也不回。”", "A: “Smith is back in his country now.” B: “Ah. That's why he doesn't pick up or reply to email.”"],
	"w3d5-1": ["真希望暑假快点来。", "I want summer vacation to come soon."],
	"w3d5-2": ["不好意思，能再说慢一点吗？", "Sorry, could you say that a little more slowly?"],
	"w3d5-3": ["A：“明天星期天，没什么事做。”B：“去动物园怎么样？一个人去也开心。”", "A: “It's Sunday tomorrow and I have nothing to do.” B: “How about the zoo? It's fun even alone.”"],
	"w3d5-4": ["A：“田中老师大概多少岁？”B：“他说别问年龄，所以我觉得不年轻了。”", "A: “About how old is Tanaka-sensei?” B: “He said he doesn't want people asking his age, so I don't think he's young.”"],
	"w3d5-5": ["母亲：“小健，今天想去哪儿？”健：“有想买的书，所以想去书店。”", "Mother: “Ken, where do you want to go today?” Ken: “There's a book I want you to buy me, so I want to go to the bookstore.”"],
	"w3d6-1": ["胖了，所以打算减肥。", "I've gained weight, so I'm thinking of going on a diet."],
	"w3d6-2": ["天气预报说明天下午会晴。", "The forecast said it will clear up tomorrow afternoon."],
	"w3d6-3": ["A：“怎么办？打车去？”B：“有时间，走着去吧。”", "A: “What should we do? Take a taxi?” B: “We have time, so let's walk.”"],
	"w3d6-4": ["A：“那是新包吧。”B：“嗯，本来不打算买的，可是想要就买了。”", "A: “That's a new bag, right?” B: “Yes. I wasn't going to buy one, but I wanted it and ended up buying it.”"],
	"w3d6-5": ["A：“山田君经常请假呢。”B：“是啊。我正想跟他说别再请假了。”", "A: “Yamada takes a lot of days off.” B: “Yes. I'm thinking of telling him to stop taking time off.”"],
	"w4d1-1": ["如果热的话，请把窗户打开。", "If it's hot, please open the window."],
	"w4d1-2": ["要是去中国，请帮我买茶回来。", "If you're going to China, please buy some tea."],
	"w4d1-3": ["A：“请问这附近有便利店吗？”B：“那个拐角往右走一点，右边就有。”", "A: “Is there a convenience store around here?” B: “Turn right at that corner and go a little — it's on the right.”"],
	"w4d1-4": ["A：“考试结果马上就出来了。”B：“对。要是没考上，明年还打算再考。”", "A: “We'll know the exam results soon.” B: “Yes. If I don't pass, I plan to take it again next year.”"],
	"w4d1-5": ["丈夫：“我去一下书店。”妻子：“哦。既然出门，回来时能不能买鸡蛋？”", "Husband: “I'm just going to the bookstore.” Wife: “Oh. If you're going out, could you buy eggs on the way back?”"],
	"w4d2-1": ["这头狮子还像个宝宝呢。", "This lion still looks like a baby."],
	"w4d2-2": ["这台电脑有点不对劲。说不定坏了。", "This computer feels off. It might be broken."],
	"w4d2-3": ["A：“听说小林回国了。”B：“嗯，大概一周前。真寂寞。”", "A: “I hear Lin went back to China.” B: “Yes, about a week ago. It's lonely now.”"],
	"w4d2-4": ["新闻说，来自越南的留学生今后还会增加。", "The news said the number of students from Vietnam will probably keep growing."],
	"w4d2-5": ["妻子：“今天洗衣服怎么办？”丈夫：“明天好像天气不好，今天先洗了比较好。”", "Wife: “What about laundry today?” Husband: “It looks like bad weather tomorrow, so you'd better do it today.”"],
	"w4d3-1": ["昨天走太多，脚疼。", "I walked too much yesterday and my feet hurt."],
	"w4d3-2": ["听说便宜电脑容易坏，不知道行不行。", "I heard cheap computers break easily — will it be okay?"],
	"w4d3-3": ["A：“这螃蟹真好吃。”B：“是吗。难剥又难吃干净，我不太喜欢。”", "A: “This crab is delicious.” B: “Is it? It's hard to eat, so I don't like it much.”"],
	"w4d3-4": ["医生：“脚怎么样？还疼吗？”病人：“一直走的话还会疼，不过现在没事了。”", "Doctor: “How's the foot? Still hurt?” Patient: “If I keep walking it starts to hurt, but it's fine now.”"],
	"w4d3-5": ["开始学唱歌之后，每天都变有趣了。", "Every day has been more fun since I started learning to sing."],
	"w4d4-1": ["这游戏看起来很好玩。也让我玩吧。", "That game looks fun. Let me play too."],
	"w4d4-2": ["小时候被狗咬过。", "When I was a child I was bitten by a dog."],
	"w4d4-3": ["A：“孩子看起来很健康。”B：“是啊，不过婴儿时期老生病，让我担心坏了。”", "A: “Your child looks so healthy.” B: “Yes, but as a baby they were always sick and I was made to worry a lot.”"],
	"w4d4-4": ["A：“这椅子真好坐。”B：“听说这是欧洲学校在用的。”", "A: “This chair is comfortable.” B: “I hear this is the kind used in schools in Europe.”"],
	"w4d4-5": ["A：“山田从店里辞职了？”B：“听说因为迟到太多被辞退了。”", "A: “Did Yamada leave the shop?” B: “I hear he was made to quit because he was late so often.”"],
	"w4d5-1": ["车停在这儿没关系吗？", "Is it okay to leave the car parked here?"],
	"w4d5-2": ["上次地震里房子塌了的人很多。", "A lot of people had their houses collapse in the recent earthquake."],
	"w4d5-3": ["出门时忘了锁门。", "I forgot to lock the house when I left."],
	"w4d5-4": ["A：“今天天气真好。”B：“是啊。不过入夏以后会越来越热吧。”", "A: “Nice weather today.” B: “Yes. But it'll keep getting hotter as summer comes.”"],
	"w4d5-5": ["A：“知道约翰的邮箱吗？”B：“给我的名片上好像写着。”", "A: “Do you know John's email?” B: “I think it was written on the card he gave me.”"],
	"w4d6-1": ["约翰为什么没来上学呢？", "I wonder why John was absent from school."],
	"w4d6-2": ["生日怎么还不来啊。", "I wish my birthday would come soon."],
	"w4d6-3": ["A：“昨天的牛排真好吃啊。”B：“在哪儿吃的？”", "A: “That steak yesterday was so good.” B: “Where did you eat it?”"],
	"w4d6-4": ["A：“来晚了。怎么了？”B：“早上肚子不舒服，不过现在没事了。”", "A: “You're late. What happened?” B: “My stomach was bad this morning, but I'm fine now.”"],
	"w4d6-5": ["A：“咦？不吃蛋糕吗？”B：“想吃，可是现在在减肥。”", "A: “Huh? You're not having cake?” B: “I want to, but I'm on a diet right now.”"],
}
