def t(cn, en, opts_cn=None, opts_en=None, point="", point_en=""):
	return {"cn": cn, "en": en, "opts_cn": opts_cn or [], "opts_en": opts_en or [], "point": point, "point_en": point_en}


VOCAB_EXAM = {
	"4-1": t("见到想见的人，很高兴。", "I'm happy I got to see the person I wanted to see.", ["温柔", "凉快", "悲伤", "高兴"], ["kind", "cool", "sad", "happy"]),
	"4-2": t("要吃饭了，请把桌子擦一下。", "We're going to eat, so please wipe the table.", ["扫", "擦", "拉/弹", "吸"], ["sweep", "wipe", "pull/play", "suck"]),
	"4-3": t("请脱掉鞋，换上拖鞋。", "Please take off your shoes and change into slippers.", ["换衣服", "换乘", "换鞋", "更换（放入）"], ["change clothes", "transfer", "change footwear", "replace"]),
	"4-4": t("到得早，所以先买点东西再去。", "I arrived early, so I'll do a little shopping first.", ["到了", "沾上", "听了", "穿了（下装）"], ["arrived", "got on", "heard", "put on"]),
	"4-5": t("如果生病了，请不要勉强。", "If you're sick, please don't overdo it.", ["受伤", "感冒", "勉强/过度", "变成"], ["injury", "cold", "overdoing it", "become"]),
	"4-6": t("早上起来后冲个澡。", "I take a shower after I get up.", ["浇", "淋/冲", "取", "擦"], ["pour on", "take (a shower)", "take", "wipe"]),
	"4-7": t("这项训练很严，但很有用。", "This training is tough, but it's useful.", ["严格", "寂寞", "凉快", "正确"], ["strict", "lonely", "cool", "correct"]),
	"4-8": t("已经习惯日本了。", "I've gotten used to Japan.", ["变成了", "学了", "排队了", "习惯了"], ["became", "learned", "lined up", "got used to"]),
	"4-9": t("忘了锁门。", "I forgot to lock up.", ["藏", "锁着（自动）", "锁上", "停止"], ["hide", "be locked", "lock", "stop"]),
	"4-10": t("家人要来日本，所以去机场接。", "My family is coming to Japan, so I'll go to the airport to meet them.", ["去接", "去送", "带着", "拿着"], ["pick up", "see off", "take along", "carry"]),
	"4-11": t("不懂的词就查词典。", "I look up words I don't know in the dictionary.", ["用词典查不懂的词", "给不懂的词划线", "把不懂的词写进词典", "给不懂的词打勾"], ["look them up in a dictionary", "underline them", "write them in a dictionary", "check them"]),
	"4-12": t("擦窗玻璃。", "I polish the window glass.", ["把玻璃弄碎", "把玻璃弄干净", "把玻璃洗干净", "把玻璃扫干净"], ["break it clean", "make it clean", "wash it clean", "sweep it clean"]),
	"4-13": t("这个名字很少见。", "This name is unusual.", ["这个名字很多", "这个名字很受欢迎", "这个名字很少", "这个名字让人害羞"], ["there are many", "it's popular", "there are few", "it's embarrassing"]),
	"4-14": t("虽然下雨，没办法，还是出门。", "It's raining, but there's nothing for it, so I'll go out.", ["不想出门但还是去", "没伞所以晚一点去", "必须出门", "雨马上停所以出门"], ["don't want to but will go", "no umbrella so later", "have to go out", "it'll stop soon"]),
	"4-15": t("那部漫画有点让人不舒服。", "That manga is a bit creepy.", ["不太有趣", "看起来让人恶心", "看了也不太懂", "不太受欢迎"], ["not very funny", "makes you feel uneasy", "hard to follow", "not popular"]),
	"4-16": t("每天记新单词。", "I memorize new words every day.", ["每天记新词", "总是记着家里人", "觉得日本菜好吃叫おぼえる", "想起来叫おぼえる"], ["memorize new words", "remember family", "think food is tasty", "recall something forgotten"]),
	"4-17": t("舞者在转圈。", "The dancer is spinning around.", ["舞者转圈", "下一个拐角往左转（应为まがる）", "把音量旋钮往右转", "过了桥一直走"], ["spinning", "turn left at the corner", "turn it to the right", "cross the bridge"]),
	"4-18": t("把抽屉里收拾整齐。", "I tidy the inside of the desk drawer.", ["用冰箱收拾啤酒", "洗脸后收拾牙", "收拾抽屉", "用洗衣机收拾衬衫"], ["put beer away in the fridge", "tidy teeth", "tidy the drawer", "tidy a shirt in the washer"]),
	"4-19": t("勉强过度，结果生病了。", "I overdid it and got sick.", ["家里有还再买是むり", "勉强过度生病了", "我对猪肉むり", "むり所以别担心"], ["buying extras is むり", "overdid it and got sick", "pork is むり", "it's むり so don't worry"]),
	"4-20": t("困的时候喝浓茶。", "When I'm sleepy I drink strong tea.", ["困了喝浓茶", "这本浓书有多少页", "因为浓所以开灯", "那条河很浓很危险"], ["drink strong tea", "a thick book", "it's dark so turn on the light", "the river is deep"]),
	"5-1": t("往洗衣机里放洗涤剂。", "I put detergent in the washing machine.", ["进入", "放入", "出来", "拿出"], ["go in", "put in", "come out", "take out"]),
	"5-2": t("车站前开了一家超市。", "A supermarket was built in front of the station.", ["建成了/开业了", "盖了（他动词）", "出生了", "做了"], ["was built / opened", "built (transitive)", "was born", "made"]),
	"5-3": t("往面包上涂黄油再吃。", "I spread butter on the bread and eat it.", ["浇", "涂", "用", "揉"], ["pour", "spread", "use", "knead"]),
	"5-4": t("工作还没做完，请先回去吧。", "Work is still left, so please go home first.", ["还剩着", "结束了", "多余了", "做着"], ["is left", "finished", "left over", "doing"]),
	"5-5": t("跑的话就能赶上下一班公交。", "If you run, you can catch the next bus.", ["上去的话", "跳舞的话", "能做的话", "跑的话"], ["if you go up", "if you dance", "if you can", "if you run"]),
	"5-6": t("好好学习了，今年一定能合格。", "I studied hard, so I'll surely pass this year.", ["一直", "终于", "一定", "更加"], ["all along", "finally", "surely", "more"]),
	"5-7": t("“啊，橡皮掉了。给你。”“谢谢。”", "“Oh, your eraser fell. Here.” “Thanks.”", ["消失了", "弄坏了", "弄掉了", "掉了"], ["disappeared", "broke it", "dropped it", "fell"]),
	"5-8": t("系好安全带，安全驾驶吧。", "Fasten your seatbelt and drive safely.", ["安全的", "危险的", "遗憾的", "结实的"], ["safe", "dangerous", "regrettable", "sturdy"]),
	"5-9": t("往墙上贴海报。", "I put a poster on the wall.", ["涂", "贴", "复印/印", "按"], ["paint", "stick", "copy", "press"]),
	"5-10": t("最近写信的人变少了。", "Lately fewer people write letters.", ["贴了", "下了", "减少了", "涂了"], ["stuck", "fell (rain)", "decreased", "painted"]),
	"5-11": t("过了马路那边有医院。", "There's a hospital just after you cross the road.", ["马路对面有医院", "马路这边有医院", "拐弯就有医院", "马路尽头有医院"], ["across the road", "on this side", "if you turn", "where the road ends"]),
	"5-12": t("不知道票掉在哪儿了。", "I don't know where I dropped the ticket.", ["不知道谁给的票", "不知道找票的地方", "不知道把票弄丢在哪儿", "不知道票掉没掉"], ["who gave it", "where I looked", "where I lost it", "whether it fell"]),
	"5-13": t("这里的灯是自动的。", "The lights here are automatic.", ["开开关关都没关系", "不用自己开关", "不许开关", "不能开关"], ["okay to switch", "no need to switch", "must not switch", "can't switch"]),
	"5-14": t("我在找兼职。", "I'm looking for a part-time job.", ["想做兼职", "弄丢了兼职", "找不到兼职", "不能兼职"], ["I want a job", "I dropped a job", "I don't find one", "I mustn't work"]),
	"5-15": t("走错路了。", "I took the wrong road.", ["正确的路做成了", "查了正确的路", "问了正确的路", "没有走正确的路"], ["the right road was made", "I looked up the road", "I asked the road", "I didn't take the right road"]),
	"5-16": t("冷，所以戴上毛线帽。", "It's cold, so I put on a knit hat.", ["苹果整个かぶる", "雨天穿这双鞋叫かぶる", "冷了戴毛线帽", "一跑杯子里的水かぶる"], ["eat an apple whole", "wear these shoes", "put on a knit hat", "water spills"]),
	"5-17": t("昨天工作做到很晚。", "I worked quite late yesterday.", ["准备这么多就ずいぶん了", "ずいぶん六点起床", "明天ずいぶん下雨", "昨天工作到很晚"], ["that's ずいぶん enough", "I ずいぶん get up at 6", "it'll ずいぶん rain", "worked quite late"]),
	"5-18": t("不认识的人帮我捡起了钱包。", "A stranger picked up my wallet for me.", ["忙得ひろう了", "钥匙在那儿ひろう着", "陌生人帮我捡了钱包", "房间又亮又ひろう"], ["got very ひろう", "the key is ひろう", "picked up my wallet", "the room is ひろう"]),
	"5-19": t("想拍照可这孩子动来动去，真没办法。", "I want to take a photo but this child keeps moving.", ["孩子动来动去不好拍", "下周搬到隔壁镇叫うごく", "笔记本可以うごく", "开会请把椅子うごく"], ["the child is moving", "move to the next town", "you may うごく my notebook", "うごく the chairs"]),
	"5-20": t("时间有多，再检查一遍吧。", "If we have time left, let's check again.", ["时间有多再检查", "饮料あまったら去买", "工作あまったら通宵做", "别勉强吃、あまったらいい"], ["if time is left", "if drinks あまる, buy more", "if work あまる, stay up", "don't force yourself to eat"]),
	"6-1": t("“肚子饿了呢。”“啊，已经过 12 点了。”", "“I'm hungry.” “Oh, it's already past 12.”", ["过了", "饿了", "到了", "穿过了"], ["passed", "got hungry", "became", "went through"]),
	"6-2": t("在院子里种树。", "I'll plant a tree in the garden.", ["立/盖", "种", "养大", "爬"], ["stand/build", "plant", "raise", "climb"]),
	"6-3": t("“明天去看电影吗？”“明天不方便。”", "“Want to see a movie tomorrow?” “Tomorrow is inconvenient.”", ["场合", "方便/安排", "心情", "计划"], ["case", "convenience", "mood", "plan"]),
	"6-4": t("“怎么了，大家都在吵闹。”“着火了。”", "“What's going on? Everyone's making a racket.” “There's a fire.”", ["坐着", "摸着", "吵闹", "欺负"], ["sitting", "touching", "making a fuss", "bullying"]),
	"6-5": t("考上大学，作为祝贺收到了一个包。", "I got a bag as a congratulations present for getting into university.", ["祝贺", "感谢", "探望", "关系"], ["celebration", "thanks", "visit a sick person", "relation"]),
	"6-6": t("那把伞折了，不能用。", "That umbrella is broken, so I can't use it.", ["碎了", "折了", "湿了", "习惯了"], ["shattered", "snapped", "got wet", "got used to"]),
	"6-7": t("水开了以后，请把这些菜放进去。", "When the water boils, please put these vegetables in.", ["开了的话", "浇了的话", "碎了的话", "煮了的话"], ["if it boils", "if you pour", "if it breaks", "if you cook rice"]),
	"6-8": t("“感冒怎么样了？”“托您的福，好多了。”", "“How's your cold?” “Thanks to you, much better.”", ["好久不见", "高兴地", "真可怜", "托您的福"], ["it's been a while", "gladly", "that's too bad", "thanks to you"]),
	"6-9": t("重要的笔记本丢了，正发愁。", "I lost an important notebook and I'm in trouble.", ["相信", "被抓住", "为难", "享受"], ["believe", "be caught", "be in trouble", "enjoy"]),
	"6-10": t("以前常喝酒，现在不太喝了。", "I used to drink a lot; now I don't drink much.", ["从前", "点心", "刚才", "最近"], ["in the past", "sweets", "just now", "lately"]),
	"6-11": t("我在大学工作。", "I work at a university.", ["在大学学习", "在大学找工作", "在大学上班", "住在大学"], ["studying there", "looking for work", "working there", "living there"]),
	"6-12": t("我听老师说的。（うかがう＝听，敬语）", "I heard it from the teacher.", ["从老师那儿听说", "向老师提问", "老师来见我", "老师有话"], ["heard from the teacher", "asked the teacher", "the teacher came", "there was a talk"]),
	"6-13": t("洗完衣服会响铃。", "When the laundry finishes, a chime sounds.", ["声音听不见了", "铃在调查", "洗衣机关了", "用铃声通知"], ["the sound stops", "the chime investigates", "the machine stops", "it notifies you with a chime"]),
	"6-14": t("那个人偷了车。", "That person stole a car.", ["拿走了别人的车", "向别人借了车", "把车借给别人", "别人给了车"], ["took someone's car", "borrowed a car", "lent a car", "was given a car"]),
	"6-15": t("比较一下价格。", "I'll compare the prices.", ["排一排看哪个好", "问问多少钱", "检查大小颜色", "查哪个贵哪个便宜"], ["line them up", "ask the price", "check size and color", "see which is cheaper"]),
	"6-16": t("在车站前的咖啡店会合。", "We'll meet at the coffee shop in front of the station.", ["让家人和朋友まちあわせ", "在下一站和地铁まちあわせ", "在站前咖啡店会合", "向车站的人まちあわせ时间"], ["have family meet a friend", "meet the subway", "meet at the cafe", "ask the station staff"]),
	"6-17": t("一到冬天这里就会积雪。", "Snow piles up here in winter.", ["今年打算考 N4", "冬天这里会积雪", "每天攒一百日元叫つもる", "这部电影很つもる"], ["I intend to take N4", "snow piles up", "save 100 yen", "the movie is つもる"]),
	"6-18": t("妈妈在院子里养花。", "My mother grows flowers in the garden.", ["种的树在そだてている", "把鸡蛋そだてて加糖和黄油", "给猫そだてる什么吃的", "妈妈在院子里养花"], ["the tree is そだてている", "そだてる an egg", "そだてる food for the cat", "grows flowers"]),
	"6-19": t("昨天父母的信寄到了。", "A letter from my parents arrived yesterday.", ["昨天信到了", "把行李とどきました", "3 号线电车とどきました", "被陌生人叫名字很とどく"], ["the letter arrived", "I とどく the luggage", "the train とどく", "I was very とどく"]),
	"6-20": t("请别客气，吃吧。（めしあがる＝吃，尊敬语）", "Please help yourself.", ["请到里面めしあがる", "穿着漂亮外套めしあがっている", "我国也めしあがる生鱼", "别客气请用"], ["please めしあがる inside", "you're めしあがる a coat", "we also めしあがる raw fish", "please eat, don't hold back"]),
}

KANJI_EXAM = {
	"1-1": t("今晚月亮很亮。", "The moon is bright tonight.", ["こうや", "こんや", "こよい", "こんばん"], ["wrong", "konya (tonight)", "koyoi", "konban"]),
	"1-2": t("在邮局寄行李。", "I'll send a package at the post office.", ["にもつ", "にもの", "にぶつ", "にもち"], ["nimotsu", "wrong", "wrong", "wrong"]),
	"1-3": t("在暗处看书会伤眼睛。", "Reading in a dark place is bad for your eyes.", ["くらい", "くろい", "くれい", "くるい"], ["kurai (dark)", "kuroi (black)", "wrong", "wrong"]),
	"1-4": t("这位日本小说家在国外也很有名。", "This Japanese novelist is famous abroad too.", ["こせつか", "こせつや", "しょうせつか", "しょうせつや"], ["wrong", "wrong", "shōsetsuka", "wrong"]),
	"1-5": t("去年和家人旅行了两次。", "Last year I traveled with my family twice.", ["こねん", "きょねん", "きゅねん", "ことし"], ["wrong", "kyonen (last year)", "wrong", "this year"]),
	"1-6": t("今天下着雨，风也大。", "It's raining today, and the wind is strong too.", ["きょうい", "こわい", "つよい", "つおい"], ["wrong", "kowai (scary)", "tsuyoi (strong)", "wrong"]),
	"1-7": t("那位歌手的声音很低。", "That singer's voice is very low.", ["ひくい", "ひどい", "ふとい", "ほそい"], ["hikui (low)", "hidoi", "futoi", "hosoi"]),
	"1-8": t("“会开车吗？”“会，不过远的地方有点……”", "“Can you drive?” “Yes, but not far…”", ["ぐんてん", "ゆんてん", "うんでん", "うんてん"], ["wrong", "wrong", "wrong", "unten (driving)"]),
	"1-9": t("台风靠近了，请小心。", "A typhoon is approaching, so please be careful.", ["たいほん", "たいぷう", "たいふう", "だいふう"], ["wrong", "wrong", "taifū", "wrong"]),
	"1-10": t("要拍照了，请不要动。", "I'm taking a photo, so please don't move.", ["どかないで", "のかないで", "うごかないで", "いごかないで"], ["wrong", "wrong", "ugokanaide", "wrong"]),
	"1-11": t("这所学校是一百年前建的。", "This school was built a hundred years ago.", ["建", "道", "通", "进"], ["built", "road", "pass", "advance"]),
	"1-12": t("寒假去青森玩。", "I'll visit Aomori during winter vacation.", ["春假", "暑假", "秋假", "寒假"], ["spring break", "summer break", "autumn break", "winter break"]),
	"1-13": t("这个镇上没有医生。", "There is no doctor in this town.", ["道", "都", "市", "町"], ["road", "metropolis", "city", "town"]),
	"1-14": t("那栋楼是大使馆。", "That building is an embassy.", ["大使馆", "美术馆", "电影院", "图书馆"], ["embassy", "art museum", "cinema", "library"]),
	"1-15": t("这条街晚上也很热闹。", "This street is lively even at night.", ["夕", "晩", "夜", "昼"], ["evening", "evening", "night", "daytime"]),
	"1-16": t("下个月市民会堂有音乐会。", "There's a concert at the civic hall next month.", ["国民", "县民", "市民", "府民"], ["nationals", "prefectural citizens", "city residents", "fu residents"]),
	"1-17": t("怎么用，现在开始说明。", "I'll now explain how to use it.", ["作", "便", "利", "使"], ["make", "convenient", "profit", "use"]),
	"1-18": t("我家有三台电脑。", "There are three computers in my house.", ["体", "代", "台", "回"], ["body", "generation", "counter for machines", "times"]),
	"1-19": t("在超市买食品。", "I buy groceries at the supermarket.", ["物", "品", "饭", "集"], ["thing", "goods", "meal", "gather"]),
	"1-20": t("骑自行车在附近转一转。", "I ride around the neighborhood on a bicycle.", ["回", "同", "通", "进"], ["go around", "same", "pass along", "advance"]),
	"2-1": t("和服完全没有穿的机会。", "I never get a chance to wear Japanese clothes.", ["おふく", "わふく", "しふく", "きもの"], ["wrong", "wafuku", "wrong", "kimono reading"]),
	"2-2": t("坐地铁去上班。", "I go to work by subway.", ["ちはてつ", "じはでつ", "ちかてつ", "じかてつ"], ["wrong", "wrong", "chikatetsu", "wrong"]),
	"2-3": t("制定暑假计划。", "I'll make a summer-vacation plan.", ["けいが", "けかく", "けえが", "けいかく"], ["wrong", "wrong", "wrong", "keikaku"]),
	"2-4": t("有事，我先告辞了。", "I have something to do, so I'll excuse myself first.", ["よじ", "ようじ", "ゆじ", "ゆうじ"], ["wrong", "yōji (errand)", "wrong", "wrong"]),
	"2-5": t("电池没电了，有新的吗？", "The battery died — do you have a new one?", ["でんき", "でんし", "でんじ", "でんち"], ["electricity", "electron", "wrong", "denchi (battery)"]),
	"2-6": t("绿灯是前进，黄灯注意，红灯停下。", "Green means go, yellow caution, red stop.", ["つうい", "しゅうい", "ちゅうい", "じゅうい"], ["wrong", "wrong", "chūi (caution)", "wrong"]),
	"2-7": t("那人的脸记得，名字想不起来。", "I know the face but can't recall the name.", ["かわ", "かお", "こう", "こえ"], ["river/skin", "kao (face)", "wrong", "voice"]),
	"2-8": t("请教我这个词的发音方法。", "Please teach me how to pronounce this word.", ["しかた", "しほう", "しがた", "しよう"], ["shikata (way)", "wrong", "wrong", "wrong"]),
	"2-9": t("老师的包真重啊。", "The teacher's bag is heavy.", ["おむい", "おもい", "おおい", "じゅうい"], ["wrong", "omoi (heavy)", "ooi (many)", "wrong"]),
	"2-10": t("有意见的人请举手。", "If you have an opinion, please raise your hand.", ["いみ", "いけん", "いげん", "しつもん"], ["meaning", "iken (opinion)", "wrong", "question"]),
	"2-11": t("要上课了，进教室吧。", "Class is starting, so let's go into the classroom.", ["开始", "经过", "下（车）", "聚集"], ["begin", "pass", "get off", "gather"]),
	"2-12": t("要晚的时候请告诉我。", "Please let me know if you'll be late.", ["和", "知", "仕", "使"], ["harmony", "inform", "serve", "use"]),
	"2-13": t("寺庙的池子里有红色、黄色的鱼。", "There are red and yellow fish in the temple pond.", ["池", "地", "他", "洋"], ["pond", "ground", "other", "ocean"]),
	"2-14": t("研究日语。", "I research Japanese.", ["学习", "说明", "研究", "教育"], ["study", "explain", "research", "education"]),
	"2-15": t("我的大学是工业大学。", "My university is a university of technology.", ["工业", "产业", "行业", "高业"], ["industry/engineering", "industry", "wrong", "wrong"]),
	"2-16": t("家里的狗每天早上叫醒家人。", "Our dog wakes the family every morning.", ["别", "起", "光", "发"], ["separate", "wake", "light", "depart"]),
	"2-17": t("那本书请在一周以内还。", "Please return that book within a week.", ["以上", "以外", "以内", "以下"], ["or more", "except", "within", "or less"]),
	"2-18": t("我的话到此结束。", "That concludes what I have to say.", ["结束", "转", "代替", "发光"], ["end", "turn", "replace", "shine"]),
	"2-19": t("厨房里好像有什么声音。", "I hear some kind of sound from the kitchen.", ["歌", "事", "音", "首"], ["song", "matter", "sound", "neck"]),
	"2-20": t("这件行李很轻。", "This luggage is light.", ["宽", "轻", "粗", "冷"], ["wide", "light", "thick", "cold"]),
	"3-1": t("这周不方便，能改到下周吗？", "This week is inconvenient — could we make it next week?", ["とごう", "つごう", "とあい", "つあい"], ["wrong", "tsugō", "wrong", "wrong"]),
	"3-2": t("姐姐在花店工作。", "My older sister works at a flower shop.", ["はたらいて", "はだらいて", "はらだいて", "はらたいて"], ["hataraite", "wrong", "wrong", "wrong"]),
	"3-3": t("请一天吃三次这个药。", "Please take this medicine three times a day.", ["くつり", "くすり", "すくり", "つくり"], ["wrong", "kusuri", "wrong", "tsukuri"]),
	"3-4": t("请从 1、2、3、4 中选一个正确的。", "Choose the correct one from 1–4.", ["ただしい", "たらしい", "たろしい", "たのしい"], ["tadashii (correct)", "wrong", "wrong", "tanoshii (fun)"]),
	"3-5": t("食堂很挤，所以在教室吃午饭。", "The cafeteria is crowded, so I'll eat lunch in the classroom.", ["きゅうしつ", "きゅうちつ", "きょうしつ", "きょうちつ"], ["wrong", "wrong", "kyōshitsu", "wrong"]),
	"3-6": t("睡觉前必须做作业。", "I have to do my homework before bed.", ["しゅくだい", "しょくだい", "ちゅくだい", "ちょくだい"], ["shukudai", "wrong", "wrong", "wrong"]),
	"3-7": t("妹妹在收集世界各地的特产。", "My little sister collects souvenirs from around the world.", ["おみあげ", "おにあげ", "おみやげ", "おにやげ"], ["wrong", "wrong", "omiyage", "wrong"]),
	"3-8": t("请随便拿。", "Please take freely.", ["じゅう", "じょう", "じゆう", "じよう"], ["jū", "jō", "jiyū (free)", "wrong"]),
	"3-9": t("满屋子都是书，连坐的地方都没有。", "The whole room is full of books; I can't even sit.", ["へやちゅう", "へやじゅう", "ひやちゅう", "ひやじゅう"], ["wrong", "heyajū (throughout the room)", "wrong", "wrong"]),
	"3-10": t("过年回国。", "I'll go home for New Year.", ["しゅうがつ", "しょうげつ", "しゅうげつ", "しょうがつ"], ["wrong", "wrong", "wrong", "shōgatsu"]),
	"3-11": t("这道题很难，再复习一遍吧。", "This problem is hard, so let's review it once more.", ["门", "间", "问", "闻"], ["gate", "interval", "question", "hear"]),
	"3-12": t("这里有点不方便，但有森林，我喜欢。", "It's a bit inconvenient here, but I like the woods.", ["不便", "木便", "未便", "米便"], ["inconvenient", "wrong", "wrong", "wrong"]),
	"3-13": t("医院里请不要跑。", "Please don't run inside the hospital.", ["走（步行）", "足", "停", "跑"], ["walk", "foot", "stop", "run"]),
	"3-14": t("在银行借钱买了房子。", "I borrowed money from the bank and bought a house.", ["贷", "借", "质", "卖"], ["lend", "borrow", "pawn", "sell"]),
	"3-15": t("早上被鸟叫声叫醒。", "I wake up to birdsong in the morning.", ["音", "鸣", "声", "心"], ["sound", "cry/sing", "voice", "heart"]),
	"3-16": t("请在这边坐着等。", "Please sit here and wait.", ["侍", "持", "特", "待"], ["samurai", "hold", "special", "wait"]),
	"3-17": t("这把刀很锋利。", "This knife cuts well.", ["着", "黄", "切", "气"], ["wear", "yellow", "cut", "spirit"]),
	"3-18": t("没时间了，请快点。", "There's no time, so please hurry.", ["急", "忙", "跑", "乘"], ["hurry", "busy", "run", "ride"]),
	"3-19": t("部长的太太是位非常亲切的人。", "The manager's wife is a very kind person.", ["大切", "亲切", "新说", "亲说"], ["important", "kind", "wrong", "wrong"]),
	"3-20": t("那是自动门。", "That's an automatic door.", ["自动", "自働", "自転", "自同"], ["automatic", "wrong kanji", "rotation", "wrong"]),
}
