# Daily exercise sentence translations. Arrays follow each day's item order.
# Usage-of-the-word items (often n=4) translate the correct example sentence.

VOCAB = {
	"w4d1": [
		["下雨了，穿上长筒靴再走吧。", "It's raining, so let's put on rain boots and go."],
		["洗完手，用毛巾或手帕擦一下吧。", "After you wash your hands, wipe them with a towel or handkerchief."],
		["树上掉了很多叶子，所以扫一扫。", "Lots of leaves have fallen, so I'll sweep them."],
		["我总是大概 12 点肚子饿。", "I always get hungry around 12."],
	],
	"w4d2": [
		["朋友要回国了，我很寂寞。", "My friend is going back to their country, so I feel lonely."],
		["照片让人害羞，请不要拍。", "Photos are embarrassing, so please don't take any."],
		["看了新闻吃了一惊。", "I was surprised when I saw the news."],
		["出事故车过不去。没办法，走着去。", "There's an accident and cars can't get through. There's nothing for it, so I'll walk."],
	],
	"w4d3": [
		["踢足球把脚弄伤了。", "I hurt my foot playing soccer."],
		["把钟表的电池换一下。", "I'll replace the clock battery."],
		["戒烟是不可能的。", "It's impossible for me to quit smoking."],
		["到了车站请打电话，我去接你。", "Call me when you get to the station and I'll come pick you up."],
	],
	"w4d4": [
		["早上 7 点叫醒家人。", "I wake my family at 7 in the morning."],
		["把垃圾收起来扔掉。", "I collect the trash and throw it away."],
		["做出门的准备。", "I'm getting ready to go out."],
		["把桌上和抽屉里收拾整齐。", "I tidy the top of the desk and the drawers."],
	],
	"w4d5": [
		["请在那个红绿灯往左拐。", "Please turn left at that traffic light."],
		["危险，请不要碰那个。", "That's dangerous, so please don't touch it."],
		["日本的食物我还没习惯。", "I still haven't gotten used to Japanese food."],
		["昨天第一次吃了生鱼片。", "Yesterday I ate sashimi for the first time."],
	],
	"w4d6": [
		["隔壁的人太吵，睡不着。", "The neighbors are so noisy I can't sleep."],
		["那儿水太深，在这边游吧。", "It's deep there, so let's swim over here."],
		["弟弟身体很结实。", "My little brother is strong and healthy."],
		["这肉又硬又难吃。", "This meat is tough and tastes bad."],
	],
	"w5d1": [
		["下了这个楼梯往左走就有便利店。", "Go down these stairs and turn left — there's a convenience store."],
		["危险，把手从口袋里拿出来再走。", "It's dangerous, so take your hands out of your pockets when you walk."],
		["钱包里放进了钱。", "I put money in my wallet."],
		["就算不跑也赶得上那班电车。", "Even if we don't run, we'll make that train."],
	],
	"w5d2": [
		["那边跳舞的长头发是谁？", "Who's the long-haired person dancing over there?"],
		["那个人一边弹钢琴一边唱歌。", "That person is singing while playing the piano."],
		["那个学生非常认真。", "That student is very serious about studying."],
		["我长得像爸爸。", "I look like my father."],
	],
	"w5d3": [
		["过了桥一直走，左边就是小学。", "Cross the bridge and go straight — the elementary school is on the left."],
		["投币再按按钮，饮料就会出来。", "Put in money and press the button, and a drink comes out."],
		["邮件发来的文件打不开。", "I can't open the file they sent me by email."],
		["用这块橡皮就能擦干净。", "If you use this eraser, it comes off cleanly."],
	],
	"w5d4": [
		["剩下的沙拉放进冰箱。", "I'll put the leftover salad in the fridge."],
		["孩子们喜欢贴纸，往各种东西上贴。", "Kids love stickers and stick them on all kinds of things."],
		["用一千日元买东西，剩下一百日元。", "I bought something with 1,000 yen and had 100 yen left."],
		["往面包上涂果酱。", "I spread jam on the bread."],
	],
	"w5d5": [
		["最近小林同学不来学校。", "Lately Li hasn't been coming to school."],
		["太郎长这么大了啊。", "Taro, you've grown so much."],
		["爸爸早上起来一定慢跑。", "Dad always goes jogging when he gets up in the morning."],
		["没学习，果然考试没考好。", "I didn't study, so of course I couldn't do the test."],
	],
	"w5d6": [
		["走丢的孩子找到了，放心了。", "The missing child was found, so I felt relieved."],
		["游戏借给你，可别弄坏了。", "I'll lend you the game, but please don't break it."],
		["有人把票给我看，说“你掉了”。", "Someone showed me a ticket and said, “You dropped this.”"],
		["朋友帮我找到了兼职。", "A friend found a part-time job for me."],
	],
	"w6d1": [
		["周末有什么安排吗？", "Do you have any plans for the weekend?"],
		["明天下雨的话比赛取消。", "If it rains tomorrow, there's no game."],
		["大家一起唱卡拉 OK 玩得很开心。", "We all enjoyed karaoke together."],
		["明天我有点不方便。", "Tomorrow is a bit inconvenient for me."],
	],
	"w6d2": [
		["水大概几分钟开？", "About how many minutes until the water boils?"],
		["这套西装干洗要一周。", "Dry-cleaning this suit takes a week."],
		["我报电话号码，请记下来。", "I'll say the phone number, so please write it down."],
		["这房子是爸爸年轻时盖的。", "My father built this house when he was young."],
	],
	"w6d3": [
		["重要的盘子碎了。", "An important plate broke."],
		["偷了钻石逃走的人已经被抓住了。", "The person who stole the diamond and ran has already been caught."],
		["谁都不相信我说的话。", "Nobody believed what I said."],
		["外面有人在吵闹。", "Someone is making a racket outside."],
	],
	"w6d4": [
		["这个游戏是把黑白圆形棋子摆开来玩。", "This game is played by lining up round black and white pieces."],
		["我正在做出门准备，再等一下。", "I'm getting ready to go out, so wait a little longer."],
		["和上周比，这周更忙。", "Compared with last week, this week is busy."],
		["架子上摆着人偶。", "There are dolls displayed on the shelf."],
	],
	"w6d5": [
		["哥哥在计算机相关的公司上班。", "My older brother works at a computer-related company."],
		["下周计划搬到学校附近。", "I plan to move near the school next week."],
		["发出了感谢祝贺的明信片。", "I sent a postcard to thank them for the congratulations."],
		["买花去探望。", "I'll buy flowers and go visit them in the hospital."],
	],
	"w6d6": [
		["初次见面，我叫山田。", "How do you do? My name is Yamada."],
		["“打扰一下，我看一下票。……谢谢。”", "“Excuse me, I'll just check the ticket. … Thank you.”"],
		["社长，田中先生到了。", "President, Mr. Tanaka has arrived."],
		["我客气了一下，点心没怎么吃。", "I held back and didn't take many sweets."],
	],
}

KANJI = {
	"w1d1": [
		["想试试穿和服。", "I want to try wearing a kimono."],
		["感冒了。", "I caught a cold."],
		["公司在那栋楼里面。", "The company is inside that building."],
		["妈妈在厨房。", "Mom is in the kitchen."],
		["这家店的东西很贵。", "The goods at this shop are expensive."],
		["到了车站请打电话。", "Please call when you arrive at the station."],
		["下车之前付钱。", "I pay before I get off."],
		["这里是动物医院。", "This is an animal hospital."],
	],
	"w1d2": [
		["请 8 点在学校门前集合。", "Please gather in front of the school at 8."],
		["智能手机很方便。", "Smartphones are convenient."],
		["我们上同一所学校。", "We go to the same school."],
		["每天晚上都做到很晚作业。", "I do homework late every night."],
		["这一页做完就进入下一页吧。", "When this page is done, let's go on to the next."],
		["记住日语就马上用。", "Once I learn Japanese, I use it right away."],
		["写短文章。", "I write a short sentence."],
		["和日本朋友一起做了寿司。", "I made sushi with a Japanese friend."],
	],
	"w1d3": [
		["最近经常下雨啊。", "It's been raining a lot lately."],
		["明天晚上和朋友见面。", "I'm meeting a friend tomorrow evening."],
		["孩子们去远足了。", "The children went on a field trip."],
		["这里写着说明，请读一下。", "The explanation is written here, so please read it."],
		["这条裤子有点短。", "These pants are a little short."],
		["搬到附近了，请多关照。", "I just moved to the neighborhood. Nice to meet you."],
		["这孩子身体很弱。", "This child has a weak constitution."],
		["这里离车站远，不方便。", "This place is far from the station and inconvenient."],
	],
	"w1d4": [
		["那栋建筑很有名。", "That building is famous."],
		["晚饭吃什么好呢？", "What shall we have for dinner?"],
		["去车站接丈夫。", "I'm going to the station to meet my husband."],
		["在日本住了旅馆。", "I stayed at a Japanese inn."],
		["傍晚开始风会变大。", "The wind will get stronger from evening."],
		["请假没上课，所以抄了朋友的笔记。", "I missed class, so I copied a friend's notes."],
		["桌子正中间放着花。", "There are flowers in the middle of the table."],
		["想去外国旅行。", "I want to travel abroad."],
	],
	"w1d5": [
		["不喜欢学习，但喜欢运动。", "I hate studying, but I like sports."],
		["骑自行车去车站。", "I go to the station by bicycle."],
		["想建立一个温暖的家庭。", "I want to make a warm family."],
		["在市民泳池游泳。", "I swim at the municipal pool."],
		["大家一起去唱了卡拉 OK。", "We all went to karaoke and sang."],
		["有钱的话想盖房子。", "If I had the money, I'd like to build a house."],
		["这是家人的照片。", "This is a family photo."],
		["那个店员开朗又好人。", "That clerk is cheerful and nice."],
	],
	"w1d6": [
		["明天有点不方便。", "Tomorrow is a bit inconvenient."],
		["白天不在家。", "I'm not home during the day."],
		["都道府县一共 47 个。", "There are 47 prefectures in all."],
		["暑假去旅行。", "I'll travel during summer vacation."],
		["到了春天就去赏花。", "When spring comes, we'll go flower-viewing."],
		["冬天在山里滑雪。", "In winter I ski in the mountains."],
		["秋天水果很好吃。", "Fruit is delicious in autumn."],
		["东京都人很多。", "There are a lot of people in Tokyo."],
	],
	"w2d1": [
		["暑假去图书馆。", "I go to the library during summer vacation."],
		["有事，明天来不了。", "I have something to do, so I can't come tomorrow."],
		["那只表有点慢。", "That clock is a little slow."],
		["妈妈在准备饭。", "Mom is getting the meal ready."],
		["我总是坐地铁。", "I always use the subway."],
		["发烧了，所以请假不工作。", "I have a fever, so I'm taking off work."],
		["在网上看电影。", "I watch movies on the internet."],
		["不看地图就找不到路。", "I can't find the way unless I look at a map."],
	],
	"w2d2": [
		["全家人一起去旅行。", "The family is going on a trip."],
		["不要写在笔记本上，写在别的纸上。", "Don't write in the notebook — write on another sheet."],
		["那棵粗的树是什么树？", "What kind of tree is that thick one?"],
		["要不要在和室喝茶？", "Shall we have tea in the Japanese-style room?"],
		["有不认识的人打电话来。", "I got a call from someone I don't know."],
		["我去一趟区公所。", "I'm going to the ward office."],
		["看得见那边的蓝光吗？", "Can you see that blue light over there?"],
		["回国后想做用日语的工作。", "When I go home I want to do a job that uses Japanese."],
	],
	"w2d3": [
		["因为生病请假没上学。", "I missed school because I was sick."],
		["这台笔记本电脑真轻。", "This laptop is light, isn't it?"],
		["要搬到更宽敞的公寓。", "We're moving to a bigger apartment."],
		["明天要早起，先睡了。", "Tomorrow is early, so I'm going to bed."],
		["好，开始学习吧。", "All right, let's start studying."],
		["好热，请开空调。", "It's hot, so please turn on the air conditioner."],
		["公司几点结束？", "What time does the company finish?"],
		["家人都很健康。", "The whole family is well."],
	],
	"w2d4": [
		["明天有日语课。", "There's a Japanese class tomorrow."],
		["8 点从这里出发。", "We leave here at 8."],
		["那位是日语研究者。", "That person is a Japanese-language researcher."],
		["请告诉我地址。", "Please tell me your address."],
		["那条路在施工。", "That road is under construction."],
		["查一下词的意思。", "I'll look up the meaning of the word."],
		["听得见雨声。", "I can hear the sound of the rain."],
		["住在便利店附近。", "I live near a convenience store."],
	],
	"w2d5": [
		["房间号码是 102。", "The room number is 102."],
		["我妻子完全不懂日语。", "My wife doesn't understand Japanese at all."],
		["我妻子代我去。", "My wife will go in my place."],
		["派对穿什么样的西式衣服去？", "What kind of Western clothes will you wear to the party?"],
		["出租车费多少？", "How much was the taxi fare?"],
		["下一班电车进 3 号线。", "The next train will arrive at track 3."],
		["除了周六日以外我不在家。", "Except for Saturday and Sunday, I'm not home."],
		["去安全的地方吧。", "Let's go somewhere safe."],
	],
	"w2d6": [
		["请用黑色笔写。", "Please write with a black pen."],
		["兄弟姐妹有几个人？", "How many brothers and sisters do you have?"],
		["我有两个弟弟。", "I have two younger brothers."],
		["令妹身体好吗？", "How is your younger sister?"],
		["从早上开始头就一直疼。", "I've had a headache since morning."],
		["那种动物脖子很长。", "That animal has a long neck."],
		["那件毛衣颜色真好看。", "That sweater is a pretty color."],
		["宝宝最喜欢妈妈。", "The baby loves Mom the most."],
	],
	"w3d1": [
		["隔壁家的姐姐总是照顾妹妹。", "The older sister next door always looks after her little sister."],
		["从屋顶上看烟花吧。", "Let's watch the fireworks from the rooftop."],
		["哥哥在世界各地旅行。", "My older brother is traveling all over the world."],
		["在这儿买特产吧。", "Let's buy souvenirs here."],
		["那两个人是兄妹。", "Those two are brother and sister."],
		["这本书已经全部读完了。", "I've already read this whole book."],
		["接下来讲讲我们镇上的产业。", "Next I'll talk about industry in our town."],
		["在书店买了杂志。", "I bought a magazine at the bookstore."],
	],
	"w3d2": [
		["做完作业再看电视。", "I watch TV after I do my homework."],
		["休息日打扫卫生、洗衣服。", "On days off I clean and do laundry."],
		["今天天气好，心情很好。", "It's nice weather today, and I feel good."],
		["不好意思，可以提问吗？", "Excuse me, may I ask a question?"],
		["去看村里的庙会吧。", "Let's go see the village festival."],
		["今天星期几？", "What day of the week is it today?"],
		["那个人很有钱。", "That person is rich."],
		["特快这站不停。", "The limited express doesn't stop at this station."],
	],
	"w3d3": [
		["请随便坐喜欢的地方。", "Please sit wherever you like."],
		["我现在在学花道。", "I'm learning ikebana now."],
		["那样的衣服在哪儿卖？", "Where do they sell clothes like that?"],
		["学了就要好好练习。", "After you learn it, practice well."],
		["坐特快去吧。", "Let's take the limited express."],
		["这本书是在图书馆借的。", "I borrowed this book from the library."],
		["养着的狗死了。", "The dog I was keeping died."],
		["能借我一支笔吗？", "Could you lend me a pen?"],
	],
	"w3d4": [
		["没时间了，赶紧走。", "There's no time, so let's hurry."],
		["那个人块头大，心很善良。", "That person is big, and kind-hearted."],
		["明天考试，所以今天学习。", "There's a test tomorrow, so I'll study today."],
		["想好了再写作文。", "I'll think, then write the composition."],
		["太太身体好吗？", "How is your wife?"],
		["在日本过年吃年糕。", "In Japan we eat rice cakes at New Year."],
		["明天去看篮球比赛。", "I'm going to watch a basketball game tomorrow."],
		["妈妈在药店工作。", "My mother works at a pharmacy."],
	],
	"w3d5": [
		["N4 考试合格了。", "I passed the N4 exam."],
		["字太小，请再放大一点。", "The letters are small, so please make them a bit bigger."],
		["定一下派对的时间和地点吧。", "Let's decide the time and place of the party."],
		["那个人是我重要的朋友。", "That person is an important friend of mine."],
		["今天非常开心。", "Today was a lot of fun."],
		["请在信上贴邮票。", "Please put a stamp on the letter."],
		["几点出门才能赶上课？", "What time should I leave home to make it to class?"],
		["午饭自己做。", "I make lunch myself."],
	],
	"w3d6": [
		["妈妈在医院工作。", "My mother works at a hospital."],
		["每天在公司食堂吃午饭。", "I eat lunch in the company cafeteria every day."],
		["去海岸散步吧。", "Let's take a walk along the coast."],
		["海和山你更喜欢哪个？", "Which do you like better, the sea or the mountains?"],
		["就算跑也赶不上公交了吧。", "Even if we run, we probably won't make the bus."],
		["寒假回国。", "I'll go back to my country for winter vacation."],
		["那棵树上聚了很多小鸟。", "Lots of little birds gather in that tree."],
		["在银行汇款。", "I send money at the bank."],
	],
}
